## People Centered COS - Convert CDOT Data format (2007-2020) to the 2021+ data format 

 #### Part 1 - SCRATCH PAD --- (THIS NOTEBOOK) convert information on road condition, lighting, location, number of vehicles and people etc.

In [1]:
pip install pandas

Requirement already satisfied: pandas in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

### Load CDOT csvs

In [4]:
cdot_base_path = "/Users/haley.northrup/Desktop/PeopleCenteredCOS/cdot_data/"

In [5]:
# Load CDOT Data from new data format (2021+) 

year_new = 2023
filename_new = f"CDOTRM_CD_Crash_Listing_-_{year_new}.xlsx"

full_path_new = cdot_base_path + filename_new
print(full_path_new)

cdot_new_pdf = pd.read_excel(full_path_new)
display(cdot_new_pdf.head(5))

/Users/haley.northrup/Desktop/PeopleCenteredCOS/cdot_data/CDOTRM_CD_Crash_Listing_-_2023.xlsx

,CUID,System Code,Rd_Number,Rd_Section,City_Street,Crash Date,Crash Time,Agency Id,City,County,...,TU-2 NM Safety Helmet,TU-1 NM Alcohol Suspected,TU-2 NM Alcohol Suspected,TU-1 NM Marijuana Suspected,TU-2 NM Marijuana Suspected,TU-1 NM Other Drugs Suspected,TU-2 NM Other Drugs Suspected,Record Status,Processing Status,Last Updated
0,296027,City Street,0455,VERMO,TIMBE,2023-01-01,00:00:00,FTCPD,FORT COLLINS,LARIMER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Aug 4 2023 11:35PM
1,299624,City Street,0455,HARMO,TIMBE,2023-01-01,00:03:00,FTCPD,FORT COLLINS,LARIMER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Apr 6 2023 10:08PM
2,289075,City Street,0320,KALAM,CEDAR,2023-01-01,00:09:00,DPD,DENVER,DENVER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Feb 8 2023 8:29PM
3,293978,City Street,0055,LINVA,LARED,2023-01-01,00:16:00,AURPD,AURORA,ARAPAHOE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,May 5 2023 8:02PM
4,299717,State Highway,095A,12.906,NaN,2023-01-01,00:34:00,WMPD,WESTMINSTER,JEFFERSON,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Feb 15 2023 1:35PM

In [6]:
# Load CDOT Data from old data format (2007-2020) 

year = 2007
filename_old = f"CDOTRM_CD_Crash_Listing_-_{year}.xlsx"

full_path_old = cdot_base_path + filename_old
print(full_path_old)

cdot_old_pdf = pd.read_excel(full_path_old)
display(cdot_old_pdf.head(5))

/Users/haley.northrup/Desktop/PeopleCenteredCOS/cdot_data/CDOTRM_CD_Crash_Listing_-_2007.xlsx

,SYSTEM,RTE,SEC,MP,DATE,TIME,SEVERITY,INJURY 00,INJURY 01,INJURY 02,...,DRVINJ_1,DRVINJ_2,DRVINJ_3,DUI_1,DUI_2,DUI_3,CITY,COUNTY,LATITUDE,LONGITUDE
0,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,2,0,0,...,NO INJURY,NO INJURY,NaN,N,N,N,FORT COLLINS,LARIMER,40.55955,-105.045929
1,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,1,0,0,...,NO INJURY,NaN,NaN,N,N,N,PARKER,DOUGLAS,39.51831,-104.774870
2,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,1,0,0,...,NaN,NO INJURY,NaN,N,N,N,DENVER,DENVER,39.66372,-105.075380
3,INTERSTATE,70,A,387.3,2007-01-01,2.0,PDO,7,0,0,...,NO INJURY,NO INJURY,NaN,N,N,N,NaN,LINCOLN,39.28565,-103.196810
4,CITY STREET,0,NaN,0.0,2007-01-01,10.0,PDO,4,0,0,...,NO INJURY,NO INJURY,NaN,N,N,N,AURORA,ARAPAHOE,39.65800,-104.777000

### Create a new dataframe to be converted

In [7]:
# Make a copy to edit
cdot_old_converted_pdf = cdot_old_pdf

###  Convert Road Number, Section, Street

##### Rd_Number, Rd_Section, City_Street

In [8]:
# Convert SYSTEM (old column) to System Code (new column)
old_column = 'SYSTEM'
new_column = 'System Code'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].str.lower().str.title()
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format SYSTEM ['CITY STREET' 'INTERSTATE' 'COUNTY ROAD' 'STATE HIGHWAY' 'FRONTAGE ROAD']
New format System Code ['City Street' 'State Highway' 'Interstate Highway' 'County Road'
 'Frontage Road']
Old converted format System Code ['City Street' 'Interstate' 'County Road' 'State Highway' 'Frontage Road']

In [9]:
# REVISIT **** - RTE, SEC, MP -- Rd_Number and Rd_Section 
# Convert RTE (old column) to Rd_Number (new column)

print(f"Old format SEC", cdot_old_pdf["SEC"].unique())
print(f"Old format RTE", cdot_old_pdf["RTE"].unique())
print(f"Old format MP", cdot_old_pdf["MP"].unique())

print(f"New format Rd_Number", cdot_new_pdf["Rd_Number"].unique())
print(f"New format Rd_Number", cdot_new_pdf["Rd_Section"].unique())

Old format SEC [nan 'A' 'B' 'D' 'C' 'G' 'F' 'H' 'J' 'Z' 'K' 'E' 'L' 'N' 'M' 'W' '8' '9'
 'd']
Old format RTE [  0  70  25 402  36 285  88  76 287   6 119   2  30  40  95  24  21  34
   9 121  86  85  13  83  75   7  82  50 550  74 470 225 160  66 145  64
 391  14 340  65  47  26 227  35 265  72  45  96 157 128  52  91 177 224
 172  10  53 105 115 141 138 392  56  42 131 394 125   1  79  92 270  94
  60  16  84 491  17 133  12 151  93 385 114  71 109 139 348 113   3  63
   8 135  15  62 184 257 167  90 140 159  58  78 165 149  67  39 144 170
  44 120 263 291 233 350 183 196 134  69 116 318 330 127 194  22  61 142
 202  59 112 266 999 325 150  46 136 317 101 370   5 103 368  97  89 347
 300 256 239 389 207]
Old format MP [  0.   387.3   98.58 ...  20.67 244.23 103.47]
New format Rd_Number ['0455' '0320' '0055' '095A' '025A' '1085' '088A' '470A' '006B' '0570'
 '1100' '0145' '040C' '036B' '006G' '4800' '1200' '082A' '076A' '002A'
 '026B' '0240' '0600' '5400' '024A' '088B' '030A' '0800' '070A' '0700'
 '036C' '009C' '016A' '3700' '009D' '1500' '040A' '045A' '0830' '285D'
 '0540' '114A' '0350' '0130' '2400' '0175' '1280' '0400' '069A' '0045'
 '1000' '0475' '1038' '006F' '006D' '3100' '072A' '4700' '550B' '0900'
 '121A' '0330' '0820' '0415' '0580' '0927' '083A' '0245' '160A' '0110'
 '225A' '287C' '034D' '034A' '0945' '050B' '2300' '0300' '040H' '017A'
 '006E' '145A' '0465' '1250' '141B' '285A' '010A' '1380' '1235' '1285'
 '085C' '2000' '070B' '0555' '085A' '050A' '064A' '550A' '0270' '085B'
 '1355' '024G' '060B' '066B' '470N' '128A' '009B' '2500' '177A' '014B'
 '040B' '084A' '0125' '065A' '039A' '0817' '044A' '1135' '0385' '1223'
 '340A' '5200' '491B' '0185' '1195' '2800' '470B' '096C' '0910' '034B'
 '318A' '287A' '119C' '092A' '157A' '5000' '2200' '0590' '391A' '070Z'
 '007D' '350A' '021A' '096A' '047A' '119B' '402A' '0735' '003A' '0059'
 '0430' '287B' '6100' '0535' '2900' '224A' '0745' '0390' '0040' '1900'
 '0490' '3200' '4200' '0015' '0760' '115A' '285B' '1360' '024H' '052A'
 '1125' '0810' '074A' '1086' '128B' '184B' '0395' '2600' '1055' '0825'
 '091A' '0813' '093A' '007C' '1600' '257A' '127A' '013B' '119A' '0060'
 '3400' '1375' '144A' '125A' '0765' '1400' '4400' '042A' '0200' '270A'
 '105A' '2100' '006J' '094A' '139A' '014C' '392A' '021B' '270B' '0193'
 '1330' '0210' '067F' '007B' '0470' '071A' '5300' '0315' '4300' '096B'
 '0180' '1290' '4500' '3900' '141A' '0380' '0715' '0086' '006H' '131B'
 '013A' '392B' '0255' '0690' '2700' '0090' '0530' '008A' '1005' '142A'
 '133A' '052B' '040Z' '086B' '5700' '085H' '071D' '196A' '165A' '1378'
 '3800' '160Z' '0550' '3600' '135A' '0435' '006M' '4900' '291A' '1306'
 '1325' '5100' '140A' '385C' '0885' '0940' '085L' '3000' '3300' '0915'
 '159A' '1300' '0080' '0660' '0595' '1255' '1800' '050C' '285C' '009A'
 '006A' '006N' '0248' '036E' '0650' '0050' '0075' '059B' '001A' '109A'
 '0150' '134A' '063A' '024C' '0370' '0052' '4100' '079A' '287Z' '0500'
 '172A' '1363' '071F' '0097' '015B' '034Z' '085G' '0710' '1160' '089A'
 '0925' '0295' '058A' '067D' '014A' '079B' '0665' '265B' '1015' '121B'
 '103A' '023A' '0250' '1270' '325A' '017B' '491A' '085F' '0505' '006K'
 '194A' '3500' '207A' '0381' '070G' '0405' '056B' '470W' '0970' '036D'
 '071C' '090B' '0120' '086A' '024B' '1395' '0865' '113A' '149A' '151A'
 '160C' '059A' '0333' '0775' '5600' '4000' '0477' '0630' '0388' '002D'
 '050Z' '112A' '0280' '116A' '0850' '015A' '0066' '1700' '075B' '035A'
 '0450' '385D' '4600' '006L' '0935' '072B' '067A' '090A' '0061' '006C'
 '062A' '1225' '348A' '136A' '6000' '330A' '025C' '0485' '265A' '0615'
 '170A' '371A' '0875' '060A' '078A' '050D' '085E' '394A' '071B' '0480'
 '167A' '0985' '025A ' '070L' '0010' '385A' '0640' '012A' '024F' '0260'
 '071E' '184A' '053A' '1150' '067E' '0065' '024E' '007A' '0451' '239A'
 '096D' '105B' '1020' '120A' '0560' '0755' '0696' '024H ' '036A' '0965'
 '138A' '055A' '370A' '1295' '091C' '0920' '0790' '011A' '0155' '061A'
 '0160' '1385' '013C' '0420' '024I' '0730' '1299' '0610' '0695' '491B '
 '231A' '1210' '0525' '0575' '0195' '1059' '1046' '0105' '046A' '0454'
 '0960' '266A' '0184' '034C' '0237' '347A' '109B' '101A' '1345' '024D'
 '0360' '025B' '1310' '0621' '0750' '5900' '0440' '022A' '078B' '368A'
 '160?' '5800' '1220' '1350' '1120' '067B' '150A' '0026' '1276' '0770'
 '067C' '034' '0845' '070E' '1383' '1035' '0335' '491C' '0165' '5500'
 '0063' '257B' '0880' '0711' '0655' '1170' '070M' '1165' '036Z' '6300'
 '070O' '0305' '040E' '0027' '0235' '183A' '0617' '1344' '0322' '300A'
 '0345' '1260' '0835' '0241' '6200' '070R' '131A' '0355' '1037' '0542'
 '070K' '1240' '227A' '34A' '385B' '202A' '1115' '0223' '0417' '0751'
 '0163' '0780' '0095' '1049' '0416' '1091' '057A']
New format Rd_Number ['VERMO' 'HARMO' 'KALAM' ... '212.732' '67.900' '1.904']

In [10]:
cdot_old_pdf.loc[cdot_old_pdf['SYSTEM'] == 'CITY STREET', ['SYSTEM', 'MP', 'SEC', 'RTE', 'LOC_01', 'LOC_02']]

             SYSTEM   MP  SEC  RTE            LOC_01          LOC_02
0       CITY STREET  0.0  NaN    0  1720 KIRKWOOD DR        1700 BLK
1       CITY STREET  0.0  NaN    0           MAIN ST  TWENTY MILE RD
2       CITY STREET  0.0  NaN    0      SAULSBURY ST          2803 S
4       CITY STREET  0.0  NaN    0   DARTMOUTH AVE E       S WACO ST
9       CITY STREET  0.0  NaN    0          20TH AVE        PEARL ST
...             ...  ...  ...  ...               ...             ...
112179  CITY STREET  0.0  NaN    0       LOWELL BLVD        14TH AVE
112180  CITY STREET  0.0  NaN    0        LINCOLN ST        17TH AVE
112185  CITY STREET  0.0  NaN    0           26TH ST        13TH AVE
112187  CITY STREET  0.0  NaN    0       KALAMATH ST        11TH AVE
112190  CITY STREET  0.0  NaN    0         KENTON ST   DARTMOUTH AVE

[50587 rows x 6 columns]

In [11]:
cdot_new_pdf.loc[cdot_new_pdf['System Code'] == 'City Street', ['System Code', 'Rd_Number', 'Rd_Section', 'Location 1', 'Location 2']]

        System Code Rd_Number Rd_Section        Location 1       Location 2
0       City Street      0455      VERMO        VERMONT DR         2212 BLK
1       City Street      0455      HARMO      E HARMONY RD  S TIMBERLINE RD
2       City Street      0320      KALAM     S KALAMATH ST      W CEDAR AVE
3       City Street      0055      LINVA     E LINVALE AVE      S LAREDO ST
6       City Street      1085      6THST         W 6TH ST        N MAIN ST
...             ...       ...        ...               ...              ...
102160  City Street      0320      LOGAN        S LOGAN ST    E ALAMEDA AVE
102161  City Street      0320      LOGAN        S LOGAN ST    E ALAMEDA AVE
102162  City Street      0590      BOULE    S BOULEVARD ST     SAN JUAN AVE
102164  City Street      0415      MOUNT  MOUNTAIN VIEW DR         3722 BLK
102165  City Street      1085      KINGS   1609 KINGSROYAL         ARCH WAY

[43382 rows x 5 columns]

In [12]:
cdot_old_pdf.loc[cdot_old_pdf['SYSTEM'] == 'INTERSTATE', ['SYSTEM', 'MP', 'SEC', 'RTE','LOC_01', 'LOC_02']]

            SYSTEM      MP SEC  RTE          LOC_01               LOC_02
3       INTERSTATE  387.30   A   70            I-70               MM 387
6       INTERSTATE   98.58   A   25  I-25 (100 BLK)              100 BLK
18      INTERSTATE  212.01   A   25            I-25              20TH ST
21      INTERSTATE   10.07   A   76            I-76             88TH AVE
53      INTERSTATE  100.09   A   25  I-25 SB 2100 N            EXIT 100A
...            ...     ...  ..  ...             ...                  ...
112137  INTERSTATE  223.05   A   25       120TH AVE  SB HWY I-25 ON RAMP
112150  INTERSTATE  212.73   A   25            I-25   E 38TH AVE ON RAMP
112181  INTERSTATE  174.00   A   70            I-70               MM 174
112182  INTERSTATE  264.34   A   70        32ND AVE      I-70 WB ON RAMP
112188  INTERSTATE  174.00   A   70            I-70                MM174

[14156 rows x 6 columns]

In [13]:
cdot_new_pdf.loc[cdot_new_pdf['System Code'] == 'Interstate Highway', ['System Code', 'Rd_Number', 'Rd_Section', 'Location 1', 'Location 2']]

,System Code,Rd_Number,Rd_Section,Location 1,Location 2
5,Interstate Highway,025A,227.35,15500 I-25 NB,MM 227.35
25,Interstate Highway,025A,143,I-25 NB,MM 143
28,Interstate Highway,025A,141.30,I-25 SB EXIT RAMP,W CIMARRON ST
29,Interstate Highway,076A,16.47,I-76,HWY 2
39,Interstate Highway,025A,98.99,I-25,MM 99
...,...,...,...,...,...
102119,Interstate Highway,270A,4.729,I-270 EB OFF RAMP,N NORTHFIELD QUEBEC ST
102122,Interstate Highway,025A,212.202,I-25,20TH ST
102130,Interstate Highway,070A,244.343,I-70,MM 244.343
102150,Interstate Highway,025A,212.737,PARK AVE W,I-25 NB RAMPS
102151,Interstate Highway,025A,212.732,PARK AVE W,I-25 EB RAMPS

In [14]:
cdot_old_pdf.loc[cdot_old_pdf['SYSTEM'] == 'COUNTY ROAD', ['SYSTEM', 'MP', 'SEC', 'RTE','LOC_01', 'LOC_02']]

             SYSTEM   MP  SEC  RTE           LOC_01            LOC_02
5       COUNTY ROAD  0.0  NaN    0  SHADOW ROCK RUN  SLEEPING BEAR TR
11      COUNTY ROAD  0.0  NaN    0       HILLTOP RD    FLINTWOOD RD S
13      COUNTY ROAD  0.0  NaN    0        COPPER RD            HWY 91
17      COUNTY ROAD  0.0  NaN    0            CR 17            TRILBY
20      COUNTY ROAD  0.0  NaN    0            CR 81             CR 78
...             ...  ...  ...  ...              ...               ...
112171  COUNTY ROAD  0.0  NaN    0        MONROE WY           84TH DR
112176  COUNTY ROAD  0.0  NaN    0         68TH AVE         WARREN DR
112177  COUNTY ROAD  0.0  NaN    0             K RD         22 1/2 RD
112184  COUNTY ROAD  0.0  NaN    0  WITTER GULCH RD        STAGECOACH
112189  COUNTY ROAD  0.0  NaN    0   ACRES GREEN DR        SCORPIO DR

[9707 rows x 6 columns]

In [15]:
cdot_new_pdf.loc[cdot_new_pdf['System Code'] == 'County Road', ['System Code', 'Rd_Number', 'Rd_Section', 'Location 1', 'Location 2']]

        System Code Rd_Number Rd_Section          Location 1    Location 2
14      County Road      1100      BELLE     W BELLEVIEW AVE  RED DEER TRL
18      County Road      1100      SHADO  SHADOW MOUNTAIN DR  S WARHAWK RD
22      County Road      4800      PAGOS       N PAGOSA BLVD   CAPITAN CIR
24      County Road      1200      PECOS            PECOS ST    W 76TH AVE
35      County Road      0600      LARIM               CR 43    H BAR G RD
...             ...       ...        ...                 ...           ...
102121  County Road      0700      BOULD        S BOULDER RD       68TH ST
102124  County Road      0800      SUNSE     SUNSET HILLS RD       190 BLK
102129  County Road      1000      ARAPA         ARAPAHOE RD    3000 BLK E
102153  County Road      0600       CR43               CR 43  MACGREGOR RD
102163  County Road      1200      PECOS            PECOS ST    ELMWOOD LN

[9721 rows x 5 columns]

In [16]:
cdot_old_pdf.loc[cdot_old_pdf['SYSTEM'] == 'STATE HIGHWAY', ['SYSTEM', 'MP', 'SEC', 'RTE','LOC_01', 'LOC_02']]

               SYSTEM      MP SEC  RTE             LOC_01             LOC_02
7       STATE HIGHWAY    1.00   A  402         14TH ST SE  CR 11H (BOISE ST)
8       STATE HIGHWAY   25.10   B   36             HWY 36              MM 25
15      STATE HIGHWAY  259.15   D  285            HWY 285             MM 259
16      STATE HIGHWAY   17.13   B   88        S BOSTON ST      E ARAPAHOE RD
23      STATE HIGHWAY  346.45   C  287  COLLEGE AVE S 232           OLIVE ST
...               ...     ...  ..  ...                ...                ...
112160  STATE HIGHWAY   35.28   A   82             HWY 82     BRUSH CREEK RD
112162  STATE HIGHWAY    1.49   A   88       FEDERAL BLVD            1ST AVE
112170  STATE HIGHWAY  206.01   B   85        SANTA FE DR       W OXFORD AVE
112183  STATE HIGHWAY  346.22   C  287        MULBERRY ST        COLLEGE AVE
112186  STATE HIGHWAY    1.31   A   45        PUEBLO BLVD        PRAIRIE AVE

[37310 rows x 6 columns]

In [17]:
cdot_new_pdf.loc[cdot_new_pdf['System Code'] == 'State Highway', ['System Code', 'Rd_Number', 'Rd_Section', 'Location 1', 'Location 2']]

          System Code Rd_Number Rd_Section         Location 1   Location 2
4       State Highway      095A     12.906    N SHERIDAN BLVD    W 79TH ST
8       State Highway      088A      1.659  50 S FEDERAL BLVD  W ARCHER PL
9       State Highway      470A     17.000              C-470        MM 17
10      State Highway      006B     33.599          NORTH AVE        29 RD
13      State Highway      470A     17.000              C-470        MM 17
...               ...       ...        ...                ...          ...
102139  State Highway      470A      5.438              C-470     MM 5.438
102140  State Highway      030A      4.276        E ILIFF AVE  S HAVANA ST
102145  State Highway      092A      5.566             HWY 92     MM 5.566
102154  State Highway      050A     67.900             HWY 50     1375 BLK
102157  State Highway      125A      1.904            HWY 125     MM 1.904

[33844 rows x 5 columns]

In [18]:
cdot_old_pdf.loc[cdot_old_pdf['SYSTEM'] == 'FRONTAGE ROAD', ['SYSTEM', 'MP', 'SEC', 'RTE','LOC_01', 'LOC_02']]

,SYSTEM,MP,SEC,RTE,LOC_01,LOC_02
74,FRONTAGE ROAD,255.83,D,285,HAMPDEN FRONTAGE 6200 BLK,KENDALL ST
724,FRONTAGE ROAD,173.30,A,70,2399 N FRONTAGE RD,NaN
725,FRONTAGE ROAD,138.46,C,14,MULBERRY ST,SHERRY DR.
819,FRONTAGE ROAD,244.20,A,25,CR 32,I-25 FRONTAGE RD
822,FRONTAGE ROAD,236.70,A,25,I-25 FRNTG RD,COMMERCE DR
...,...,...,...,...,...,...
111381,FRONTAGE ROAD,278.05,G,6,6TH AVE W FRONTAGE RD N,URBAN CT
111901,FRONTAGE ROAD,245.22,A,25,CR 34,I-25 E FRONTAGE RD
111914,FRONTAGE ROAD,175.61,A,70,548 S FRONTAGE RD,WESTWIND
111919,FRONTAGE ROAD,173.94,A,70,N FRONTAGE RD W,BUFFEHR CREEK
112035,FRONTAGE ROAD,26.71,A,76,I-76 FRONTAGE RD,CO RD 4

In [19]:
cdot_new_pdf.loc[cdot_new_pdf['System Code'] == 'Frontage Road', ['System Code', 'Rd_Number', 'Rd_Section', 'Location 1', 'Location 2']]

,System Code,Rd_Number,Rd_Section,Location 1,Location 2
591,Frontage Road,070A,173.944,N FRONTAGE RD W,BUFFEHR CREEK RD
611,Frontage Road,070A,175.650,S FRONTAGE RD W,E LIONSHEAD CIRCLE
909,Frontage Road,025A,248.237,I-25 FRONTAGE RD,CR 40
1476,Frontage Road,070A,116.02,I-70 FRONTAGE RD,TRAVER TRL N
1654,Frontage Road,070A,178.500,FRONTAGE RD E,1600 BLK S
...,...,...,...,...,...
100913,Frontage Road,025A,274.382,I-25 FRT RD W,MM 274.382
101296,Frontage Road,076A,10.694,BRIGHTON RD,E 88TH AVE
101681,Frontage Road,070A,173.308,I-70 FRONTAGE RD S,CHAMONIX RD
101685,Frontage Road,025A,261.262,SW FRONTAGE RD,CR 30
101938,Frontage Road,025A,180.667,I-25 FRONTAGE RD W,PLUM CREEK PKWY

In [20]:
# Rd_Number

import numpy as np

# set Rd_Number to none since I'm not sure how to do these mappings
cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['City Street', 'County Road']), 'Rd_Number'] = np.nan
display(cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['City Street', 'County Road'])])

# Rd_Number is the RTE (with 3 digits) and the SEC
cdot_old_converted_pdf['RTE_3dig'] = cdot_old_converted_pdf['RTE'].apply(lambda x: f"{x:03}")
cdot_old_converted_pdf['RTE_3dig_SEC'] = cdot_old_converted_pdf['RTE_3dig'] + cdot_old_converted_pdf['SEC']
# display(cdot_old_converted_pdf[['RTE', 'RTE_3dig','RTE_3dig_SEC']])

cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['Interstate Highway', 'State Highway', 'Frontage Road']), 'Rd_Number'] = \
    cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['Interstate Highway', 'State Highway', 'Frontage Road']), 'RTE_3dig_SEC'] 

display(cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['Interstate Highway', 'State Highway', 'Frontage Road'])])

,SYSTEM,RTE,SEC,MP,DATE,TIME,SEVERITY,INJURY 00,INJURY 01,INJURY 02,...,DRVINJ_3,DUI_1,DUI_2,DUI_3,CITY,COUNTY,LATITUDE,LONGITUDE,System Code,Rd_Number
0,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,2,0,0,...,NaN,N,N,N,FORT COLLINS,LARIMER,40.55955,-105.045929,City Street,NaN
1,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,1,0,0,...,NaN,N,N,N,PARKER,DOUGLAS,39.51831,-104.774870,City Street,NaN
2,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,1,0,0,...,NaN,N,N,N,DENVER,DENVER,39.66372,-105.075380,City Street,NaN
4,CITY STREET,0,NaN,0.0,2007-01-01,10.0,PDO,4,0,0,...,NaN,N,N,N,AURORA,ARAPAHOE,39.65800,-104.777000,City Street,NaN
5,COUNTY ROAD,0,NaN,0.0,2007-01-01,15.0,INJ,1,1,0,...,NaN,N,N,N,NaN,DOUGLAS,39.46586,-105.088140,County Road,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112184,COUNTY ROAD,0,NaN,0.0,2007-12-31,2330.0,PDO,3,0,0,...,NaN,N,N,N,NaN,CLEAR CREEK,39.65105,-105.416160,County Road,NaN
112185,CITY STREET,0,NaN,0.0,2007-12-31,2341.0,PDO,4,0,0,...,NaN,N,N,N,GREELEY,WELD,40.41175,-104.699960,City Street,NaN
112187,CITY STREET,0,NaN,0.0,2007-12-31,2343.0,PDO,2,0,0,...,NaN,N,N,N,DENVER,DENVER,39.73369,-105.000150,City Street,NaN
112189,COUNTY ROAD,0,NaN,0.0,2007-12-31,2350.0,PDO,1,0,0,...,NaN,N,N,N,NaN,DOUGLAS,39.55904,-104.896640,County Road,NaN
112190,CITY STREET,0,NaN,0.0,2007-12-31,2355.0,PDO,3,0,0,...,NaN,N,N,N,DENVER,DENVER,39.66022,-104.858990,City Street,NaN

/var/folders/wh/mh9pm3896vb556vt9fxjp6sc0000gq/T/ipykernel_11881/228033779.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['402A' '036B' '285D' ... '085B' '287C' '045A']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['Interstate Highway', 'State Highway', 'Frontage Road']), 'Rd_Number'] = \

,SYSTEM,RTE,SEC,MP,DATE,TIME,SEVERITY,INJURY 00,INJURY 01,INJURY 02,...,DUI_2,DUI_3,CITY,COUNTY,LATITUDE,LONGITUDE,System Code,Rd_Number,RTE_3dig,RTE_3dig_SEC
7,STATE HIGHWAY,402,A,1.00,2007-01-01,39.0,PDO,3,0,0,...,N,N,NaN,LARIMER,40.378335,-105.054310,State Highway,402A,402,402A
8,STATE HIGHWAY,36,B,25.10,2007-01-01,43.0,PDO,1,0,0,...,N,N,NaN,BOULDER,40.167402,-105.266613,State Highway,036B,036,036B
15,STATE HIGHWAY,285,D,259.15,2007-01-01,103.0,INJ,0,0,1,...,N,N,SHERIDAN,ARAPAHOE,39.653583,-105.005925,State Highway,285D,285,285D
16,STATE HIGHWAY,88,B,17.13,2007-01-01,109.0,PDO,2,0,0,...,N,N,GREENWOOD VILLAGE,ARAPAHOE,39.595010,-104.880886,State Highway,088B,088,088B
23,STATE HIGHWAY,287,C,346.45,2007-01-01,135.0,INJ,1,0,1,...,N,N,FORT COLLINS,LARIMER,40.584751,-105.077087,State Highway,287C,287,287C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112160,STATE HIGHWAY,82,A,35.28,2007-12-31,2040.0,PDO,7,0,0,...,N,N,NaN,PITKIN,39.249718,-106.883928,State Highway,082A,082,082A
112162,STATE HIGHWAY,88,A,1.49,2007-12-31,2045.0,PDO,1,0,0,...,N,N,DENVER,DENVER,39.718416,-105.025071,State Highway,088A,088,088A
112170,STATE HIGHWAY,85,B,206.01,2007-12-31,2132.0,PDO,3,0,0,...,N,N,SHERIDAN,ARAPAHOE,39.642121,-105.005776,State Highway,085B,085,085B
112183,STATE HIGHWAY,287,C,346.22,2007-12-31,2313.0,PDO,3,0,0,...,N,N,FORT COLLINS,LARIMER,40.581502,-105.077110,State Highway,287C,287,287C
112186,STATE HIGHWAY,45,A,1.31,2007-12-31,2342.0,INJ,1,0,2,...,N,N,PUEBLO,PUEBLO,38.219990,-104.643721,State Highway,045A,045,045A

In [21]:
# Rd_Section 
import re

def convert_location1_to_rd_number(LOC01):
    drop_numbers = re.sub(r'\\d+\\s', '', str(LOC01))
    drop_single_letters = re.sub('\\s[a-z]\\s', '', drop_numbers)
    split_list = drop_single_letters.split()
    if len(split_list) == 0:
        return np.nan
    else:
        get_first_word = split_list[0]
        first_word_first_five_letters_uppercase = get_first_word[0:5].upper()
        return first_word_first_five_letters_uppercase
    
# set Rd_Section to part of location 1 for City Street and County Road
cdot_old_converted_pdf['Location 1'] = cdot_old_pdf['LOC_01']
cdot_old_converted_pdf['Location 1 converted to Rd_Section'] = cdot_old_converted_pdf['Location 1'].apply(convert_location1_to_rd_number)
cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['City Street', 'County Road']), 'Rd_Section'] = \
    cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['City Street', 'County Road']), 'Location 1 converted to Rd_Section']

# Rd_Section is MP for Highways and Frontage roads
cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['Interstate Highway', 'State Highway', 'Frontage Road']), 'Rd_Section'] = \
    cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['Interstate Highway', 'State Highway', 'Frontage Road']), 'MP'] 

display(cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['City Street', 'County Road'])])
display(cdot_old_converted_pdf.loc[cdot_old_converted_pdf['System Code'].isin(['Interstate Highway', 'State Highway', 'Frontage Road'])])

,SYSTEM,RTE,SEC,MP,DATE,TIME,SEVERITY,INJURY 00,INJURY 01,INJURY 02,...,COUNTY,LATITUDE,LONGITUDE,System Code,Rd_Number,RTE_3dig,RTE_3dig_SEC,Location 1,Location 1 converted to Rd_Section,Rd_Section
0,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,2,0,0,...,LARIMER,40.55955,-105.045929,City Street,NaN,000,NaN,1720 KIRKWOOD DR,1720,1720
1,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,1,0,0,...,DOUGLAS,39.51831,-104.774870,City Street,NaN,000,NaN,MAIN ST,MAIN,MAIN
2,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,1,0,0,...,DENVER,39.66372,-105.075380,City Street,NaN,000,NaN,SAULSBURY ST,SAULS,SAULS
4,CITY STREET,0,NaN,0.0,2007-01-01,10.0,PDO,4,0,0,...,ARAPAHOE,39.65800,-104.777000,City Street,NaN,000,NaN,DARTMOUTH AVE E,DARTM,DARTM
5,COUNTY ROAD,0,NaN,0.0,2007-01-01,15.0,INJ,1,1,0,...,DOUGLAS,39.46586,-105.088140,County Road,NaN,000,NaN,SHADOW ROCK RUN,SHADO,SHADO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112184,COUNTY ROAD,0,NaN,0.0,2007-12-31,2330.0,PDO,3,0,0,...,CLEAR CREEK,39.65105,-105.416160,County Road,NaN,000,NaN,WITTER GULCH RD,WITTE,WITTE
112185,CITY STREET,0,NaN,0.0,2007-12-31,2341.0,PDO,4,0,0,...,WELD,40.41175,-104.699960,City Street,NaN,000,NaN,26TH ST,26TH,26TH
112187,CITY STREET,0,NaN,0.0,2007-12-31,2343.0,PDO,2,0,0,...,DENVER,39.73369,-105.000150,City Street,NaN,000,NaN,KALAMATH ST,KALAM,KALAM
112189,COUNTY ROAD,0,NaN,0.0,2007-12-31,2350.0,PDO,1,0,0,...,DOUGLAS,39.55904,-104.896640,County Road,NaN,000,NaN,ACRES GREEN DR,ACRES,ACRES
112190,CITY STREET,0,NaN,0.0,2007-12-31,2355.0,PDO,3,0,0,...,DENVER,39.66022,-104.858990,City Street,NaN,000,NaN,KENTON ST,KENTO,KENTO

,SYSTEM,RTE,SEC,MP,DATE,TIME,SEVERITY,INJURY 00,INJURY 01,INJURY 02,...,COUNTY,LATITUDE,LONGITUDE,System Code,Rd_Number,RTE_3dig,RTE_3dig_SEC,Location 1,Location 1 converted to Rd_Section,Rd_Section
7,STATE HIGHWAY,402,A,1.00,2007-01-01,39.0,PDO,3,0,0,...,LARIMER,40.378335,-105.054310,State Highway,402A,402,402A,14TH ST SE,14TH,1.0
8,STATE HIGHWAY,36,B,25.10,2007-01-01,43.0,PDO,1,0,0,...,BOULDER,40.167402,-105.266613,State Highway,036B,036,036B,HWY 36,HWY,25.1
15,STATE HIGHWAY,285,D,259.15,2007-01-01,103.0,INJ,0,0,1,...,ARAPAHOE,39.653583,-105.005925,State Highway,285D,285,285D,HWY 285,HWY,259.15
16,STATE HIGHWAY,88,B,17.13,2007-01-01,109.0,PDO,2,0,0,...,ARAPAHOE,39.595010,-104.880886,State Highway,088B,088,088B,S BOSTON ST,S,17.13
23,STATE HIGHWAY,287,C,346.45,2007-01-01,135.0,INJ,1,0,1,...,LARIMER,40.584751,-105.077087,State Highway,287C,287,287C,COLLEGE AVE S 232,COLLE,346.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112160,STATE HIGHWAY,82,A,35.28,2007-12-31,2040.0,PDO,7,0,0,...,PITKIN,39.249718,-106.883928,State Highway,082A,082,082A,HWY 82,HWY,35.28
112162,STATE HIGHWAY,88,A,1.49,2007-12-31,2045.0,PDO,1,0,0,...,DENVER,39.718416,-105.025071,State Highway,088A,088,088A,FEDERAL BLVD,FEDER,1.49
112170,STATE HIGHWAY,85,B,206.01,2007-12-31,2132.0,PDO,3,0,0,...,ARAPAHOE,39.642121,-105.005776,State Highway,085B,085,085B,SANTA FE DR,SANTA,206.01
112183,STATE HIGHWAY,287,C,346.22,2007-12-31,2313.0,PDO,3,0,0,...,LARIMER,40.581502,-105.077110,State Highway,287C,287,287C,MULBERRY ST,MULBE,346.22
112186,STATE HIGHWAY,45,A,1.31,2007-12-31,2342.0,INJ,1,0,2,...,PUEBLO,38.219990,-104.643721,State Highway,045A,045,045A,PUEBLO BLVD,PUEBL,1.31

### Convert Crash Time Format

In [22]:
# Convert TIME (old column) to Crash Time (new column)
# TODO - convert float HHMM.SS to string HH:MM:SS
old_column = 'TIME'
new_column = 'Crash Time'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"Old format {old_column}", cdot_old_pdf[old_column].min())
print(f"Old format {old_column}", cdot_old_pdf[old_column].max())
display(cdot_old_pdf[old_column].head(200))
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())
display(cdot_new_pdf[new_column].head(200))

#cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column]
#print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format TIME [0.000e+00 2.000e+00 1.000e+01 ... 2.339e+03 5.020e+02 3.460e+02]
Old format TIME 0.0
Old format TIME 2400.0

0         0.0
1         0.0
2         0.0
3         2.0
4        10.0
        ...
195    2144.0
196    2152.0
197    2200.0
198    2235.0
199    2240.0
Name: TIME, Length: 200, dtype: float64

New format Crash Time ['00:00:00' '00:03:00' '00:09:00' ... '05:59:00' '00:36:00' '03:34:00']

0      00:00:00
1      00:03:00
2      00:09:00
3      00:16:00
4      00:34:00
         ...
195    03:45:00
196    03:45:00
197    03:49:00
198    03:53:00
199    03:55:00
Name: Crash Time, Length: 200, dtype: object

In [23]:
display(cdot_old_pdf.loc[cdot_old_pdf['TIME'] > 2159, 'TIME'])

197       2200.0
198       2235.0
199       2240.0
200       2245.0
201       2255.0
           ...
112186    2342.0
112187    2343.0
112188    2343.0
112189    2350.0
112190    2355.0
Name: TIME, Length: 4900, dtype: float64

In [24]:
def convert_4digit_time_to_timestr(time_4digit):
    add_colons_and_seconds = time_4digit[0:2] + ':' + time_4digit[2:4] + ':00' 
    return add_colons_and_seconds
    
cdot_old_converted_pdf['TIME'] = cdot_old_pdf['TIME']
cdot_old_converted_pdf['TIME_int_str'] = cdot_old_converted_pdf['TIME'].fillna(-1).astype(int).astype(str)
cdot_old_converted_pdf['Crash Time'] = cdot_old_converted_pdf['TIME_int_str'].apply(lambda x: f"{x:04}") \
    .apply(convert_4digit_time_to_timestr)
display(cdot_old_converted_pdf['Crash Time'])

0         00:00:00
1         00:00:00
2         00:00:00
3         20:00:00
4         10:00:00
            ...
112186    23:42:00
112187    23:43:00
112188    23:43:00
112189    23:50:00
112190    23:55:00
Name: Crash Time, Length: 112191, dtype: object

### Convert Location

In [25]:
# Convert LOCATION (old column) to Location (new column)
old_column = 'LOCATION'
new_column = 'Location'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

map_location_old_to_new = {'ON': 'On Roadway', 
                'OFF LEFT': 'Ran off left side',
                'OFF RIGHT': 'Ran off right side', 
                'OFF AT TEE': 'Ran off "T" intersection',
                'UNKNOWN': np.nan,
                'OFF IN MEDIAN': 'Center median/ Island'}
                
cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_location_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format LOCATION ['ON' 'OFF LEFT' 'OFF RIGHT' 'OFF AT TEE' 'UNKNOWN' 'OFF IN MEDIAN']
New format Location ['On Roadway' 'Ran off right side' 'Ran off left side'
 'Vehicle crossed center median into opposing lanes'
 'Center median/ Island' 'Ran off "T" intersection']
Old converted format Location ['On Roadway' 'Ran off left side' 'Ran off right side'
 'Ran off "T" intersection' nan 'Center median/ Island']

### Convert Road Description

In [26]:
# Convert ROAD_DESC (old column) to Road Description (new column)
old_column = 'ROAD_DESC'
new_column = 'Road Description'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

map_road_desc_old_to_new = {'NON-INTERSECTION': 'Non-Intersection', 
                'AT INTERSECTION': 'At Intersection',
                'INTERSECTION RELATED': 'Intersection Related', 
                'PARKING LOT': 'Parking Lot',
                'AT DRIVEWAY ACCESS': 'Driveway Access Related',
                'ROUNDABOUT': 'Roundabout',
                'RAMP': 'Ramp', 
                'IN ALLEY': 'Alley Related',
                'UNKNOWN': np.nan}
                
cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_road_desc_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format ROAD_DESC ['NON-INTERSECTION' 'AT INTERSECTION' 'INTERSECTION RELATED' 'PARKING LOT'
 'AT DRIVEWAY ACCESS' 'ROUNDABOUT' 'RAMP' 'IN ALLEY' 'UNKNOWN']
New format Road Description ['Non-Intersection' 'At Intersection' 'Intersection Related'
 'Ramp-related' 'Ramp' 'Driveway Access Related' 'Crossover-Related '
 'Roundabout' 'Railroad Crossing Related' 'Express/Managed/HOV Lane'
 'Alley Related' 'Shared-Use Path or Trail' 'Auxiliary Lane'
 'Mid-Block Crosswalk' nan 'Parking Lot']
Old converted format Road Description ['Non-Intersection' 'At Intersection' 'Intersection Related' 'Parking Lot'
 'Driveway Access Related' 'Roundabout' 'Ramp' 'Alley Related' nan]

### Convert Harmful Events

In [27]:
# Convert EVENT_1 (old column) to First HE (new column)
old_column = 'EVENT_1'
new_column = 'First HE'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

map_harmful_event_old_to_new = {
    'HEAD-ON': 'Front to Front', 
    'GUARD RAIL': 'Guardrail unspecified',
    'PARKED MOTOR VEHICLE': 'Parked Motor Vehicle', 
    'REAR-END': 'Front to Rear',
    'BROADSIDE': 'old__broadside',
    'WILD ANIMAL': 'Wild Animal',
    'DELINEATOR POST': 'Delineator/Milepost',
    'LIGHT/UTILITY POLE': 'Light Pole/Utility Pole',
    'SIDESWIPE (SAME DIRECTION)': 'Side to Side-Same Direction', 
    'OVERTURNING': 'Overturning/Rollover',
    'CONCRETE BARRIER': 'Concrete Highway Barrier', 
    'PEDESTRIAN': 'Pedestrian', 
    'INVOLVING OTHER OBJECT': 'Other Non-Fixed Object (Describe in Narrative)', 
    'SIGN': 'Sign',
    'TREE/SHRUBBERY': 'Tree',
    'EMBANKMENT CUT/FILL SLOPE': 'Embankment', 
    'MAILBOX': 'Mailbox',
    'FENCE': 'Fence', 
    'CURB/RAISED MEDIAN': 'Curb', 
    'OTHER FIXED OBJECT': 'Other Fixed Object (Describe in Narrative)',
    'ROAD MAINTENANCE EQUIPMENT': 'old__road_maintenance_equipment',
    'BRIDGE RAIL': 'Bridge Structure (Not Overhead)',
    'SIDESWIPE (OPPOSITE DIRECTION)': 'Side to Side-Opposite Direction', 
    'LARGE BOULDERS OR ROCKS': 'Large Rocks or Boulder', 
    'OTHER NON-COLLISION': 'Other Non-Collision',
    'VEHICLE CARGO/DEBRIS': 'Vehicle Debris or Cargo',
    'BICYCLE': 'Bicycle/Motorized Bicycle', 
    'DOMESTIC ANIMAL': 'Domestic Animal', 
    'CABLE RAIL': 'Cable Rail', 
    'WALL/BUILDING': 'Wall or Building', 
    'CULVERT/HEADWALL': 'Culvert or Headwall', 
    'BARRICADE/TRAFFIC BARRIER': 'Barricade',
    'TRAFFIC SIGNAL POLE': 'Traffic Signal Pole', 
    'CRASH CUSHION': 'Crash Cushion/Traffic Barrel', 
    'RAILWAY VEHICLE': 'old__railway_vehicle', 
    'OVERTAKING TURN': np.nan, 
    'APPROACH TURN': np.nan,
    'UNKNOWN': np.nan}

                
cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_harmful_event_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format EVENT_1 ['HEAD-ON' 'GUARD RAIL' 'PARKED MOTOR VEHICLE' 'REAR-END' 'BROADSIDE'
 'WILD ANIMAL' 'DELINEATOR POST' 'LIGHT/UTILITY POLE'
 'SIDESWIPE (SAME DIRECTION)' 'OVERTURNING' 'CONCRETE BARRIER'
 'PEDESTRIAN' 'INVOLVING OTHER OBJECT' 'SIGN' 'TREE/SHRUBBERY'
 'APPROACH TURN' 'EMBANKMENT CUT/FILL SLOPE' 'MAILBOX' 'FENCE' 'UNKNOWN'
 'CURB/RAISED MEDIAN' 'OTHER FIXED OBJECT' 'ROAD MAINTENANCE EQUIPMENT'
 'BRIDGE RAIL' 'SIDESWIPE (OPPOSITE DIRECTION)' 'OVERTAKING TURN'
 'LARGE BOULDERS OR ROCKS' 'OTHER NON-COLLISION' 'VEHICLE CARGO/DEBRIS'
 nan 'BICYCLE' 'DOMESTIC ANIMAL' 'CABLE RAIL' 'WALL/BUILDING'
 'CULVERT/HEADWALL' 'BARRICADE/TRAFFIC BARRIER' 'TRAFFIC SIGNAL POLE'
 'CRASH CUSHION' 'RAILWAY VEHICLE']
New format First HE ['Parked Motor Vehicle' 'Front to Side' 'Overturning/Rollover'
 'Pedestrian' 'Wall or Building' 'Concrete Highway Barrier'
 'Guardrail End' 'Front to Front' 'Front to Rear'
 'Side to Side-Same Direction' 'Tree' 'Large Rocks or Boulder'
 'Wild Animal' 'Cable Rail' 'Side to Side-Opposite Direction' 'Curb'
 'Guardrail Face' 'Light Pole/Utility Pole' 'Sign' 'Other Non-Collision'
 'Delineator/Milepost' 'Barricade' 'Embankment'
 'Bicycle/Motorized Bicycle' 'Rear to Side' 'Fence'
 'Other Non-Fixed Object (Describe in Narrative)'
 'Other Fixed Object (Describe in Narrative)' 'Ditch'
 'Railroad Crossing Equipment' 'Vehicle Debris or Cargo' 'Ground'
 'Traffic Signal Pole' 'Rear to Rear' 'Bridge Structure (Not Overhead)'
 'Electical/Utility Box' 'Culvert or Headwall' 'Mailbox'
 'Overhead Structure (Bridge)' 'Domestic Animal'
 'Crash Cushion/Traffic Barrel' 'Immersion, Full or Partial'
 'Fell from Motor Vehicle' 'Overhead Structure (Not Bridge)'
 'School Age To/From School']
Old converted format First HE ['Front to Front' 'Guardrail unspecified' 'Parked Motor Vehicle'
 'Front to Rear' 'old__broadside' 'Wild Animal' 'Delineator/Milepost'
 'Light Pole/Utility Pole' 'Side to Side-Same Direction'
 'Overturning/Rollover' 'Concrete Highway Barrier' 'Pedestrian'
 'Other Non-Fixed Object (Describe in Narrative)' 'Sign' 'Tree' nan
 'Embankment' 'Mailbox' 'Fence' 'Curb'
 'Other Fixed Object (Describe in Narrative)'
 'old__road_maintenance_equipment' 'Bridge Structure (Not Overhead)'
 'Side to Side-Opposite Direction' 'Large Rocks or Boulder'
 'Other Non-Collision' 'Vehicle Debris or Cargo'
 'Bicycle/Motorized Bicycle' 'Domestic Animal' 'Cable Rail'
 'Wall or Building' 'Culvert or Headwall' 'Barricade'
 'Traffic Signal Pole' 'Crash Cushion/Traffic Barrel'
 'old__railway_vehicle']

In [28]:
# Convert EVENT_2 (old column) to Second HE (new column)
old_column = 'EVENT_2'
new_column = 'Second HE'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_harmful_event_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format EVENT_2 [nan 'LIGHT/UTILITY POLE' 'PARKED MOTOR VEHICLE' 'OVERTURNING' 'FENCE'
 'GUARD RAIL' 'PEDESTRIAN' 'CURB/RAISED MEDIAN' 'OTHER FIXED OBJECT'
 'INVOLVING OTHER OBJECT' 'UNKNOWN' 'CONCRETE BARRIER' 'BRIDGE RAIL'
 'TREE/SHRUBBERY' 'SIDESWIPE (SAME DIRECTION)' 'EMBANKMENT CUT/FILL SLOPE'
 'CULVERT/HEADWALL' 'SIDESWIPE (OPPOSITE DIRECTION)' 'SIGN' 'MAILBOX'
 'DELINEATOR POST' 'TRAFFIC SIGNAL POLE' 'VEHICLE CARGO/DEBRIS'
 'LARGE BOULDERS OR ROCKS' 'WALL/BUILDING' 'DOMESTIC ANIMAL'
 'CRASH CUSHION' 'CABLE RAIL' 'OTHER NON-COLLISION'
 'ROAD MAINTENANCE EQUIPMENT' 'RAILWAY VEHICLE'
 'BARRICADE/TRAFFIC BARRIER' 'WILD ANIMAL' 'BICYCLE']
New format Second HE ['Parked Motor Vehicle' 'Side to Side-Opposite Direction' nan
 'Other Non-Fixed Object (Describe in Narrative)' 'Curb'
 'Light Pole/Utility Pole' 'Pedestrian' 'Overturning/Rollover'
 'Front to Rear' 'Front to Side' 'Bridge Structure (Not Overhead)' 'Sign'
 'Concrete Highway Barrier' 'Embankment' 'Ditch' 'Tree'
 'Culvert or Headwall' 'Large Rocks or Boulder' 'Front to Front' 'Fence'
 'Electical/Utility Box' 'Guardrail Face' 'Ground' 'Guardrail End'
 'Side to Side-Same Direction' 'Traffic Signal Pole' 'Wall or Building'
 'Other Non-Collision' 'Other Fixed Object (Describe in Narrative)'
 'Mailbox' 'Delineator/Milepost' 'Rear to Rear' 'Barricade' 'Rear to Side'
 'Vehicle Debris or Cargo' 'Wild Animal' 'Immersion, Full or Partial'
 'Cable Rail' 'Crash Cushion/Traffic Barrel' 'Railroad Crossing Equipment'
 'Fell from Motor Vehicle' 'Bicycle/Motorized Bicycle'
 'School Age To/From School' 'Domestic Animal'
 'Overhead Structure (Not Bridge)' 'Overhead Structure (Bridge)']
Old converted format Second HE [nan 'Light Pole/Utility Pole' 'Parked Motor Vehicle'
 'Overturning/Rollover' 'Fence' 'Guardrail unspecified' 'Pedestrian'
 'Curb' 'Other Fixed Object (Describe in Narrative)'
 'Other Non-Fixed Object (Describe in Narrative)'
 'Concrete Highway Barrier' 'Bridge Structure (Not Overhead)' 'Tree'
 'Side to Side-Same Direction' 'Embankment' 'Culvert or Headwall'
 'Side to Side-Opposite Direction' 'Sign' 'Mailbox' 'Delineator/Milepost'
 'Traffic Signal Pole' 'Vehicle Debris or Cargo' 'Large Rocks or Boulder'
 'Wall or Building' 'Domestic Animal' 'Crash Cushion/Traffic Barrel'
 'Cable Rail' 'Other Non-Collision' 'old__road_maintenance_equipment'
 'old__railway_vehicle' 'Barricade' 'Wild Animal'
 'Bicycle/Motorized Bicycle']

In [29]:
# Convert EVENT_3 (old column) to Third HE (new column)
old_column = 'EVENT_3'
new_column = 'Third HE'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_harmful_event_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format EVENT_3 [nan 'FENCE' 'UNKNOWN' 'SIDESWIPE (OPPOSITE DIRECTION)'
 'LIGHT/UTILITY POLE' 'SIGN' 'GUARD RAIL' 'SIDESWIPE (SAME DIRECTION)'
 'EMBANKMENT CUT/FILL SLOPE' 'OVERTURNING' 'PARKED MOTOR VEHICLE'
 'CONCRETE BARRIER' 'TREE/SHRUBBERY' 'TRAFFIC SIGNAL POLE'
 'INVOLVING OTHER OBJECT' 'OTHER FIXED OBJECT' 'CABLE RAIL'
 'WALL/BUILDING' 'RAILWAY VEHICLE' 'CURB/RAISED MEDIAN'
 'VEHICLE CARGO/DEBRIS' 'CULVERT/HEADWALL' 'LARGE BOULDERS OR ROCKS'
 'PEDESTRIAN' 'DELINEATOR POST' 'OTHER NON-COLLISION' 'MAILBOX'
 'BRIDGE RAIL']
New format Third HE [nan 'Ground' 'Other Fixed Object (Describe in Narrative)'
 'Other Non-Fixed Object (Describe in Narrative)' 'Wall or Building'
 'Light Pole/Utility Pole' 'Vehicle Debris or Cargo' 'Other Non-Collision'
 'Overturning/Rollover' 'Ditch' 'Tree' 'Front to Side' 'Guardrail End'
 'Front to Rear' 'Large Rocks or Boulder' 'Side to Side-Same Direction'
 'Sign' 'Concrete Highway Barrier' 'Parked Motor Vehicle' 'Fence'
 'Traffic Signal Pole' 'Guardrail Face' 'Curb' 'Culvert or Headwall'
 'Rear to Side' 'Embankment' 'Immersion, Full or Partial'
 'Side to Side-Opposite Direction' 'Delineator/Milepost' 'Front to Front'
 'Pedestrian' 'Cable Rail' 'Electical/Utility Box' 'Mailbox'
 'Fell from Motor Vehicle' 'Barricade' 'Domestic Animal' 'Wild Animal'
 'Overhead Structure (Bridge)' 'Rear to Rear'
 'Bridge Structure (Not Overhead)' 'School Age To/From School'
 'Crash Cushion/Traffic Barrel' 'Railroad Crossing Equipment'
 'Bicycle/Motorized Bicycle']
Old converted format Third HE [nan 'Fence' 'Side to Side-Opposite Direction' 'Light Pole/Utility Pole'
 'Sign' 'Guardrail unspecified' 'Side to Side-Same Direction' 'Embankment'
 'Overturning/Rollover' 'Parked Motor Vehicle' 'Concrete Highway Barrier'
 'Tree' 'Traffic Signal Pole'
 'Other Non-Fixed Object (Describe in Narrative)'
 'Other Fixed Object (Describe in Narrative)' 'Cable Rail'
 'Wall or Building' 'old__railway_vehicle' 'Curb'
 'Vehicle Debris or Cargo' 'Culvert or Headwall' 'Large Rocks or Boulder'
 'Pedestrian' 'Delineator/Milepost' 'Other Non-Collision' 'Mailbox'
 'Bridge Structure (Not Overhead)']

In [30]:
# Convert MHE (old column) to MHE (new column)
old_column = 'MHE'
new_column = 'MHE'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_harmful_event_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format MHE ['HEAD-ON' 'GUARD RAIL' 'PARKED MOTOR VEHICLE' 'REAR-END' 'BROADSIDE'
 'WILD ANIMAL' 'OVERTURNING' 'LIGHT/UTILITY POLE'
 'SIDESWIPE (SAME DIRECTION)' 'CONCRETE BARRIER' 'PEDESTRIAN'
 'INVOLVING OTHER OBJECT' 'SIGN' 'TREE/SHRUBBERY' 'APPROACH TURN'
 'EMBANKMENT CUT/FILL SLOPE' 'FENCE' 'UNKNOWN' 'OTHER FIXED OBJECT'
 'DELINEATOR POST' 'BRIDGE RAIL' 'SIDESWIPE (OPPOSITE DIRECTION)'
 'MAILBOX' 'OVERTAKING TURN' 'CULVERT/HEADWALL' nan
 'LARGE BOULDERS OR ROCKS' 'CURB/RAISED MEDIAN' 'OTHER NON-COLLISION'
 'VEHICLE CARGO/DEBRIS' 'BICYCLE' 'ROAD MAINTENANCE EQUIPMENT'
 'DOMESTIC ANIMAL' 'CABLE RAIL' 'WALL/BUILDING'
 'BARRICADE/TRAFFIC BARRIER' 'TRAFFIC SIGNAL POLE' 'CRASH CUSHION'
 'RAILWAY VEHICLE']
New format MHE ['Parked Motor Vehicle' 'Front to Side' 'Overturning/Rollover'
 'Pedestrian' 'Wall or Building' 'Concrete Highway Barrier'
 'Guardrail End' 'Front to Front' 'Front to Rear'
 'Side to Side-Same Direction' 'Tree' 'Large Rocks or Boulder'
 'Wild Animal' 'Cable Rail' 'Side to Side-Opposite Direction'
 'Light Pole/Utility Pole' 'Guardrail Face' 'Embankment' 'Ditch'
 'Delineator/Milepost' 'Barricade' 'Sign' 'Culvert or Headwall' 'Curb'
 'Bicycle/Motorized Bicycle' 'Rear to Side' 'Fence'
 'Other Fixed Object (Describe in Narrative)' 'Electical/Utility Box'
 'Other Non-Fixed Object (Describe in Narrative)'
 'Railroad Crossing Equipment' 'Vehicle Debris or Cargo' 'Ground'
 'Traffic Signal Pole' 'Other Non-Collision'
 'Bridge Structure (Not Overhead)' 'Overhead Structure (Bridge)' 'Mailbox'
 'Domestic Animal' 'Crash Cushion/Traffic Barrel' 'Rear to Rear'
 'Immersion, Full or Partial' 'Fell from Motor Vehicle'
 'Overhead Structure (Not Bridge)' 'School Age To/From School']
Old converted format MHE ['Front to Front' 'Guardrail unspecified' 'Parked Motor Vehicle'
 'Front to Rear' 'old__broadside' 'Wild Animal' 'Overturning/Rollover'
 'Light Pole/Utility Pole' 'Side to Side-Same Direction'
 'Concrete Highway Barrier' 'Pedestrian'
 'Other Non-Fixed Object (Describe in Narrative)' 'Sign' 'Tree' nan
 'Embankment' 'Fence' 'Other Fixed Object (Describe in Narrative)'
 'Delineator/Milepost' 'Bridge Structure (Not Overhead)'
 'Side to Side-Opposite Direction' 'Mailbox' 'Culvert or Headwall'
 'Large Rocks or Boulder' 'Curb' 'Other Non-Collision'
 'Vehicle Debris or Cargo' 'Bicycle/Motorized Bicycle'
 'old__road_maintenance_equipment' 'Domestic Animal' 'Cable Rail'
 'Wall or Building' 'Barricade' 'Traffic Signal Pole'
 'Crash Cushion/Traffic Barrel' 'old__railway_vehicle']

### Convert Crash Type

In [31]:
# Convert ACCTYPE (old column) to Crash Type (new column)
old_column = 'ACCTYPE'
new_column = 'Crash Type'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

map_accident_type_old_to_new = {
    'HEAD-ON': 'Head-On',
    'GUARD RAIL': 'Guardrail Unspecified',
    'PARKED MOTOR VEHICLE': 'Parked Motor Vehicle',
    'REAR-END': 'Rear-End', 
    'BROADSIDE': 'Broadside',
    'WILD ANIMAL': 'Wild Animal', 
    'OVERTURNING': 'Overturning/Rollover',
    'LIGHT/UTILITY POLE': 'Light Pole/Utility Pole',
    'SIDESWIPE (SAME DIRECTION)': 'Sideswipe Same Direction',
    'CONCRETE BARRIER': 'Concrete Highway Barrier',
    'PEDESTRIAN': 'Pedestrian',
    'SIGN': 'Sign',
    'TREE/SHRUBBERY': 'Tree',
    'APPROACH TURN': 'Approach Turn', 
    'EMBANKMENT CUT/FILL SLOPE': 'Embankment',
    'MAILBOX': 'Mailbox', 
    'FENCE': 'Fence', 
    'CURB/RAISED MEDIAN': 'Curb',
    'DELINEATOR POST': 'Delineator/Milepost', 
    'OTHER FIXED OBJECT': 'Other Fixed Object (Describe in Narrative)', 
    'BRIDGE RAIL': 'Bridge Structure (Not Overhead)', 
    'SIDESWIPE (OPPOSITE DIRECTION)': 'Sideswipe Opposite Direction', 
    'INVOLVING OTHER OBJECT': 'Other Non-Fixed Object Describe in Narrative)', 
    'OVERTAKING TURN': 'Overtaking Turn', 
    'CULVERT/HEADWALL': 'Culvert or Headwall',
    'LARGE BOULDERS OR ROCKS': 'Large Rocks or Boulder',
    'OTHER NON-COLLISION': 'Other Non-Collision', 
    'VEHICLE CARGO/DEBRIS': 'Vehicle Debris or Cargo', 
    'BICYCLE': 'Bicycle/Motorized Bicycle', 
    'ROAD MAINTENANCE EQUIPMENT': 'old__road_maintenance_equipment', 
    'DOMESTIC ANIMAL': 'Domestic Animal', 
    'CABLE RAIL': 'Cable Rail', 
    'WALL/BUILDING': 'Wall or Building', 
    'BARRICADE/TRAFFIC BARRIER': 'Barricade', 
    'TRAFFIC SIGNAL POLE': 'Traffic Signal Pole', 
    'CRASH CUSHION': 'Crash Cushion/Traffic Barrel', 
    'RAILWAY VEHICLE': 'old__railway_vehicle',
    'UNKNOWN': np.nan,
}

                
cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_accident_type_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format ACCTYPE ['HEAD-ON' 'GUARD RAIL' 'PARKED MOTOR VEHICLE' 'REAR-END' 'BROADSIDE'
 'WILD ANIMAL' 'OVERTURNING' 'LIGHT/UTILITY POLE'
 'SIDESWIPE (SAME DIRECTION)' 'CONCRETE BARRIER' 'PEDESTRIAN' 'SIGN'
 'TREE/SHRUBBERY' 'APPROACH TURN' 'EMBANKMENT CUT/FILL SLOPE' 'MAILBOX'
 'FENCE' 'CURB/RAISED MEDIAN' 'DELINEATOR POST' 'OTHER FIXED OBJECT'
 'BRIDGE RAIL' 'SIDESWIPE (OPPOSITE DIRECTION)' 'INVOLVING OTHER OBJECT'
 'OVERTAKING TURN' 'CULVERT/HEADWALL' 'LARGE BOULDERS OR ROCKS'
 'OTHER NON-COLLISION' 'VEHICLE CARGO/DEBRIS' nan 'BICYCLE'
 'ROAD MAINTENANCE EQUIPMENT' 'DOMESTIC ANIMAL' 'CABLE RAIL'
 'WALL/BUILDING' 'BARRICADE/TRAFFIC BARRIER' 'TRAFFIC SIGNAL POLE'
 'CRASH CUSHION' 'UNKNOWN' 'RAILWAY VEHICLE']
New format Crash Type ['Parked Motor Vehicle' 'Broadside' 'Overturning/Rollover' 'Pedestrian'
 'Wall or Building' 'Concrete Highway Barrier' 'Guardrail End' 'Head-On'
 'Rear-End' 'Sideswipe Same Direction' 'Tree' 'Large Rocks or Boulder'
 'Wild Animal' 'Cable Rail' 'Sideswipe Opposite Direction' 'Sign'
 'Guardrail Face' 'Light Pole/Utility Pole' 'Delineator/Milepost'
 'Barricade' 'Embankment' 'Curb' 'Bicycle/Motorized Bicycle' 'Fence'
 'Overtaking Turn' 'Approach Turn'
 'Other Non-Fixed Object Describe in Narrative)'
 'Other Fixed Object (Describe in Narrative)' 'Ditch'
 'Railroad Crossing Equipment' 'Vehicle Debris or Cargo' 'Ground'
 'Traffic Signal Pole' 'Other Non-Collision'
 'Bridge Structure (Not Overhead)' 'Electrical/Utility Box'
 'Culvert or Headwall' 'Mailbox' 'Overhead Structure (Bridge)'
 'Domestic Animal' 'Crash Cushion/Traffic Barrel'
 'Immersion, Full or Partial' 'Fell from Motor Vehicle'
 'Overhead Structure (Not Bridge)' 'School Age To/From School']
Old converted format Crash Type ['Head-On' 'Guardrail Unspecified' 'Parked Motor Vehicle' 'Rear-End'
 'Broadside' 'Wild Animal' 'Overturning/Rollover'
 'Light Pole/Utility Pole' 'Sideswipe Same Direction'
 'Concrete Highway Barrier' 'Pedestrian' 'Sign' 'Tree' 'Approach Turn'
 'Embankment' 'Mailbox' 'Fence' 'Curb' 'Delineator/Milepost'
 'Other Fixed Object (Describe in Narrative)'
 'Bridge Structure (Not Overhead)' 'Sideswipe Opposite Direction'
 'Other Non-Fixed Object Describe in Narrative)' 'Overtaking Turn'
 'Culvert or Headwall' 'Large Rocks or Boulder' 'Other Non-Collision'
 'Vehicle Debris or Cargo' nan 'Bicycle/Motorized Bicycle'
 'old__road_maintenance_equipment' 'Domestic Animal' 'Cable Rail'
 'Wall or Building' 'Barricade' 'Traffic Signal Pole'
 'Crash Cushion/Traffic Barrel' 'old__railway_vehicle']

### Approach Overtaking Turn

In [43]:
new_column = 'Approach Overtaking Turn'
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

# approach and overtaking turn info is in Accident Type
display(cdot_old_pdf.loc[cdot_old_pdf['ACCTYPE'].isin(['OVERTAKING TURN', 'APPROACH TURN'])])

cdot_old_converted_pdf[new_column] = cdot_old_converted_pdf['Crash Type'] 
cdot_old_converted_pdf.loc[~cdot_old_converted_pdf[new_column].isin(['Approach Turn', 'Overtaking Turn'])] = 'Not Applicable'

print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

New format Approach Overtaking Turn ['Not Applicable' 'Overtaking Turn' 'Approach Turn']

,SYSTEM,RTE,SEC,MP,DATE,TIME,SEVERITY,INJURY 00,INJURY 01,INJURY 02,...,Crash Time,Location,Road Description,First HE,Second HE,Third HE,Crash Type,Number Killed,Total Vehicles,Approach Overtaking Turn
34,CITY STREET,0,NaN,0.0,2007-01-01 00:00:00,230.0,PDO,3,0,0,...,23:00:00,On Roadway,At Intersection,NaN,NaN,NaN,Approach Turn,0,2.0,Approach Turn
94,STATE HIGHWAY,13,B,96.6,2007-01-01 00:00:00,1130.0,PDO,5,0,0,...,11:30:00,On Roadway,Non-Intersection,NaN,NaN,NaN,Overtaking Turn,0,2.0,Overtaking Turn
119,STATE HIGHWAY,83,A,71.74,2007-01-01 00:00:00,1345.0,PDO,8,0,0,...,13:45:00,On Roadway,Driveway Access Related,NaN,NaN,NaN,Approach Turn,0,2.0,Approach Turn
120,STATE HIGHWAY,30,A,10.26,2007-01-01 00:00:00,1352.0,INJ,1,0,1,...,13:52:00,On Roadway,At Intersection,NaN,NaN,NaN,Approach Turn,0,2.0,Approach Turn
151,COUNTY ROAD,0,NaN,0.0,2007-01-01 00:00:00,1725.0,INJ,2,2,0,...,17:25:00,On Roadway,At Intersection,NaN,NaN,NaN,Overtaking Turn,0,2.0,Overtaking Turn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112107,STATE HIGHWAY,30,A,3.6,2007-12-31 00:00:00,1700.0,INJ,1,1,0,...,17:00:00,On Roadway,At Intersection,NaN,NaN,NaN,Approach Turn,0,2.0,Approach Turn
112148,CITY STREET,0,NaN,0.0,2007-12-31 00:00:00,1931.0,PDO,3,0,0,...,19:31:00,On Roadway,Driveway Access Related,NaN,NaN,NaN,Overtaking Turn,0,2.0,Overtaking Turn
112163,CITY STREET,0,NaN,0.0,2007-12-31 00:00:00,2056.0,PDO,2,0,0,...,20:56:00,On Roadway,At Intersection,Side to Side-Same Direction,NaN,NaN,Overtaking Turn,0,2.0,Overtaking Turn
112182,INTERSTATE,70,A,264.34,2007-12-31 00:00:00,2302.0,PDO,7,0,0,...,23:02:00,On Roadway,At Intersection,NaN,NaN,NaN,Approach Turn,0,2.0,Approach Turn
112187,CITY STREET,0,NaN,0.0,2007-12-31 00:00:00,2343.0,PDO,2,0,0,...,23:43:00,On Roadway,Intersection Related,Side to Side-Same Direction,NaN,NaN,Overtaking Turn,0,2.0,Overtaking Turn

Old converted format Approach Overtaking Turn ['Not Applicable' 'Approach Turn' 'Overtaking Turn']

### Convert Number Injured

In [52]:
# Convert Combine a few columns (INJURY 02, INJURY 03) (old column) to Number Injured (new column)

# INSPECT INJURY 00, 01, 02, 03, 04
# Inspect how columns in new format are combined to get the "number injured" value. Then apply that to the old data format
cdot_new_pdf['sum injury 123'] = cdot_new_pdf['Injury 01'] + cdot_new_pdf['Injury 02'] + cdot_new_pdf['Injury 03']
display(cdot_new_pdf[['Injury 00', 'Injury 01', 'Injury 02', 'Injury 03', 'Injury 04', 'Number Injured', 'sum injury 123']])
print(cdot_new_pdf.shape[0]) 
print((cdot_new_pdf['sum injury 123'] == cdot_new_pdf['Number Injured']).sum())

new_column = 'Number Injured'
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

cdot_old_converted_pdf[new_column] = cdot_old_pdf['INJURY 01'] + cdot_old_pdf['INJURY 02'] + cdot_old_pdf['INJURY 03']
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

,Injury 00,Injury 01,Injury 02,Injury 03,Injury 04,Number Injured,sum injury 123
0,0,0,0,0,0,0,0
1,2,0,1,0,0,1,1
2,0,1,0,0,0,1,1
3,1,0,0,0,0,0,0
4,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...
102161,0,0,1,0,0,1,1
102162,2,0,0,0,0,0,0
102163,0,1,0,1,0,2,2
102164,1,0,0,0,0,0,0
102165,2,0,0,0,0,0,0

102166
102166
New format Number Injured [ 0  1  2  3  7  4  5  8  6 10  9]
Old converted format Number Injured ['Not ApplicableNot ApplicableNot Applicable' 0 1 2 3 4 6 5 7]

### Convert Secondary Crash

In [35]:
# Convert VEHICLES (old column) to Total Vehicles (new column)
# Rename Column + cast to float
old_column = 'VEHICLES'
new_column = 'Total Vehicles'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].astype(float)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format VEHICLES [ 2  1  3  5  6  4  0 20  9  7 96 22 44 83  8 13 23 25 16 29 10 37 11 93
 52 92]
New format Total Vehicles [ 3.  1.  2.  4.  6.  5.  0.  8.  7. 10.  9. 22. nan]
Old converted format Total Vehicles [ 2.  1.  3.  5.  6.  4.  0. 20.  9.  7. 96. 22. 44. 83.  8. 13. 23. 25.
 16. 29. 10. 37. 11. 93. 52. 92.]

In [58]:
# Convert None (old column) to Secondary Crash (new column)
# Is this true if the number of vehicles is greater than 2??? - NOPE - SET TO NULL

new_column = 'Secondary Crash'
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

cdot_new_pdf['total vehicle gr 1'] = (cdot_new_pdf['Total Vehicles'] > 0).astype(float)

display(cdot_new_pdf[['Total Vehicles', 'Secondary Crash', 'total vehicle gr 1']])

print(cdot_new_pdf.shape[0]) 
print((cdot_new_pdf['Secondary Crash'] == cdot_new_pdf['total vehicle gr 1']).sum())

#cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].astype(float)
#print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

New format Secondary Crash [ 1.  0. nan]

        Total Vehicles  Secondary Crash  total vehicle gr 1
0                  3.0              1.0                 1.0
1                  3.0              1.0                 1.0
2                  1.0              0.0                 1.0
3                  3.0              0.0                 1.0
4                  2.0              0.0                 1.0
...                ...              ...                 ...
102161             2.0              0.0                 1.0
102162             2.0              0.0                 1.0
102163             2.0              0.0                 1.0
102164             2.0              0.0                 1.0
102165             2.0              0.0                 1.0

[102166 rows x 3 columns]

102166
1645

### Convert Contour Information

In [63]:
# Convert COUNTOUR (old column) to Road Contour Curves (new column)
old_column = 'CONTOUR'
new_column = 'Road Contour Curves'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

map_road_contour_curves_old_to_new = {
    'Not Applicable': np.nan,
    'STRAIGHT ON-LEVEL': 'Straight',
    'CURVE ON-GRADE': 'Curve Unknown Direction', 
    'STRAIGHT ON-GRADE': 'Straight',
    'CURVE ON-LEVEL': 'Curve Unknown Direction',
    'HILLCREST': 'Unknown',
    'UNKNOWN': 'Unknown',
}
                
cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_road_contour_curves_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format CONTOUR ['Not Applicable' 'STRAIGHT ON-LEVEL' 'CURVE ON-GRADE' 'STRAIGHT ON-GRADE'
 'CURVE ON-LEVEL' 'UNKNOWN' 'HILLCREST']
New format Road Contour Curves ['Straight' 'Curve Left' 'Curve Right' nan 'Unknown']
Old converted format Road Contour Curves [nan 'Straight' 'Curve Unknown Direction' 'Unknown']

In [66]:
# Convert COUNTOUR (old column) to Road Contour Grade (new column)
old_column = 'CONTOUR'
new_column = 'Road Contour Grade'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

map_road_contour_grade_old_to_new = {
    'Not Applicable': np.nan,
    'STRAIGHT ON-LEVEL': 'Level',
    'CURVE ON-GRADE': 'Unknown', 
    'STRAIGHT ON-GRADE': 'Unknown',
    'CURVE ON-LEVEL': 'Level',
    'HILLCREST': 'Hill Crest',
    'UNKNOWN': 'Unknown',
}
                
cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_road_contour_grade_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format CONTOUR ['Not Applicable' 'STRAIGHT ON-LEVEL' 'CURVE ON-GRADE' 'STRAIGHT ON-GRADE'
 'CURVE ON-LEVEL' 'UNKNOWN' 'HILLCREST']
New format Road Contour Grade ['Level' 'Downhill' nan 'Uphill' 'Hill Crest' 'Unknown' 'Sag/Bottom']
Old converted format Road Contour Grade [nan 'Level' 'Unknown' 'Hill Crest']

### Convert Road Condition

In [68]:
# Convert CONDITION (old column) to Road Condition (new column)
# TODO - CONVERT EQUIVALENT WORDS
old_column = 'CONDITION'
new_column = 'Road Condition'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

map_road_condition_old_to_new = {
    'Not Applicable': np.nan, 
    'ICY': 'Icy', 
    'DRY': 'Dry', 
    'SLUSHY': 'Slushy', 
    'WET W/VIS ICY ROAD TREATMENT': 'Wet W/Visible Icy Road Treatment', 
    'DRY W/VIS ICY ROAD TREATMENT': 'Dry W/Visible Icy Road Treatment',
    'WET': 'Wet', 
    'ICY W/VIS ICY ROAD TREATMENT': 'Icy W/Visible Icy Road Treatment', 
    'SNOWY': 'Snowy', 
    'UNKNOWN': np.nan, 
    'SNOWY W/VIS ICY ROAD TREATMENT': 'Snowy W/Visible Icy Road Treatment', 
    'SLUSHY W/VIS ICY ROAD TREATMENT': 'Slushy W/Visible Icy Road Treatment', 
    'FOREIGN MATERIAL': 'Foreign Material', 
    'MUDDY': 'Muddy'
}
                
cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_road_condition_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format CONDITION ['Not Applicable' 'ICY' 'DRY' 'SLUSHY' 'WET W/VIS ICY ROAD TREATMENT'
 'DRY W/VIS ICY ROAD TREATMENT' 'WET' 'ICY W/VIS ICY ROAD TREATMENT'
 'SNOWY' 'UNKNOWN' 'SNOWY W/VIS ICY ROAD TREATMENT'
 'SLUSHY W/VIS ICY ROAD TREATMENT' 'FOREIGN MATERIAL' 'MUDDY']
New format Road Condition ['Icy' 'Dry' 'Wet' 'Icy W/Visible Icy Road Treatment' 'Slushy'
 'Slushy W/Visible Icy Road Treatment' 'Snowy' nan
 'Dry W/Visible Icy Road Treatment' 'Snowy W/Visible Icy Road Treatment'
 'Wet W/Visible Icy Road Treatment' 'Muddy' 'Foreign Material'
 'Sand/Gravel' 'Roto-Milled']
Old converted format Road Condition [nan 'Icy' 'Dry' 'Slushy' 'Wet W/Visible Icy Road Treatment'
 'Dry W/Visible Icy Road Treatment' 'Wet'
 'Icy W/Visible Icy Road Treatment' 'Snowy'
 'Snowy W/Visible Icy Road Treatment'
 'Slushy W/Visible Icy Road Treatment' 'Foreign Material' 'Muddy']

### Convert Lighting Conditions

In [70]:
# Convert LIGHTING (old column) to Lighting Condition (new column)
old_column = 'LIGHTING'
new_column = 'Lighting Conditions'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

map_lighting_conditions_old_to_new = {
    'Not Applicable': np.nan, 
    'DARK-LIGHTED': 'Dark â€“ Lighted', 
    'DAYLIGHT': 'Daylight', 
    'DAWN OR DUSK': 'Dawn or Dusk', 
    'DARK-UNLIGHTED': 'Dark â€“ Unlighted', 
    'UNKNOWN': np.nan,
}
                
cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_lighting_conditions_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format LIGHTING ['Not Applicable' 'DARK-LIGHTED' 'DAYLIGHT' 'DAWN OR DUSK'
 'DARK-UNLIGHTED' 'UNKNOWN']
New format Lighting Conditions ['Dark â€“ Lighted' 'Dark â€“ Unlighted' 'Daylight' 'Dawn or Dusk' nan]
Old converted format Lighting Conditions [nan 'Dark â€“ Lighted' 'Daylight' 'Dawn or Dusk' 'Dark â€“ Unlighted']

### Convert Weather Conditions

In [72]:
# Convert WEATHER (old column) to Weather Condition (new column)
old_column = 'WEATHER'
new_column = 'Weather Condition'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())



map_weather_conditions_old_to_new = {
    'Not Applicable': np.nan, 
    'NONE': 'None', 
    'RAIN': 'Rain', 
    'SNOW/SLEET/HAIL': 'old__snow_sleet_hail',
    'WIND': 'Wind', 
    'FOG': 'Fog', 
    'DUST': 'Dust',
    'UNKNOWN': np.nan, 
}
                
cdot_old_converted_pdf[new_column] = cdot_old_pdf[old_column].map(map_weather_conditions_old_to_new)
print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format WEATHER ['Not Applicable' 'NONE' 'RAIN' 'SNOW/SLEET/HAIL' 'WIND' 'FOG' 'DUST'
 'UNKNOWN']
New format Weather Condition ['Snow' 'Clear' 'Cloudy' 'Sleet or Hail' nan 'Wind' 'Rain' 'Fog'
 'Blowing Snow' 'Freezing Rain or Freezing Drizzle' 'Dust']
Old converted format Weather Condition [nan 'None' 'Rain' 'old__snow_sleet_hail' 'Wind' 'Fog' 'Dust']

In [73]:
# Convert No Column (old column) to Weather Condition (new column)
# Create empty column
old_column = ''
new_column = 'Weather Condition 2'

#print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

#cdot_old_converted_pdf[new_column] = None
#print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

New format Weather Condition 2 [nan 'Clear' 'Sleet or Hail' 'Wind' 'Cloudy' 'Fog' 'Rain' 'Snow'
 'Freezing Rain or Freezing Drizzle' 'Blowing Snow' 'Dust']