## People Centered COS - Convert CDOT Data format (2007-2020) to the 2021+ data format 

 #### Part 1 - (THIS NOTEBOOK) convert information on road condition, lighting, location, number of vehicles and people etc. 

 #### Part 2 - in another notebook - will handle the mapping from vechile and non-motorist attributes and speeds etc.

In [1]:
pip install pandas

Requirement already satisfied: pandas in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

### Load CDOT csvs

In [4]:
cdot_base_path = "/Users/haley.northrup/Desktop/PeopleCenteredCOS/cdot_data/"

In [5]:
# Load CDOT Data from new data format (2021+) 

year_new = 2023
filename_new = f"CDOTRM_CD_Crash_Listing_-_{year_new}.xlsx"

full_path_new = cdot_base_path + filename_new
print(full_path_new)

cdot_new_pdf = pd.read_excel(full_path_new)
display(cdot_new_pdf.head(5))

/Users/haley.northrup/Desktop/PeopleCenteredCOS/cdot_data/CDOTRM_CD_Crash_Listing_-_2023.xlsx

,CUID,System Code,Rd_Number,Rd_Section,City_Street,Crash Date,Crash Time,Agency Id,City,County,...,TU-2 NM Safety Helmet,TU-1 NM Alcohol Suspected,TU-2 NM Alcohol Suspected,TU-1 NM Marijuana Suspected,TU-2 NM Marijuana Suspected,TU-1 NM Other Drugs Suspected,TU-2 NM Other Drugs Suspected,Record Status,Processing Status,Last Updated
0,296027,City Street,0455,VERMO,TIMBE,2023-01-01,00:00:00,FTCPD,FORT COLLINS,LARIMER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Aug 4 2023 11:35PM
1,299624,City Street,0455,HARMO,TIMBE,2023-01-01,00:03:00,FTCPD,FORT COLLINS,LARIMER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Apr 6 2023 10:08PM
2,289075,City Street,0320,KALAM,CEDAR,2023-01-01,00:09:00,DPD,DENVER,DENVER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Feb 8 2023 8:29PM
3,293978,City Street,0055,LINVA,LARED,2023-01-01,00:16:00,AURPD,AURORA,ARAPAHOE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,May 5 2023 8:02PM
4,299717,State Highway,095A,12.906,NaN,2023-01-01,00:34:00,WMPD,WESTMINSTER,JEFFERSON,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Feb 15 2023 1:35PM

In [6]:
# Load CDOT Data from old data format (2007-2020) 

year = 2007
filename_old = f"CDOTRM_CD_Crash_Listing_-_{year}.xlsx"

full_path_old = cdot_base_path + filename_old
print(full_path_old)

cdot_old_pdf = pd.read_excel(full_path_old)
display(cdot_old_pdf.head(5))

/Users/haley.northrup/Desktop/PeopleCenteredCOS/cdot_data/CDOTRM_CD_Crash_Listing_-_2007.xlsx

,SYSTEM,RTE,SEC,MP,DATE,TIME,SEVERITY,INJURY 00,INJURY 01,INJURY 02,...,DRVINJ_1,DRVINJ_2,DRVINJ_3,DUI_1,DUI_2,DUI_3,CITY,COUNTY,LATITUDE,LONGITUDE
0,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,2,0,0,...,NO INJURY,NO INJURY,NaN,N,N,N,FORT COLLINS,LARIMER,40.55955,-105.045929
1,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,1,0,0,...,NO INJURY,NaN,NaN,N,N,N,PARKER,DOUGLAS,39.51831,-104.774870
2,CITY STREET,0,NaN,0.0,2007-01-01,0.0,PDO,1,0,0,...,NaN,NO INJURY,NaN,N,N,N,DENVER,DENVER,39.66372,-105.075380
3,INTERSTATE,70,A,387.3,2007-01-01,2.0,PDO,7,0,0,...,NO INJURY,NO INJURY,NaN,N,N,N,NaN,LINCOLN,39.28565,-103.196810
4,CITY STREET,0,NaN,0.0,2007-01-01,10.0,PDO,4,0,0,...,NO INJURY,NO INJURY,NaN,N,N,N,AURORA,ARAPAHOE,39.65800,-104.777000

### Inspect Data

In [7]:
print(cdot_new_pdf.info(verbose=True, show_counts=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102166 entries, 0 to 102165
Data columns (total 110 columns):
 #    Column                              Non-Null Count   Dtype
---   ------                              --------------   -----
 0    CUID                                102166 non-null  int64
 1    System Code                         102166 non-null  object
 2    Rd_Number                           102166 non-null  object
 3    Rd_Section                          102015 non-null  object
 4    City_Street                         56097 non-null   object
 5    Crash Date                          102166 non-null  datetime64[ns]
 6    Crash Time                          101951 non-null  object
 7    Agency Id                           102120 non-null  object
 8    City                                72982 non-null   object
 9    County                              102166 non-null  object
 10   Latitude                            94184 non-null   float64
 11   Longitude                           94184 non-null   float64
 12   Location 1                          102166 non-null  object
 13   Link                                102166 non-null  object
 14   Location 2                          102151 non-null  object
 15   Location                            102166 non-null  object
 16   Road Description                    102161 non-null  object
 17   First HE                            102166 non-null  object
 18   Second HE                           22404 non-null   object
 19   Third HE                            5825 non-null    object
 20   Fourth HE                           1649 non-null    object
 21   MHE                                 102166 non-null  object
 22   Crash Type                          102166 non-null  object
 23   Approach Overtaking Turn            102166 non-null  object
 24   Wild Animal                         3459 non-null    object
 25   Number Killed                       102166 non-null  int64
 26   Number Injured                      102166 non-null  int64
 27   Injury 00                           102166 non-null  int64
 28   Injury 01                           102166 non-null  int64
 29   Injury 02                           102166 non-null  int64
 30   Injury 03                           102166 non-null  int64
 31   Injury 04                           102166 non-null  int64
 32   Total Vehicles                      102165 non-null  float64
 33   Secondary Crash                     102165 non-null  float64
 34   Construction Zone                   102166 non-null  bool
 35   School Zone                         102165 non-null  float64
 36   Road Contour Curves                 93403 non-null   object
 37   Road Contour Grade                  93564 non-null   object
 38   Road Condition                      101568 non-null  object
 39   Lighting Conditions                 101519 non-null  object
 40   Weather Condition                   101130 non-null  object
 41   Weather Condition 2                 6478 non-null    object
 42   Lane Position                       90241 non-null   object
 43   TU-1 Direction                      101089 non-null  object
 44   TU-2 Direction                      78362 non-null   object
 45   TU-1 Movement                       101088 non-null  object
 46   TU-2 Movement                       78497 non-null   object
 47   TU-1 Type                           101079 non-null  object
 48   TU-2 Type                           78509 non-null   object
 49   TU-1 Special Function               91407 non-null   object
 50   TU-2 Special Function               74235 non-null   object
 51   TU-1 Autonomous Vehicle             93629 non-null   object
 52   TU-2 Autonomous Vehicle             75689 non-null   object
 53   TU-1 Hit And Run                    102166 non-null  bool
 54   TU-2 Hit And Run                    102166 non-null  bool
 55   TU-1 Speed Limit                    102166 non-null  int64
 56   TU-2 Speed Limit                    102166 non-null  int64
 57   TU-1 Estimated Speed                102166 non-null  int64
 58   TU-2 Estimated Speed                102166 non-null  int64
 59   TU-1 Speed                          102166 non-null  int64
 60   TU-2 Speed                          102166 non-null  int64
 61   TU-1 Driver Action                  93655 non-null   object
 62   TU-2 Driver Action                  73333 non-null   object
 63   TU-1 Human Contributing Factor      89065 non-null   object
 64   TU-2 Human Contributing Factor      72917 non-null   object
 65   TU-1 Age                            102166 non-null  int64
 66   TU-2 Age                            102166 non-null  int64
 67   TU-1 Sex                            89070 non-null   object
 68   TU-2 Sex                            71016 non-null   object
 69   TU-1 Safety System Available        78583 non-null   object
 70   TU-2 Safety System Available        61262 non-null   object
 71   TU-1 Safety restraint Use           80178 non-null   object
 72   TU-2 Safety restraint Use           61877 non-null   object
 73   TU-1 Safety Helmet                  81159 non-null   object
 74   TU-2  Safety Helmet                 62836 non-null   object
 75   TU-1 Alcohol Suspected              83757 non-null   object
 76   TU-2 Alcohol Suspected              66932 non-null   object
 77   TU-1  Marijuana Suspected           86871 non-null   object
 78   TU-2 Marijuana Suspected            67768 non-null   object
 79   TU-1 Other Drugs Suspected          81691 non-null   object
 80   TU-2 Other Drugs Suspected          65103 non-null   object
 81   TU-1 NM Direction                   1068 non-null    object
 82   TU-2 NM Direction                   1694 non-null    object
 83   TU-1 NM Movement                    1068 non-null    object
 84   TU-2 NM Movement                    1697 non-null    object
 85   TU-1 NM Facility Available          1693 non-null    object
 86   TU-2 NM Facility Available          1693 non-null    object
 87   TU-1 NM Location                    1068 non-null    object
 88   TU-2 NM Location                    1696 non-null    object
 89   TU-1 NM Type                        1068 non-null    object
 90   TU-2 NM Type                        1698 non-null    object
 91   TU-1 NM Age                         983 non-null     float64
 92   TU-2 NM Age                         1554 non-null    float64
 93   TU-1 NM Sex                         1067 non-null    object
 94   TU-2 NM Sex                         1692 non-null    object
 95   TU-1 NM Action                      1067 non-null    object
 96   TU-2 NM Action                      1690 non-null    object
 97   TU-1 NM Human Contributing Factor   996 non-null     object
 98   TU-2 NM Human Contributing Factor   1549 non-null    object
 99   TU-1 NM Safety Helmet               826 non-null     object
 100  TU-2 NM Safety Helmet               1328 non-null    object
 101  TU-1 NM Alcohol Suspected           943 non-null     object
 102  TU-2 NM Alcohol Suspected           1531 non-null    object
 103  TU-1 NM Marijuana Suspected         974 non-null     object
 104  TU-2 NM Marijuana Suspected         1560 non-null    object
 105  TU-1 NM Other Drugs Suspected       925 non-null     object
 106  TU-2 NM Other Drugs Suspected       1516 non-null    object
 107  Record Status                       102166 non-null  object
 108  Processing Status                   102166 non-null  object
 109  Last Updated                        102166 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(7), int64(16), object(83)
memory usage: 83.7+ MB
None

In [8]:
print(cdot_old_pdf.info(verbose=True, show_counts=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112191 entries, 0 to 112190
Data columns (total 84 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   SYSTEM      112191 non-null  object
 1   RTE         112191 non-null  int64
 2   SEC         51897 non-null   object
 3   MP          112191 non-null  float64
 4   DATE        112191 non-null  datetime64[ns]
 5   TIME        112139 non-null  float64
 6   SEVERITY    112191 non-null  object
 7   INJURY 00   112191 non-null  int64
 8   INJURY 01   112191 non-null  int64
 9   INJURY 02   112191 non-null  int64
 10  INJURY 03   112191 non-null  int64
 11  INJURY 04   112191 non-null  int64
 12  AGENCYNAME  112171 non-null  object
 13  LOCATION    112191 non-null  object
 14  ROAD_DESC   112191 non-null  object
 15  VEHICLES    112191 non-null  int64
 16  CONTOUR     112191 non-null  object
 17  CONDITION   112191 non-null  object
 18  LIGHTING    112191 non-null  object
 19  WEATHER     112191 non-null  object
 20  LIMIT1      112191 non-null  object
 21  LIMIT2      112191 non-null  object
 22  LIMIT3      112191 non-null  object
 23  RAMP        112191 non-null  object
 24  REGION      112191 non-null  int64
 25  RUCODE      112191 non-null  object
 26  EVENT_1     112161 non-null  object
 27  EVENT_2     18172 non-null   object
 28  EVENT_3     1031 non-null    object
 29  MHE         111999 non-null  object
 30  ACCTYPE     112142 non-null  object
 31  DIR_1       112191 non-null  object
 32  VEHICLE_1   112191 non-null  object
 33  DRIVER_1    112191 non-null  object
 34  FACTOR_1    112186 non-null  object
 35  SPEED_1     112191 non-null  object
 36  VEH_MOVE_1  112191 non-null  object
 37  AGE_1       112191 non-null  int64
 38  SEX_1       102911 non-null  object
 39  STATE_1     104007 non-null  object
 40  BELT_1      96022 non-null   object
 41  DIR_2       85547 non-null   object
 42  VEHICLE_2   85565 non-null   object
 43  DRIVER_2    112191 non-null  object
 44  FACTOR_2    112175 non-null  object
 45  SPEED_2     85501 non-null   object
 46  VEH_MOVE_2  85550 non-null   object
 47  AGE_2       112191 non-null  int64
 48  SEX_2       77154 non-null   object
 49  STATE_2     83377 non-null   object
 50  BELT_2      72184 non-null   object
 51  DIR_3       8893 non-null    object
 52  VEHICLE_3   8887 non-null    object
 53  DRIVER_3    112191 non-null  object
 54  FACTOR_3    112186 non-null  object
 55  SPEED_3     8884 non-null    object
 56  VEH_MOVE_3  8893 non-null    object
 57  AGE_3       112191 non-null  int64
 58  SEX_3       7631 non-null    object
 59  STATE_3     8479 non-null    object
 60  BELT_3      7369 non-null    object
 61  WAN_TYPE    3679 non-null    object
 62  LOC_01      112157 non-null  object
 63  LINK        111398 non-null  object
 64  LOC_02      110743 non-null  object
 65  HAZMAT_1    112191 non-null  object
 66  HAZMAT_2    112191 non-null  object
 67  HAZMAT_3    112191 non-null  object
 68  VIOLCODE_1  88107 non-null   object
 69  VIOLCODE_2  4569 non-null    object
 70  VIOLCODE_3  430 non-null     object
 71  CYCPROT_1   111844 non-null  object
 72  CYCPROT_2   84781 non-null   object
 73  CYCPROT_3   8486 non-null    object
 74  DRVINJ_1    104712 non-null  object
 75  DRVINJ_2    81598 non-null   object
 76  DRVINJ_3    8219 non-null    object
 77  DUI_1       112191 non-null  object
 78  DUI_2       112191 non-null  object
 79  DUI_3       112191 non-null  object
 80  CITY        83754 non-null   object
 81  COUNTY      112191 non-null  object
 82  LATITUDE    112191 non-null  float64
 83  LONGITUDE   112191 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(11), object(68)
memory usage: 71.9+ MB
None

## Convert Data

In [62]:
# VEHICLE_X to TU-1 Type and all the other columns associated that are not just empty 
# Anything marked TU-1 or TU-2, or NM and anything old marked XXX_1 FACTOR, DRIVER, DUI, CYCPROT, SEX, AGE, DIR etc. 

# Convert VEHICLE_1 (old column) to TU-1 Type (new column)
# TODO - CONVERT EQUIVALENT WORDS
# And segment the Non-motorists out of the old format and note which vehicle number is the non-motorist if any 
old_column = 'VEHICLE_1'
new_column = 'TU-1 Type'

print(f"Old format {old_column}", cdot_old_pdf[old_column].unique())
print(f"New format {new_column}", cdot_new_pdf[new_column].unique())

#cdot_old_converted_pdf[new_column] = None
#print(f"Old converted format {new_column}", cdot_old_converted_pdf[new_column].unique())

Old format VEHICLE_1 ['PASSENGER CAR/VAN' 'HIT & RUN - UNKNOWN' 'PICKUP TRUCK/UTILITY VAN'
 'SUV' 'OTHER - SEE REPORT' 'TRUCK GVW > 10K/BUSSES > 15 PEOPLE'
 'PICKUP TRUCK/UTILITY VAN W/TRAILER' 'NON-SCHOOL BUS < 15 PEOPLE'
 'MOTORIZED BICYCLE' 'SCHOOL BUS < 15 PEOPLE' 'MOTOR HOME' 'UNKNOWN'
 'PASSENGER CAR/VAN W/TRAILER' 'MOTORCYCLE' 'SUV W/TRAILER'
 'FARM EQUIPMENT' 'BICYCLE']
New format TU-1 Type ['Unknown ' 'Passenger Car/Passenger Van' 'SUV' nan
 'Pickup Truck/Utility Van'
 'Medium/Heavy Trucks, GVWR/GCWR 10,001 or Over'
 'Medium/Heavy Trucks, GVWR/GCWR 16,001 or over'
 'Non-School Bus (nine occupants or more including driver) in commerce'
 'Motor Home' 'Working Vehicle/Equipment'
 'Other Vehicle Type (Describe in Narrative)'
 'School Bus (all school buses)' 'Transit Bus' 'Motorcycle'
 'Farm Equipment' 'Autocycle' 'Off Highway Vehicle/ATV'
 'Low Speed Vehicle' 'Passenger Car/Passenger Van with Trailer - RET'
 'Light Rail']

In [ ]:
#