## People Centered COS - Convert CDOT Data format (2007-2020) to the 2021+ data format
## CHECK THE UTILITY FUNCTION WORKS 

 #### Part 1 - another notebook convert information on road condition, lighting, location, number of vehicles and people etc. 

 #### Part 2 - (THIS NOTEBOOK) - will handle the mapping from vechile and non-motorist attributes and speeds etc.

In [1]:
pip install pandas

Requirement already satisfied: pandas in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/lib/python3.13/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

### Load CDOT csvs

In [4]:
cdot_base_path = "/Users/haley.northrup/Desktop/PeopleCenteredCOS/cdot_data/"

In [5]:
# Load CDOT Data from new data format (2021+) 

year_new = 2024
filename_new = f"CDOTRM_CD_Crash_Listing_-_{year_new}.xlsx"

full_path_new = cdot_base_path + filename_new
print(full_path_new)

cdot_new_pdf = pd.read_excel(full_path_new)
display(cdot_new_pdf.head(5))

/Users/haley.northrup/Desktop/PeopleCenteredCOS/cdot_data/CDOTRM_CD_Crash_Listing_-_2024.xlsx

,CUID,System Code,Rd_Number,Rd_Section,City_Street,Crash Date,Crash Time,Agency Id,City,County,...,TU-2 NM Safety Helmet,TU-1 NM Alcohol Suspected,TU-2 NM Alcohol Suspected,TU-1 NM Marijuana Suspected,TU-2 NM Marijuana Suspected,TU-1 NM Other Drugs Suspected,TU-2 NM Other Drugs Suspected,Record Status,Processing Status,Last Updated
0,453608,City Street,0320,SANTA,THAVE,2024-01-01,00:16:00,DPD,DENVER,DENVER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Jun 13 2024 2:21PM
1,420975,State Highway,391A,8.482,NaN,2024-01-01,00:34:00,WRPD,WHEAT RIDGE,JEFFERSON,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Feb 26 2024 10:46PM
2,466850,State Highway,093A,16.461,NaN,2024-01-01,00:34:00,BLDPD,BOULDER,BOULDER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Jun 27 2024 12:21AM
3,453551,City Street,1285,THAVE,COLOR,2024-01-01,00:37:00,THPD,THORNTON,ADAMS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Jun 13 2024 2:20PM
4,467394,State Highway,082A,29.988,NaN,2024-01-01,00:40:00,CSP,NaN,PITKIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coded,Completed,Jun 19 2024 1:03PM

In [6]:
# Load CDOT Data from old data format (2007-2020) 

year = 2020
filename_old = f"CDOTRM_CD_Crash_Listing_-_{year}.xlsx"

full_path_old = cdot_base_path + filename_old
print(full_path_old)

cdot_old_pdf = pd.read_excel(full_path_old)
display(cdot_old_pdf.head(5))

/Users/haley.northrup/Desktop/PeopleCenteredCOS/cdot_data/CDOTRM_CD_Crash_Listing_-_2020.xlsx

,SYSTEM,RTE,SEC,MP,DATE,TIME,SEVERITY,INJURY 00,INJURY 01,INJURY 02,...,DRVINJ_1,DRVINJ_2,DRVINJ_3,DUI_1,DUI_2,DUI_3,CITY,COUNTY,LATITUDE,LONGITUDE
0,COUNTY ROAD,0,NaN,0.0,2020-01-01,0.0,PDO,0,0,0,...,NaN,NaN,NaN,N,N,N,NaN,MESA,0.000000,0.000000
1,CITY STREET,0,NaN,0.0,2020-01-01,1.0,PDO,0,0,0,...,NaN,NaN,NaN,N,N,N,GYPSUM,EAGLE,0.000000,0.000000
2,STATE HIGHWAY,160,A,123.1,2020-01-01,1.0,INJ,1,1,0,...,POSSIBLE/COMPLAINT OF INJURY,NaN,NaN,N,N,N,NaN,ARCHULETA,37.204663,-107.329465
3,CITY STREET,0,NaN,0.0,2020-01-01,6.0,PDO,0,0,0,...,NaN,NaN,NaN,N,N,N,CENTENNIAL,ARAPAHOE,39.578560,-104.807100
4,CITY STREET,0,NaN,0.0,2020-01-01,13.0,INJ,0,1,0,...,NaN,NaN,NaN,N,N,N,DENVER,DENVER,39.746541,-105.007589

### Inspect Data

In [7]:
print(cdot_new_pdf.info(verbose=True, show_counts=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92810 entries, 0 to 92809
Data columns (total 110 columns):
 #    Column                              Non-Null Count  Dtype
---   ------                              --------------  -----
 0    CUID                                92810 non-null  int64
 1    System Code                         92804 non-null  object
 2    Rd_Number                           92436 non-null  object
 3    Rd_Section                          91776 non-null  object
 4    City_Street                         51847 non-null  object
 5    Crash Date                          92810 non-null  datetime64[ns]
 6    Crash Time                          92632 non-null  object
 7    Agency Id                           92770 non-null  object
 8    City                                68696 non-null  object
 9    County                              92742 non-null  object
 10   Latitude                            87175 non-null  float64
 11   Longitude                           87177 non-null  float64
 12   Location 1                          92606 non-null  object
 13   Link                                92803 non-null  object
 14   Location 2                          91043 non-null  object
 15   Location                            92780 non-null  object
 16   Road Description                    92770 non-null  object
 17   First HE                            92767 non-null  object
 18   Second HE                           20048 non-null  object
 19   Third HE                            5293 non-null   object
 20   Fourth HE                           1586 non-null   object
 21   MHE                                 92545 non-null  object
 22   Crash Type                          90423 non-null  object
 23   Approach Overtaking Turn            92721 non-null  object
 24   Wild Animal                         2600 non-null   object
 25   Number Killed                       92810 non-null  int64
 26   Number Injured                      92810 non-null  int64
 27   Injury 00                           92810 non-null  int64
 28   Injury 01                           92810 non-null  int64
 29   Injury 02                           92810 non-null  int64
 30   Injury 03                           92810 non-null  int64
 31   Injury 04                           92810 non-null  int64
 32   Total Vehicles                      92809 non-null  float64
 33   Secondary Crash                     92809 non-null  float64
 34   Construction Zone                   92809 non-null  float64
 35   School Zone                         92809 non-null  float64
 36   Road Contour Curves                 85456 non-null  object
 37   Road Contour Grade                  85635 non-null  object
 38   Road Condition                      92279 non-null  object
 39   Lighting Conditions                 92259 non-null  object
 40   Weather Condition                   91943 non-null  object
 41   Weather Condition 2                 5859 non-null   object
 42   Lane Position                       82131 non-null  object
 43   TU-1 Direction                      91325 non-null  object
 44   TU-2 Direction                      72483 non-null  object
 45   TU-1 Movement                       91346 non-null  object
 46   TU-2 Movement                       72701 non-null  object
 47   TU-1 Type                           91348 non-null  object
 48   TU-2 Type                           72717 non-null  object
 49   TU-1 Special Function               83382 non-null  object
 50   TU-2 Special Function               69472 non-null  object
 51   TU-1 Autonomous Vehicle             84928 non-null  object
 52   TU-2 Autonomous Vehicle             70460 non-null  object
 53   TU-1 Hit And Run                    92810 non-null  bool
 54   TU-2 Hit And Run                    92810 non-null  bool
 55   TU-1 Speed Limit                    92810 non-null  int64
 56   TU-2 Speed Limit                    92810 non-null  int64
 57   TU-1 Estimated Speed                92810 non-null  int64
 58   TU-2 Estimated Speed                92810 non-null  int64
 59   TU-1 Speed                          92810 non-null  int64
 60   TU-2 Speed                          92810 non-null  int64
 61   TU-1 Driver Action                  85035 non-null  object
 62   TU-2 Driver Action                  68339 non-null  object
 63   TU-1 Human Contributing Factor      81256 non-null  object
 64   TU-2 Human Contributing Factor      68038 non-null  object
 65   TU-1 Age                            80394 non-null  float64
 66   TU-2 Age                            66153 non-null  float64
 67   TU-1 Sex                            79781 non-null  object
 68   TU-2 Sex                            65608 non-null  object
 69   TU-1 Safety System Available        76408 non-null  object
 70   TU-2 Safety System Available        61153 non-null  object
 71   TU-1 Safety restraint Use           78477 non-null  object
 72   TU-2 Safety restraint Use           61867 non-null  object
 73   TU-1 Safety Helmet                  79900 non-null  object
 74   TU-2  Safety Helmet                 63301 non-null  object
 75   TU-1 Alcohol Suspected              77124 non-null  object
 76   TU-2 Alcohol Suspected              62290 non-null  object
 77   TU-1  Marijuana Suspected           81046 non-null  object
 78   TU-2 Marijuana Suspected            63593 non-null  object
 79   TU-1 Other Drugs Suspected          76974 non-null  object
 80   TU-2 Other Drugs Suspected          61825 non-null  object
 81   TU-1 NM Direction                   994 non-null    object
 82   TU-2 NM Direction                   1695 non-null   object
 83   TU-1 NM Movement                    1109 non-null   object
 84   TU-2 NM Movement                    1817 non-null   object
 85   TU-1 NM Facility Available          1695 non-null   object
 86   TU-2 NM Facility Available          1695 non-null   object
 87   TU-1 NM Location                    1114 non-null   object
 88   TU-2 NM Location                    1816 non-null   object
 89   TU-1 NM Type                        1116 non-null   object
 90   TU-2 NM Type                        1817 non-null   object
 91   TU-1 NM Age                         839 non-null    float64
 92   TU-2 NM Age                         1498 non-null   float64
 93   TU-1 NM Sex                         1108 non-null   object
 94   TU-2 NM Sex                         1809 non-null   object
 95   TU-1 NM Action                      1112 non-null   object
 96   TU-2 NM Action                      1813 non-null   object
 97   TU-1 NM Human Contributing Factor   1028 non-null   object
 98   TU-2 NM Human Contributing Factor   1641 non-null   object
 99   TU-1 NM Safety Helmet               956 non-null    object
 100  TU-2 NM Safety Helmet               1553 non-null   object
 101  TU-1 NM Alcohol Suspected           975 non-null    object
 102  TU-2 NM Alcohol Suspected           1603 non-null   object
 103  TU-1 NM Marijuana Suspected         1007 non-null   object
 104  TU-2 NM Marijuana Suspected         1642 non-null   object
 105  TU-1 NM Other Drugs Suspected       962 non-null    object
 106  TU-2 NM Other Drugs Suspected       1586 non-null   object
 107  Record Status                       92810 non-null  object
 108  Processing Status                   92810 non-null  object
 109  Last Updated                        92810 non-null  object
dtypes: bool(2), datetime64[ns](1), float64(10), int64(14), object(83)
memory usage: 76.7+ MB
None

In [8]:
print(cdot_old_pdf.info(verbose=True, show_counts=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86304 entries, 0 to 86303
Data columns (total 84 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SYSTEM      86304 non-null  object
 1   RTE         86304 non-null  int64
 2   SEC         39426 non-null  object
 3   MP          86304 non-null  float64
 4   DATE        86304 non-null  datetime64[ns]
 5   TIME        86207 non-null  float64
 6   SEVERITY    86304 non-null  object
 7   INJURY 00   86304 non-null  int64
 8   INJURY 01   86304 non-null  int64
 9   INJURY 02   86304 non-null  int64
 10  INJURY 03   86304 non-null  int64
 11  INJURY 04   86304 non-null  int64
 12  AGENCYNAME  86276 non-null  object
 13  LOCATION    86304 non-null  object
 14  ROAD_DESC   86304 non-null  object
 15  VEHICLES    86304 non-null  int64
 16  CONTOUR     86304 non-null  object
 17  CONDITION   86304 non-null  object
 18  LIGHTING    86304 non-null  object
 19  WEATHER     86304 non-null  object
 20  LIMIT1      86304 non-null  object
 21  LIMIT2      86304 non-null  object
 22  LIMIT3      86304 non-null  object
 23  RAMP        86304 non-null  object
 24  REGION      86304 non-null  int64
 25  RUCODE      86304 non-null  object
 26  EVENT_1     86260 non-null  object
 27  EVENT_2     19425 non-null  object
 28  EVENT_3     2218 non-null   object
 29  MHE         86041 non-null  object
 30  ACCTYPE     86221 non-null  object
 31  DIR_1       86302 non-null  object
 32  VEHICLE_1   86303 non-null  object
 33  DRIVER_1    86304 non-null  object
 34  FACTOR_1    86291 non-null  object
 35  SPEED_1     86286 non-null  object
 36  VEH_MOVE_1  86302 non-null  object
 37  AGE_1       86304 non-null  int64
 38  SEX_1       75013 non-null  object
 39  STATE_1     74820 non-null  object
 40  BELT_1      67924 non-null  object
 41  DIR_2       65822 non-null  object
 42  VEHICLE_2   65831 non-null  object
 43  DRIVER_2    86304 non-null  object
 44  FACTOR_2    72883 non-null  object
 45  SPEED_2     65547 non-null  object
 46  VEH_MOVE_2  65829 non-null  object
 47  AGE_2       86304 non-null  int64
 48  SEX_2       57453 non-null  object
 49  STATE_2     56908 non-null  object
 50  BELT_2      54348 non-null  object
 51  DIR_3       7802 non-null   object
 52  VEHICLE_3   7803 non-null   object
 53  DRIVER_3    86304 non-null  object
 54  FACTOR_3    35451 non-null  object
 55  SPEED_3     7752 non-null   object
 56  VEH_MOVE_3  7802 non-null   object
 57  AGE_3       86304 non-null  int64
 58  SEX_3       6147 non-null   object
 59  STATE_3     6167 non-null   object
 60  BELT_3      5944 non-null   object
 61  WAN_TYPE    3443 non-null   object
 62  LOC_01      86278 non-null  object
 63  LINK        86000 non-null  object
 64  LOC_02      86020 non-null  object
 65  HAZMAT_1    86304 non-null  object
 66  HAZMAT_2    86304 non-null  object
 67  HAZMAT_3    86304 non-null  object
 68  VIOLCODE_1  53501 non-null  object
 69  VIOLCODE_2  1740 non-null   object
 70  VIOLCODE_3  220 non-null    object
 71  CYCPROT_1   81783 non-null  object
 72  CYCPROT_2   61068 non-null  object
 73  CYCPROT_3   6753 non-null   object
 74  DRVINJ_1    76988 non-null  object
 75  DRVINJ_2    58189 non-null  object
 76  DRVINJ_3    6229 non-null   object
 77  DUI_1       86304 non-null  object
 78  DUI_2       86304 non-null  object
 79  DUI_3       86304 non-null  object
 80  CITY        65166 non-null  object
 81  COUNTY      86304 non-null  object
 82  LATITUDE    86304 non-null  float64
 83  LONGITUDE   86304 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(11), object(68)
memory usage: 55.3+ MB
None

## Convert Data Using Function

In [9]:
import sys  
sys.path.insert(1, '../')

from convert_old_cdot_format_to_new_format import convert_old_cdot_format_to_new_format

In [10]:
converted_cdot_old_pdf = convert_old_cdot_format_to_new_format(cdot_old_pdf)

/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:403: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = ''
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:417: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[condition_hit_and_run__true, f"TU-{x} Hit And Run"] = True
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:438: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[df[f"vehicle_{x}_is_nm"] == True, f"TU-{x} NM Sex"] = df[f"SEX_{x}"]
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:439: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[df[f"vehicle_{x}_is_nm"] == False, sex_col] = df[f"SEX_{x}"]
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:446: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[df[f"vehicle_{x}_is_nm"] == False, safety_helmet_col] = df[f"CYCPROT_{x}"].map(map_helmet_x_old_to_new)
/Users/haley.northrup/Desktop/PeopleCenteredCOS/beautiful_cos_data_analysis/sandbox/../convert_old_cdot_format_to_new_format.py:467: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[condition_motorist & condition_no_impairment, marijuana_suspected_col] = 'Marijuana Not Suspected'

In [11]:
# TEST COMBINING CONVERTED DATA WITH NEW DATA

combined_cdot_pdf = pd.concat([converted_cdot_old_pdf, cdot_new_pdf])

In [12]:
print(combined_cdot_pdf.info(verbose=True, show_counts=True))

<class 'pandas.core.frame.DataFrame'>
Index: 179114 entries, 0 to 92809
Data columns (total 148 columns):
 #    Column                                                Non-Null Count   Dtype
---   ------                                                --------------   -----
 0    System Code                                           179011 non-null  object
 1    Crash Date                                            179017 non-null  datetime64[ns]
 2    Injury 00                                             179017 non-null  float64
 3    Injury 01                                             179017 non-null  float64
 4    Injury 02                                             179017 non-null  float64
 5    Injury 03                                             179017 non-null  float64
 6    Injury 04                                             179017 non-null  float64
 7    Agency Id                                             178949 non-null  object
 8    Location                                              178717 non-null  object
 9    Road Description                                      178950 non-null  object
 10   Total Vehicles                                        179016 non-null  float64
 11   Road Condition                                        178280 non-null  object
 12   Lighting Conditions                                   178227 non-null  object
 13   Weather Condition                                     177585 non-null  object
 14   First HE                                              164670 non-null  object
 15   Second HE                                             32752 non-null   object
 16   Third HE                                              6998 non-null    object
 17   MHE                                                   164279 non-null  object
 18   Crash Type                                            176550 non-null  object
 19   Location 1                                            178787 non-null  object
 20   Link                                                  178706 non-null  object
 21   Location 2                                            176971 non-null  object
 22   City                                                  133768 non-null  object
 23   County                                                178949 non-null  object
 24   Latitude                                              173382 non-null  float64
 25   Longitude                                             173384 non-null  float64
 26   CUID                                                  92810 non-null   float64
 27   Fourth HE                                             1586 non-null    object
 28   Secondary Crash                                       92809 non-null   float64
 29   Construction Zone                                     92809 non-null   float64
 30   School Zone                                           92809 non-null   float64
 31   Weather Condition 2                                   5859 non-null    object
 32   Lane Position                                         82131 non-null   object
 33   Record Status                                         92810 non-null   object
 34   Processing Status                                     92810 non-null   object
 35   Last Updated                                          92810 non-null   object
 36   TU-1 Special Function                                 83382 non-null   object
 37   TU-2 Special Function                                 69472 non-null   object
 38   TU-3 Special Function                                 0 non-null       float64
 39   TU-1 Autonomous Vehicle                               84928 non-null   object
 40   TU-2 Autonomous Vehicle                               70460 non-null   object
 41   TU-3 Autnomous Vehicle                                0 non-null       float64
 42   TU-1 Speed                                            92810 non-null   float64
 43   TU-2 Speed                                            92810 non-null   float64
 44   TU-3 Speed                                            0 non-null       float64
 45   TU-1 Driver Action                                    85035 non-null   object
 46   TU-2 Driver Action                                    68339 non-null   object
 47   TU-3 Driver Action                                    0 non-null       float64
 48   TU-1 Safety System Available                          76408 non-null   object
 49   TU-2 Safety System Available                          61153 non-null   object
 50   TU-3 Safety System Avaliable                          0 non-null       float64
 51   TU-1 NM Facility Available                            1695 non-null    object
 52   TU-2 NM Facility Available                            1695 non-null    object
 53   TU-3 NM Facility Available                            0 non-null       float64
 54   TU-1 NM Location                                      1114 non-null    object
 55   TU-2 NM Location                                      1816 non-null    object
 56   TU-3 NM Location                                      0 non-null       float64
 57   TU-1 NM Action                                        1112 non-null    object
 58   TU-2 NM Action                                        1813 non-null    object
 59   TU-3 NM Action                                        0 non-null       float64
 60   TU-1 Type                                             177554 non-null  object
 61   TU-1 NM Type                                          87323 non-null   object
 62   TU-2 Type                                             138481 non-null  object
 63   TU-2 NM Type                                          88024 non-null   object
 64   TU-3 Type                                             7796 non-null    object
 65   TU-3 NM Type                                          86207 non-null   object
 66   TU-1 Direction                                        177530 non-null  object
 67   TU-1 Movement                                         172827 non-null  object
 68   TU-1 Speed Limit                                      169333 non-null  object
 69   TU-1 Estimated Speed                                  162416 non-null  object
 70   TU-1 Human Contributing Factor                        138889 non-null  object
 71   TU-1 Age                                              166601 non-null  object
 72   TU-1 Safety restraint Use                             147094 non-null  object
 73   TU-1 Alcohol Suspected                                163331 non-null  object
 74   TU-1 Other Drugs Suspected                            163181 non-null  object
 75   TU-1 NM Direction                                     87201 non-null   object
 76   TU-1 NM Movement                                      87306 non-null   object
 77   TU-1 NM Age                                           87046 non-null   object
 78   TU-1 NM Sex                                           87315 non-null   object
 79   TU-1 NM Human Contributing Factor                     86773 non-null   object
 80   TU-1 NM Safety Helmet                                 87019 non-null   object
 81   TU-1 NM Alcohol Suspected                             87182 non-null   object
 82   TU-1 NM Marijuana Suspected                           87214 non-null   object
 83   TU-1 NM Other Drugs Suspected                         87169 non-null   object
 84   TU-1 Sex TU-1 Safety HelmetTU-1  Marijuana Suspected  86207 non-null   object
 85   TU-1 Hit And Run                                      178252 non-null  object
 86   TU-1 NM Sex                                           746 non-null     object
 87   TU-1 Sex                                              153992 non-null  object
 88   TU-1 Safety Helmet                                    160999 non-null  object
 89   TU-1  Marijuana Suspected                             165998 non-null  object
 90   TU-2 Direction                                        138239 non-null  object
 91   TU-2 Movement                                         134038 non-null  object
 92   TU-2 Speed Limit                                      149886 non-null  object
 93   TU-2 Estimated Speed                                  147288 non-null  object
 94   TU-2 Human Contributing Factor                        133679 non-null  object
 95   TU-2 Age                                              152360 non-null  object
 96   TU-2 Safety restraint Use                             117303 non-null  object
 97   TU-2 Alcohol Suspected                                148497 non-null  object
 98   TU-2 Other Drugs Suspected                            148032 non-null  object
 99   TU-2 NM Direction                                     87901 non-null   object
 100  TU-2 NM Movement                                      87700 non-null   object
 101  TU-2 NM Age                                           87705 non-null   object
 102  TU-2 NM Sex                                           88016 non-null   object
 103  TU-2 NM Human Contributing Factor                     87321 non-null   object
 104  TU-2 NM Safety Helmet                                 87702 non-null   object
 105  TU-2 NM Alcohol Suspected                             87810 non-null   object
 106  TU-2 NM Marijuana Suspected                           87849 non-null   object
 107  TU-2 NM Other Drugs Suspected                         87793 non-null   object
 108  TU-2 SexTU-2  Safety HelmetTU-2 Marijuana Suspected   86207 non-null   object
 109  TU-2 Hit And Run                                      177859 non-null  object
 110  TU-2 NM Sex                                           1132 non-null    object
 111  TU-2 Sex                                              121890 non-null  object
 112  TU-2  Safety Helmet                                   123230 non-null  object
 113  TU-2 Marijuana Suspected                              148625 non-null  object
 114  TU-3 Direction                                        7795 non-null    object
 115  TU-3 Movement                                         6863 non-null    object
 116  TU-3 Speed Limit                                      6246 non-null    object
 117  TU-3 Estimated Speed                                  6278 non-null    object
 118  TU-3 Human Contributing Factor                        34256 non-null   object
 119  TU-3 Age                                              86207 non-null   object
 120  TU-3 Safety restraint Use                             5980 non-null    object
 121  TU-3 Alcohol Suspected                                86207 non-null   object
 122  TU-3 Other Drugs Suspected                            86207 non-null   object
 123  TU-3 NM Direction                                     86207 non-null   object
 124  TU-3 NM Movement                                      86205 non-null   object
 125  TU-3 NM Age                                           86207 non-null   object
 126  TU-3 NM Sex                                           86207 non-null   object
 127  TU-3 NM Human Contributing Factor                     86192 non-null   object
 128  TU-3 NM Safety Helmet                                 86202 non-null   object
 129  TU-3 NM Alcohol Suspected                             86207 non-null   object
 130  TU-3 NM Marijuana Suspected                           86207 non-null   object
 131  TU-3 NM Other Drugs Suspected                         86207 non-null   object
 132  TU-3 SexTU-3 Safety HelmetTU-3 Marijuana Suspected    86207 non-null   object
 133  TU-3 Hit And Run                                      86166 non-null   object
 134  TU-3 NM Sex                                           41 non-null      object
 135  TU-3 Sex                                              6102 non-null    object
 136  TU-3 Safety Helmet                                    6713 non-null    object
 137  TU-3 Marijuana Suspected                              86165 non-null   object
 138  Wild Animal                                           6039 non-null    object
 139  Road Contour Curves                                   171663 non-null  object
 140  Road Contour Grade                                    171842 non-null  object
 141  Number Killed                                         179017 non-null  float64
 142  Number Injured                                        179017 non-null  float64
 143  Approach Overtaking Turn                              178928 non-null  object
 144  Crash Time                                            178839 non-null  object
 145  Rd_Number                                             131835 non-null  object
 146  Rd_Section                                            177983 non-null  object
 147  City_Street                                           51847 non-null   object
dtypes: datetime64[ns](1), float64(24), object(123)
memory usage: 203.6+ MB
None

In [13]:
cdot_new_pdf[['TU-1  Marijuana Suspected', 'TU-1 NM Marijuana Suspected ', 'TU-2 Marijuana Suspected', 'TU-2 NM Marijuana Suspected ']]

,TU-1 Marijuana Suspected,TU-1 NM Marijuana Suspected,TU-2 Marijuana Suspected,TU-2 NM Marijuana Suspected
0,Unknown,NaN,Marijuana Not Suspected,NaN
1,Marijuana Not Suspected,NaN,Marijuana Not Suspected,NaN
2,Marijuana Not Suspected,NaN,Marijuana Not Suspected,NaN
3,Unknown,NaN,Marijuana Not Suspected,NaN
4,NaN,NaN,NaN,NaN
...,...,...,...,...
92805,Marijuana Not Suspected,NaN,Marijuana Not Suspected,NaN
92806,NaN,NaN,Marijuana Not Suspected,NaN
92807,Marijuana Not Suspected,NaN,NaN,NaN
92808,Marijuana Not Suspected,NaN,NaN,NaN
92809,Unknown,NaN,Marijuana Not Suspected,NaN

In [14]:
combined_cdot_pdf[['TU-1  Marijuana Suspected', 
                   'TU-1 NM Marijuana Suspected ', 
                   'TU-2 Marijuana Suspected', 
                   'TU-2 NM Marijuana Suspected ']]

,TU-1 Marijuana Suspected,TU-1 NM Marijuana Suspected,TU-2 Marijuana Suspected,TU-2 NM Marijuana Suspected
0,Marijuana Not Suspected,,Marijuana Not Suspected,
1,Marijuana Not Suspected,,Marijuana Not Suspected,
2,Marijuana Not Suspected,,Marijuana Not Suspected,
3,Marijuana Not Suspected,,Marijuana Not Suspected,
4,Marijuana Not Suspected,,Marijuana Not Suspected,
...,...,...,...,...
92805,Marijuana Not Suspected,NaN,Marijuana Not Suspected,NaN
92806,NaN,NaN,Marijuana Not Suspected,NaN
92807,Marijuana Not Suspected,NaN,NaN,NaN
92808,Marijuana Not Suspected,NaN,NaN,NaN
92809,Unknown,NaN,Marijuana Not Suspected,NaN

In [15]:
cdot_new_pdf[['TU-1 Safety Helmet', 'TU-1 NM Safety Helmet ', 'TU-2  Safety Helmet', 'TU-2 NM Safety Helmet ']]

,TU-1 Safety Helmet,TU-1 NM Safety Helmet,TU-2 Safety Helmet,TU-2 NM Safety Helmet
0,Unknown (Describe in Narrative),NaN,N/A (Cars/Trucks),NaN
1,N/A (Cars/Trucks),NaN,N/A (Cars/Trucks),NaN
2,N/A (Cars/Trucks),NaN,N/A (Cars/Trucks),NaN
3,Unknown (Describe in Narrative),NaN,N/A (Cars/Trucks),NaN
4,NaN,NaN,NaN,NaN
...,...,...,...,...
92805,N/A (Cars/Trucks),NaN,N/A (Cars/Trucks),NaN
92806,NaN,NaN,N/A (Cars/Trucks),NaN
92807,N/A (Cars/Trucks),NaN,NaN,NaN
92808,N/A (Cars/Trucks),NaN,NaN,NaN
92809,N/A (Cars/Trucks),NaN,N/A (Cars/Trucks),NaN

In [16]:
combined_cdot_pdf[['TU-1 Safety Helmet', 'TU-1 NM Safety Helmet ', 'TU-2  Safety Helmet', 'TU-2 NM Safety Helmet ']]

,TU-1 Safety Helmet,TU-1 NM Safety Helmet,TU-2 Safety Helmet,TU-2 NM Safety Helmet
0,No Helmet,,No Helmet,
1,No Helmet,,No Helmet,
2,No Helmet,,NaN,
3,No Helmet,,NaN,
4,No Helmet,,NaN,
...,...,...,...,...
92805,N/A (Cars/Trucks),NaN,N/A (Cars/Trucks),NaN
92806,NaN,NaN,N/A (Cars/Trucks),NaN
92807,N/A (Cars/Trucks),NaN,NaN,NaN
92808,N/A (Cars/Trucks),NaN,NaN,NaN
92809,N/A (Cars/Trucks),NaN,N/A (Cars/Trucks),NaN

In [17]:
cdot_new_pdf[['TU-1 Sex ', 'TU-1 NM Sex ', 'TU-2 Sex', 'TU-2 NM Sex ']]

      TU-1 Sex  TU-1 NM Sex  TU-2 Sex TU-2 NM Sex
0           NaN          NaN        M          NaN
1             F          NaN        M          NaN
2             M          NaN        M          NaN
3           NaN          NaN        F          NaN
4           NaN          NaN      NaN          NaN
...         ...          ...      ...          ...
92805         F          NaN        M          NaN
92806       NaN          NaN        F          NaN
92807         F          NaN      NaN          NaN
92808         M          NaN      NaN          NaN
92809         M          NaN        F          NaN

[92810 rows x 4 columns]

In [18]:
combined_cdot_pdf[['TU-1 Sex ', 'TU-1 NM Sex ', 'TU-2 Sex', 'TU-2 NM Sex ']]

      TU-1 Sex  TU-1 NM Sex  TU-2 Sex TU-2 NM Sex
0             U                   NaN
1           NaN                   NaN
2             F                   NaN
3           NaN                   NaN
4           NaN                   NaN
...         ...          ...      ...          ...
92805         F          NaN        M          NaN
92806       NaN          NaN        F          NaN
92807         F          NaN      NaN          NaN
92808         M          NaN      NaN          NaN
92809         M          NaN        F          NaN

[179114 rows x 4 columns]

### Check Individual Columns

In [26]:
# Columns that should be set to np.nan 
nan_columns = [
        'CUID', 
        'Fourth HE', 
        'Secondary Crash', 
        'Construction Zone', 
        'School Zone', 
        'Weather Condition 2',
        'Lane Position',
        'Record Status',
        'Processing Status', 
        'Last Updated', 
        'TU-1 Special Function',
        'TU-2 Special Function', 
        'TU-3 Special Function',
        'TU-1 Autonomous Vehicle', 
        'TU-2 Autonomous Vehicle', 
        'TU-3 Autnomous Vehicle',
        'TU-1 Speed',
        'TU-2 Speed',
        'TU-3 Speed',
        'TU-1 Driver Action', 
        'TU-2 Driver Action',
         'TU-3 Driver Action',  
        'TU-1 Safety System Available ', 
        'TU-2 Safety System Available ', 
        'TU-3 Safety System Avaliable ', 
        'TU-1 NM Facility Available', 
        'TU-2 NM Facility Available',
        'TU-3 NM Facility Available',
        'TU-1 NM Location ', 
        'TU-2 NM Location ', 
        'TU-3 NM Location ',
        'TU-1 NM Action ',
        'TU-2 NM Action ',
        'TU-3 NM Action ',
    ]
       

for column_name in nan_columns:
    print('COLUMN', column_name)
    print('New values')
    if column_name in list(cdot_new_pdf.columns):
        print(cdot_new_pdf[column_name].unique())
    print('Old converted values')
    print(converted_cdot_old_pdf[column_name].unique())
    print('combined new and old converted values')
    print(combined_cdot_pdf[column_name].unique())
    print()
    print()

COLUMN CUID
New values
[ 453608  420975  466850 ... 1259354 1259208 1259318]
Old converted values
[nan]
combined new and old converted values
[     nan  453608.  420975. ... 1259354. 1259208. 1259318.]


COLUMN Fourth HE
New values
[nan 'Overturning/Rollover' 'Electical/Utility Box' 'Parked Motor Vehicle'
 'Front to Rear' 'Culvert or Headwall' 'Tree' 'Rear to Side'
 'Front to Side' 'Fence' 'Side to Side-Same Direction' 'Cable Rail'
 'Other Fixed Object (Describe in Narrative)' 'Light Pole/Utility Pole'
 'Wall or Building' 'Ground' 'Rear to Rear' 'Vehicle Debris or Cargo'
 'Sign' 'Curb' 'Embankment' 'Mailbox'
 'Other Non-Fixed Object (Describe in Narrative)'
 'Side to Side-Opposite Direction' 'Concrete Highway Barrier'
 'Front to Front' 'Traffic Signal Pole' 'Pedestrian' 'Guardrail End'
 'Overhead Structure (Bridge)' 'Bridge Structure (Not Overhead)' 'Ditch'
 'Barricade' 'Other Non-Collision' 'Guardrail Face'
 'Immersion, Full or Partial' 'Large Rocks or Boulder'
 'Fell from Motor Vehicle' 'Delineator/Milepost' 'Wild Animal'
 'Overhead Structure (Not Bridge)' 'Crash Cushion/Traffic Barrel']
Old converted values
[nan]
combined new and old converted values
[nan 'Overturning/Rollover' 'Electical/Utility Box' 'Parked Motor Vehicle'
 'Front to Rear' 'Culvert or Headwall' 'Tree' 'Rear to Side'
 'Front to Side' 'Fence' 'Side to Side-Same Direction' 'Cable Rail'
 'Other Fixed Object (Describe in Narrative)' 'Light Pole/Utility Pole'
 'Wall or Building' 'Ground' 'Rear to Rear' 'Vehicle Debris or Cargo'
 'Sign' 'Curb' 'Embankment' 'Mailbox'
 'Other Non-Fixed Object (Describe in Narrative)'
 'Side to Side-Opposite Direction' 'Concrete Highway Barrier'
 'Front to Front' 'Traffic Signal Pole' 'Pedestrian' 'Guardrail End'
 'Overhead Structure (Bridge)' 'Bridge Structure (Not Overhead)' 'Ditch'
 'Barricade' 'Other Non-Collision' 'Guardrail Face'
 'Immersion, Full or Partial' 'Large Rocks or Boulder'
 'Fell from Motor Vehicle' 'Delineator/Milepost' 'Wild Animal'
 'Overhead Structure (Not Bridge)' 'Crash Cushion/Traffic Barrel']


COLUMN Secondary Crash
New values
[ 0.  1. nan]
Old converted values
[nan]
combined new and old converted values
[nan  0.  1.]


COLUMN Construction Zone
New values
[ 0.  1. nan]
Old converted values
[nan]
combined new and old converted values
[nan  0.  1.]


COLUMN School Zone
New values
[ 0.  1. nan]
Old converted values
[nan]
combined new and old converted values
[nan  0.  1.]


COLUMN Weather Condition 2
New values
[nan 'Clear' 'Snow' 'Wind' 'Sleet or Hail' 'Blowing Snow' 'Cloudy'
 'Freezing Rain or Freezing Drizzle' 'Fog' 'Rain' 'Dust']
Old converted values
[nan]
combined new and old converted values
[nan 'Clear' 'Snow' 'Wind' 'Sleet or Hail' 'Blowing Snow' 'Cloudy'
 'Freezing Rain or Freezing Drizzle' 'Fog' 'Rain' 'Dust']


COLUMN Lane Position
New values
['N02' 'N01' nan 'S01' 'WLS' 'SRS' 'E01' 'N03' 'W01' 'S10' 'WRS' 'E03'
 'W02' 'E02' 'ERS' 'ELS' '000' 'S02' 'E04' '001' 'NLS' 'W03' 'N04' 'W'
 'S03' 'NRS' 'S04' 'W04' 'N05' 'SLS' 'W2' '00' 'E05' '01' '003' '1' 'S05'
 'S06' 'W05' 'EB2' 'W06' '06' 'N' '2' 'E06' 'B02' 'S07' 'E12' '002' '0'
 '02' 'RES' 'N06' 'N10' 'W1' 'SEM' 'S' 'T1' '100' '3' 'N1' '04' '004' 'E4'
 'S1' 'RS0' '#02' 'WO1' 'E' '11' 'N07' 'S2' 'E07' 'S00' 'S12' 'EBS' '08'
 '14' 'N3' 'E2' 'E20' 'N2' 'E10' 'RS' '123' '12' '03' 'LS' 'W07' 'S20'
 'SBS' 'WBL' '07' 'NBS' 'N08' '05' 'ECN' 'LS1' '006' '7' 'E1' 'N12' 'E3'
 'R' 'W4' 'B01' 'LS0' 'RS1' 'N4' 'SB2' '1N' 'RLS' 'SB1' '1E' '23' 'D01'
 'S3' 'NB2' 'E08' 'N00']
Old converted values
[nan]
combined new and old converted values
[nan 'N02' 'N01' 'S01' 'WLS' 'SRS' 'E01' 'N03' 'W01' 'S10' 'WRS' 'E03'
 'W02' 'E02' 'ERS' 'ELS' '000' 'S02' 'E04' '001' 'NLS' 'W03' 'N04' 'W'
 'S03' 'NRS' 'S04' 'W04' 'N05' 'SLS' 'W2' '00' 'E05' '01' '003' '1' 'S05'
 'S06' 'W05' 'EB2' 'W06' '06' 'N' '2' 'E06' 'B02' 'S07' 'E12' '002' '0'
 '02' 'RES' 'N06' 'N10' 'W1' 'SEM' 'S' 'T1' '100' '3' 'N1' '04' '004' 'E4'
 'S1' 'RS0' '#02' 'WO1' 'E' '11' 'N07' 'S2' 'E07' 'S00' 'S12' 'EBS' '08'
 '14' 'N3' 'E2' 'E20' 'N2' 'E10' 'RS' '123' '12' '03' 'LS' 'W07' 'S20'
 'SBS' 'WBL' '07' 'NBS' 'N08' '05' 'ECN' 'LS1' '006' '7' 'E1' 'N12' 'E3'
 'R' 'W4' 'B01' 'LS0' 'RS1' 'N4' 'SB2' '1N' 'RLS' 'SB1' '1E' '23' 'D01'
 'S3' 'NB2' 'E08' 'N00']


COLUMN Record Status
New values
['Coded' 'New' 'In Progress']
Old converted values
[nan]
combined new and old converted values
[nan 'Coded' 'New' 'In Progress']


COLUMN Processing Status
New values
['Completed' 'AC Off Sys' 'AC On Sys' 'Normalized' 'New' 'In Progress']
Old converted values
[nan]
combined new and old converted values
[nan 'Completed' 'AC Off Sys' 'AC On Sys' 'Normalized' 'New' 'In Progress']


COLUMN Last Updated
New values
['Jun 13 2024  2:21PM' 'Feb 26 2024 10:46PM' 'Jun 27 2024 12:21AM' ...
 'Jan  2 2025  1:52PM' 'Jan  3 2025  1:57PM' 'Jan  3 2025  6:46PM']
Old converted values
[nan]
combined new and old converted values
[nan 'Jun 13 2024  2:21PM' 'Feb 26 2024 10:46PM' ... 'Jan  2 2025  1:52PM'
 'Jan  3 2025  1:57PM' 'Jan  3 2025  6:46PM']


COLUMN TU-1 Special Function
New values
['No Special Function' nan 'Other (Describe in Narrative)'
 'Public Utility' 'Bus â€“ Transit'
 'Non-Transport Emergency Services Vehicle' 'Police' 'Fire Truck'
 'Bus â€“ Other' 'Taxi' 'Ambulance' 'Bus â€“ Shuttle'
 'Vehicle Transporting Students To/From School' 'Construction Equipment'
 'Highway/Maintenance'
 'Vehicle Used for Electronic Ride-hailing (Uber, Lyft etc.)'
 'Rental Truck' 'Towing â€“ Incident Response' 'Farm Vehicle'
 'Other Incident Response' 'Safety Service Patrols â€“ Incident Response'
 'Farm Equipment' 'Bus â€“ Charter' 'Military'
 'Truck Acting as Crash Attenuator']
Old converted values
[nan]
combined new and old converted values
[nan 'No Special Function' 'Other (Describe in Narrative)'
 'Public Utility' 'Bus â€“ Transit'
 'Non-Transport Emergency Services Vehicle' 'Police' 'Fire Truck'
 'Bus â€“ Other' 'Taxi' 'Ambulance' 'Bus â€“ Shuttle'
 'Vehicle Transporting Students To/From School' 'Construction Equipment'
 'Highway/Maintenance'
 'Vehicle Used for Electronic Ride-hailing (Uber, Lyft etc.)'
 'Rental Truck' 'Towing â€“ Incident Response' 'Farm Vehicle'
 'Other Incident Response' 'Safety Service Patrols â€“ Incident Response'
 'Farm Equipment' 'Bus â€“ Charter' 'Military'
 'Truck Acting as Crash Attenuator']


COLUMN TU-2 Special Function
New values
['No Special Function' nan 'Bus â€“ Transit' 'Police'
 'Non-Transport Emergency Services Vehicle'
 'Vehicle Used for Electronic Ride-hailing (Uber, Lyft etc.)'
 'Public Utility' 'Ambulance' 'Other (Describe in Narrative)'
 'Construction Equipment' 'Highway/Maintenance' 'Farm Vehicle'
 'Towing â€“ Incident Response' 'Fire Truck' 'Rental Truck' 'Bus â€“ Other'
 'Vehicle Transporting Students To/From School' 'Taxi' 'Bus â€“ Shuttle'
 'Truck Acting as Crash Attenuator' 'Farm Equipment'
 'Other Incident Response' 'Military'
 'Safety Service Patrols â€“ Incident Response' 'Bus â€“ Charter']
Old converted values
[nan]
combined new and old converted values
[nan 'No Special Function' 'Bus â€“ Transit' 'Police'
 'Non-Transport Emergency Services Vehicle'
 'Vehicle Used for Electronic Ride-hailing (Uber, Lyft etc.)'
 'Public Utility' 'Ambulance' 'Other (Describe in Narrative)'
 'Construction Equipment' 'Highway/Maintenance' 'Farm Vehicle'
 'Towing â€“ Incident Response' 'Fire Truck' 'Rental Truck' 'Bus â€“ Other'
 'Vehicle Transporting Students To/From School' 'Taxi' 'Bus â€“ Shuttle'
 'Truck Acting as Crash Attenuator' 'Farm Equipment'
 'Other Incident Response' 'Military'
 'Safety Service Patrols â€“ Incident Response' 'Bus â€“ Charter']


COLUMN TU-3 Special Function
New values
Old converted values
[nan]
combined new and old converted values
[nan]


COLUMN TU-1 Autonomous Vehicle
New values
['No Automation' nan 'Unknown' 'Driver Assistance' 'Partial Automation'
 'Conditional Automation' 'High Automation' 'Full Automation']
Old converted values
[nan]
combined new and old converted values
[nan 'No Automation' 'Unknown' 'Driver Assistance' 'Partial Automation'
 'Conditional Automation' 'High Automation' 'Full Automation']


COLUMN TU-2 Autonomous Vehicle
New values
['No Automation' nan 'Unknown' 'Driver Assistance' 'Partial Automation'
 'Conditional Automation' 'High Automation' 'Full Automation']
Old converted values
[nan]
combined new and old converted values
[nan 'No Automation' 'Unknown' 'Driver Assistance' 'Partial Automation'
 'Conditional Automation' 'High Automation' 'Full Automation']


COLUMN TU-3 Autnomous Vehicle
New values
Old converted values
[nan]
combined new and old converted values
[nan]


COLUMN TU-1 Speed
New values
[  0  43  15  35  25  62  30  65  20  10  60  45  40  75  55  70  50   5
   3  18  12  67  90  78   2  68  80   1   4   7  77  32  63  58   8  72
  42  14  66  51  47  17  28  23  22  52  37   6  11  64  48  54  85  31
  21  57  13   9  44  36  69  33  59 110 100  19  79  41 320  24  76  38
  16  73  61  88  46 120  27 130  49 140  29  39  53  34  56  83  74 105
 354  95  26  71 356  82  86  91 700  87  81 645  92 255 304 435]
Old converted values
[nan]
combined new and old converted values
[ nan   0.  43.  15.  35.  25.  62.  30.  65.  20.  10.  60.  45.  40.
  75.  55.  70.  50.   5.   3.  18.  12.  67.  90.  78.   2.  68.  80.
   1.   4.   7.  77.  32.  63.  58.   8.  72.  42.  14.  66.  51.  47.
  17.  28.  23.  22.  52.  37.   6.  11.  64.  48.  54.  85.  31.  21.
  57.  13.   9.  44.  36.  69.  33.  59. 110. 100.  19.  79.  41. 320.
  24.  76.  38.  16.  73.  61.  88.  46. 120.  27. 130.  49. 140.  29.
  39.  53.  34.  56.  83.  74. 105. 354.  95.  26.  71. 356.  82.  86.
  91. 700.  87.  81. 645.  92. 255. 304. 435.]


COLUMN TU-2 Speed
New values
[ 30   0   5  45  25  15  65  10  75  58  40   2  60  50  35  52  27  72
  55  70  20   8  42  37   3  24  28  18  34  12  80  43  38  67  36  82
  47  68  48  76   4  32  74  17   1  21  29  79  69   9  63  22  62   7
   6  78  77  41  57  64  33  39  49  11  90  59  46  23  56  44  14  71
  13  19  66  84  53  26  54  31  61  16  51  73 100  85 365 201 730]
Old converted values
[nan]
combined new and old converted values
[ nan  30.   0.   5.  45.  25.  15.  65.  10.  75.  58.  40.   2.  60.
  50.  35.  52.  27.  72.  55.  70.  20.   8.  42.  37.   3.  24.  28.
  18.  34.  12.  80.  43.  38.  67.  36.  82.  47.  68.  48.  76.   4.
  32.  74.  17.   1.  21.  29.  79.  69.   9.  63.  22.  62.   7.   6.
  78.  77.  41.  57.  64.  33.  39.  49.  11.  90.  59.  46.  23.  56.
  44.  14.  71.  13.  19.  66.  84.  53.  26.  54.  31.  61.  16.  51.
  73. 100.  85. 365. 201. 730.]


COLUMN TU-3 Speed
New values
Old converted values
[nan]
combined new and old converted values
[nan]


COLUMN TU-1 Driver Action
New values
['Careless Driving ' 'Impeded Traffic' nan 'Lane Violation'
 'Failed to Yield ROW' 'Other Contributing Action (Describe in Narrative)'
 'Disregard Stop Sign' 'Improper Turn' 'Reckless Driving'
 'Failed to Stop at Signal' 'Speeding' 'Too Fast for Conditions'
 'Followed Too Closely' 'No Contributing Action'
 'Over-Correcting/ Over-Steering' 'Disregarded Other Device/Sign/Markings'
 'Improper Passing on Right' 'Improper Backing'
 'Turned from Wrong Lane or Position' 'Improper Passing on Left' 'Racing'
 'Lacking Required Chains' 'Signaling Violation']
Old converted values
[nan]
combined new and old converted values
[nan 'Careless Driving ' 'Impeded Traffic' 'Lane Violation'
 'Failed to Yield ROW' 'Other Contributing Action (Describe in Narrative)'
 'Disregard Stop Sign' 'Improper Turn' 'Reckless Driving'
 'Failed to Stop at Signal' 'Speeding' 'Too Fast for Conditions'
 'Followed Too Closely' 'No Contributing Action'
 'Over-Correcting/ Over-Steering' 'Disregarded Other Device/Sign/Markings'
 'Improper Passing on Right' 'Improper Backing'
 'Turned from Wrong Lane or Position' 'Improper Passing on Left' 'Racing'
 'Lacking Required Chains' 'Signaling Violation']


COLUMN TU-2 Driver Action
New values
['No Contributing Action' nan 'Failed to Yield ROW' 'Reckless Driving'
 'Other Contributing Action (Describe in Narrative)' 'Improper Turn'
 'Over-Correcting/ Over-Steering' 'Lane Violation'
 'Improper Passing on Left' 'Disregarded Other Device/Sign/Markings'
 'Improper Backing' 'Careless Driving ' 'Followed Too Closely'
 'Disregard Stop Sign' 'Impeded Traffic' 'Failed to Stop at Signal'
 'Speeding' 'Too Fast for Conditions' 'Turned from Wrong Lane or Position'
 'Improper Passing on Right' 'Signaling Violation'
 'Lacking Required Chains' 'Racing']
Old converted values
[nan]
combined new and old converted values
[nan 'No Contributing Action' 'Failed to Yield ROW' 'Reckless Driving'
 'Other Contributing Action (Describe in Narrative)' 'Improper Turn'
 'Over-Correcting/ Over-Steering' 'Lane Violation'
 'Improper Passing on Left' 'Disregarded Other Device/Sign/Markings'
 'Improper Backing' 'Careless Driving ' 'Followed Too Closely'
 'Disregard Stop Sign' 'Impeded Traffic' 'Failed to Stop at Signal'
 'Speeding' 'Too Fast for Conditions' 'Turned from Wrong Lane or Position'
 'Improper Passing on Right' 'Signaling Violation'
 'Lacking Required Chains' 'Racing']


COLUMN TU-3 Driver Action
New values
Old converted values
[nan]
combined new and old converted values
[nan]


COLUMN TU-1 Safety System Available
New values
[nan 'Shoulder and Lap Belt' 'N/A (e.g. Motorcycle)' 'Shoulder Belt Only'
 'Lap Belt Only' 'Booster Seat' 'Child Restraint â€“ Type Unknown'
 'Child Restraint â€“ Forward Facing' 'Child Restraint â€“ Rear Facing']
Old converted values
[nan]
combined new and old converted values
[nan 'Shoulder and Lap Belt' 'N/A (e.g. Motorcycle)' 'Shoulder Belt Only'
 'Lap Belt Only' 'Booster Seat' 'Child Restraint â€“ Type Unknown'
 'Child Restraint â€“ Forward Facing' 'Child Restraint â€“ Rear Facing']


COLUMN TU-2 Safety System Available
New values
['Shoulder and Lap Belt' nan 'N/A (e.g. Motorcycle)' 'Shoulder Belt Only'
 'Child Restraint â€“ Forward Facing' 'Child Restraint â€“ Rear Facing'
 'Lap Belt Only' 'Child Restraint â€“ Type Unknown' 'Booster Seat']
Old converted values
[nan]
combined new and old converted values
[nan 'Shoulder and Lap Belt' 'N/A (e.g. Motorcycle)' 'Shoulder Belt Only'
 'Child Restraint â€“ Forward Facing' 'Child Restraint â€“ Rear Facing'
 'Lap Belt Only' 'Child Restraint â€“ Type Unknown' 'Booster Seat']


COLUMN TU-3 Safety System Avaliable
New values
Old converted values
[nan]
combined new and old converted values
[nan]


COLUMN TU-1 NM Facility Available
New values
[nan 'Shared Travelway' 'Other (Describe in Narrative)' 'Sidewalk'
 'Unmarked Paved Shoulder' 'No Specific Facility' 'Crosswalk'
 'Marked Bicycle Lane' 'Protected Bicycle Lane'
 'Separate Bicycle Path/Trail']
Old converted values
[nan]
combined new and old converted values
[nan 'Shared Travelway' 'Other (Describe in Narrative)' 'Sidewalk'
 'Unmarked Paved Shoulder' 'No Specific Facility' 'Crosswalk'
 'Marked Bicycle Lane' 'Protected Bicycle Lane'
 'Separate Bicycle Path/Trail']


COLUMN TU-2 NM Facility Available
New values
[nan 'Shared Travelway' 'Other (Describe in Narrative)' 'Sidewalk'
 'Unmarked Paved Shoulder' 'No Specific Facility' 'Crosswalk'
 'Marked Bicycle Lane' 'Protected Bicycle Lane'
 'Separate Bicycle Path/Trail']
Old converted values
[nan]
combined new and old converted values
[nan 'Shared Travelway' 'Other (Describe in Narrative)' 'Sidewalk'
 'Unmarked Paved Shoulder' 'No Specific Facility' 'Crosswalk'
 'Marked Bicycle Lane' 'Protected Bicycle Lane'
 'Separate Bicycle Path/Trail']


COLUMN TU-3 NM Facility Available
New values
Old converted values
[nan]
combined new and old converted values
[nan]


COLUMN TU-1 NM Location
New values
[nan 'Driveway Access' 'Midblock â€“ Non-Crosswalk'
 'Intersection â€“ Unmarked Crosswalk' 'Travel Lane â€“ Other Location'
 'Shared-Use Path or Trail' 'Intersection â€“ Other'
 'Intersection â€“ Marked Crosswalk' 'Marked Bicycle Lane' 'Sidewalk'
 'Other Location (Describe in Narrative)' 'Median/Crossing Island'
 'Midblock â€“ Marked Crosswalk' 'Shoulder/Roadside'
 'Protected Bicycle Lane' 'Non-Trafficway Area']
Old converted values
[nan]
combined new and old converted values
[nan 'Driveway Access' 'Midblock â€“ Non-Crosswalk'
 'Intersection â€“ Unmarked Crosswalk' 'Travel Lane â€“ Other Location'
 'Shared-Use Path or Trail' 'Intersection â€“ Other'
 'Intersection â€“ Marked Crosswalk' 'Marked Bicycle Lane' 'Sidewalk'
 'Other Location (Describe in Narrative)' 'Median/Crossing Island'
 'Midblock â€“ Marked Crosswalk' 'Shoulder/Roadside'
 'Protected Bicycle Lane' 'Non-Trafficway Area']


COLUMN TU-2 NM Location
New values
[nan 'Intersection â€“ Unmarked Crosswalk' 'Intersection â€“ Other'
 'Driveway Access' 'Shoulder/Roadside' 'Intersection â€“ Marked Crosswalk'
 'Midblock â€“ Non-Crosswalk' 'Sidewalk'
 'Other Location (Describe in Narrative)' 'Midblock â€“ Marked Crosswalk'
 'Travel Lane â€“ Other Location' 'Marked Bicycle Lane'
 'Median/Crossing Island' 'Protected Bicycle Lane'
 'Shared-Use Path or Trail']
Old converted values
[nan]
combined new and old converted values
[nan 'Intersection â€“ Unmarked Crosswalk' 'Intersection â€“ Other'
 'Driveway Access' 'Shoulder/Roadside' 'Intersection â€“ Marked Crosswalk'
 'Midblock â€“ Non-Crosswalk' 'Sidewalk'
 'Other Location (Describe in Narrative)' 'Midblock â€“ Marked Crosswalk'
 'Travel Lane â€“ Other Location' 'Marked Bicycle Lane'
 'Median/Crossing Island' 'Protected Bicycle Lane'
 'Shared-Use Path or Trail']


COLUMN TU-3 NM Location
New values
Old converted values
[nan]
combined new and old converted values
[nan]


COLUMN TU-1 NM Action
New values
[nan 'Cross/Enter NOT at Intersection' 'Cross/Enter at Intersection'
 'Dart/Dash'
 'Traveling Along Roadway With Traffic (In or Adjacent to Travel Lane)'
 'Traveling Along Roadway Against Traffic (In or Adjacent to Travel Lane)'
 'Other (Describe in Narrative)' 'Traveling on Sidewalk Against Traffic'
 'In Roadway Improperly (Standing, Lying, Working, Playing)'
 'Failure to Obey Traffic Signs, Signals, or Officer'
 'No Contributing Action' 'Failure to Yield Right-Of-Way'
 'Improper Turn/Merge' 'Entering/Exiting Parked/Standing Vehicle'
 'Traveling on Sidewalk With Traffic' 'Improper Passing'
 'Disabled Vehicle Related (Working on, Pushing, Leaving, Approaching)'
 'Working in Trafficway (Incident Response)'
 'Working in Trafficway (Maintenance Activities)']
Old converted values
[nan]
combined new and old converted values
[nan 'Cross/Enter NOT at Intersection' 'Cross/Enter at Intersection'
 'Dart/Dash'
 'Traveling Along Roadway With Traffic (In or Adjacent to Travel Lane)'
 'Traveling Along Roadway Against Traffic (In or Adjacent to Travel Lane)'
 'Other (Describe in Narrative)' 'Traveling on Sidewalk Against Traffic'
 'In Roadway Improperly (Standing, Lying, Working, Playing)'
 'Failure to Obey Traffic Signs, Signals, or Officer'
 'No Contributing Action' 'Failure to Yield Right-Of-Way'
 'Improper Turn/Merge' 'Entering/Exiting Parked/Standing Vehicle'
 'Traveling on Sidewalk With Traffic' 'Improper Passing'
 'Disabled Vehicle Related (Working on, Pushing, Leaving, Approaching)'
 'Working in Trafficway (Incident Response)'
 'Working in Trafficway (Maintenance Activities)']


COLUMN TU-2 NM Action
New values
[nan 'No Contributing Action' 'Other (Describe in Narrative)'
 'Traveling on Sidewalk Against Traffic'
 'Traveling Along Roadway Against Traffic (In or Adjacent to Travel Lane)'
 'Cross/Enter at Intersection'
 'Working in Trafficway (Maintenance Activities)'
 'Cross/Enter NOT at Intersection'
 'Failure to Obey Traffic Signs, Signals, or Officer'
 'Traveling Along Roadway With Traffic (In or Adjacent to Travel Lane)'
 'Dart/Dash'
 'Disabled Vehicle Related (Working on, Pushing, Leaving, Approaching)'
 'Entering/Exiting Parked/Standing Vehicle'
 'In Roadway Improperly (Standing, Lying, Working, Playing)'
 'Failure to Yield Right-Of-Way'
 'Working in Trafficway (Incident Response)' 'Soliciting Rides'
 'Improper Turn/Merge' 'Traveling on Sidewalk With Traffic'
 'Improper Passing']
Old converted values
[nan]

In [40]:
# Renamed Columns and mapped - Crash Metadata
renamed_mapped_columns_part1=[
    'Crash Date', 
    'Agency Id',
    'City',
    'County', 
    'Latitude', 
    'Longitude', 
    'Location 1', 
    'Link', 
    'Location 2', 
    'Wild Animal', 
    'Injury 00', 
    'Injury 01',
    'Injury 02', 
    'Injury 03', 
    'Injury 04', 
    'Location',
    'Road Description', 
    'First HE',
    'Second HE', 
    'Third HE', 
    'MHE', 
    'Crash Type',
    'Road Condition', 
    'Lighting Conditions', 
    'Weather Condition',
    'Total Vehicles',
    'System Code',
    'Road Contour Curves', 
    'Road Contour Grade'
]

for column_name in renamed_mapped_columns_part1:
    print('COLUMN', column_name)
    print('New values')
    print(cdot_new_pdf[column_name].unique())
    print('Old converted values')
    print(converted_cdot_old_pdf[column_name].unique())
    print('combined new and old converted values')
    print(combined_cdot_pdf[column_name].unique())
    print()
    print()

COLUMN Crash Date
New values
<DatetimeArray>
['2024-01-01 00:00:00', '2024-01-02 00:00:00', '2024-01-03 00:00:00',
 '2024-01-04 00:00:00', '2024-01-05 00:00:00', '2024-01-06 00:00:00',
 '2024-01-07 00:00:00', '2024-01-08 00:00:00', '2024-01-09 00:00:00',
 '2024-01-10 00:00:00',
 ...
 '2024-12-22 00:00:00', '2024-12-23 00:00:00', '2024-12-24 00:00:00',
 '2024-12-25 00:00:00', '2024-12-26 00:00:00', '2024-12-27 00:00:00',
 '2024-12-28 00:00:00', '2024-12-29 00:00:00', '2024-12-30 00:00:00',
 '2024-12-31 00:00:00']
Length: 366, dtype: datetime64[ns]
Old converted values
<DatetimeArray>
['2020-01-01 00:00:00', '2020-01-02 00:00:00', '2020-01-03 00:00:00',
 '2020-01-04 00:00:00', '2020-01-05 00:00:00', '2020-01-06 00:00:00',
 '2020-01-07 00:00:00', '2020-01-08 00:00:00', '2020-01-09 00:00:00',
 '2020-01-10 00:00:00',
 ...
 '2020-12-22 00:00:00', '2020-12-23 00:00:00', '2020-12-24 00:00:00',
 '2020-12-25 00:00:00', '2020-12-26 00:00:00', '2020-12-27 00:00:00',
 '2020-12-28 00:00:00', '2020-12-29 00:00:00', '2020-12-30 00:00:00',
 '2020-12-31 00:00:00']
Length: 367, dtype: datetime64[ns]
combined new and old converted values
<DatetimeArray>
['2020-01-01 00:00:00', '2020-01-02 00:00:00', '2020-01-03 00:00:00',
 '2020-01-04 00:00:00', '2020-01-05 00:00:00', '2020-01-06 00:00:00',
 '2020-01-07 00:00:00', '2020-01-08 00:00:00', '2020-01-09 00:00:00',
 '2020-01-10 00:00:00',
 ...
 '2024-12-22 00:00:00', '2024-12-23 00:00:00', '2024-12-24 00:00:00',
 '2024-12-25 00:00:00', '2024-12-26 00:00:00', '2024-12-27 00:00:00',
 '2024-12-28 00:00:00', '2024-12-29 00:00:00', '2024-12-30 00:00:00',
 '2024-12-31 00:00:00']
Length: 733, dtype: datetime64[ns]


COLUMN Agency Id
New values
['DPD' 'WRPD' 'BLDPD' 'THPD' 'CSP' 'AURPD' 'CSPD' 'FTCPD' 'LDPS' 'BFPD'
 'GRYPD' 'LPD' 'GJPD' 'LRMSO' 'VPD' 'NPD' 'ARVPD' 'PUPD' 'WLDSO' 'BKPD'
 'WMPD' 'PUSO' 'EVNPD' 'DSO' 'CGPD' 'EZTHPD' 'CMCPD' 'EGLWD PD' 'TNTHPD'
 'LVPD' 'LTPD' 'GDNPD' 'BLDSO' 'LAJTPD' 'GVPD' 'MTPD' 'DGOPD' 'FTMGNPD'
 'ASPD' 'ASO' 'SDPD' 'ESO' 'PPD' 'WDSPD' 'RFLPD' 'JPD' 'SBTSGPD' 'ALPD'
 'FRSPD' 'FDRKPD' 'CNPD' 'CRPD' 'PGSSPPD' 'GNPD' 'BRPD' 'AVPD' 'CHVPD'
 'DLLPD' 'MMTPD' 'DTPD' 'FLPD' 'BPD' 'HPD' 'KMMPD' 'LNTRPD' 'GLWDSPGPD'
 'LUPD' 'EGLSO' 'ISPD' 'MPD' 'LFTTPD' 'FHPD' 'FRSWNTPPD' 'BHPD' 'MTVTAPD'
 'LKSDPD' 'PVPD' 'FNTN PD' 'EPPD' 'LMRPD' 'SUPD' 'SOMPD' 'WTONSO' 'CUSO'
 'ERPD' 'SMVLGPD' 'LKSO' 'SPFLDPD' 'WPPD' 'KYPD' 'SNCEPD' 'CRCKPD' 'PCPD'
 'PSO' 'EDWPD' 'SVPD' 'BRLPD' 'RTTSO' 'GNDLPD' 'MDPD' 'FRSTPD' 'GRBYPD'
 'NCPD' 'CRTPZ' 'LSPD' 'CBPD' 'STPD' 'TRDMO' 'SALPD' 'FTTAPD' 'LCBMO'
 'RDWYPD' 'MTNVWPD' 'SLPD' 'LCBPD' 'BRSPD' 'MVPD' 'DACOPD' 'FLRNCPD'
 'GRNDSO' 'LIPD' 'JKSNSO' 'MKRPD' 'ATPD' 'GLPNSO' 'ADSO' 'YPD' nan 'BVPD'
 'EPD' 'UCPDHSC' 'PAPD' 'PLSDPD' 'MNTUSPPD' 'HTKSSPD' 'KWSO' 'CPD' 'HXTPD'
 'ORYPD' 'BTSO' 'LDVLPD' 'WPD' 'BLRPD' 'HYDPD' 'RFPD' 'PPCCPD' 'BAFPD'
 'OKCRKPD' 'RBSO' 'EMPREPD' 'SSO' 'FRMTSO' 'OTHPD' 'HDSPD' 'NUNNPD' 'KBPD'
 'ARAPD' 'HGMO' 'CSUPD' 'HRFNSO' 'FPYPD' 'MFFTSO' 'LSANSO' 'GNMTNFLMO'
 'CALPD' 'MTZMASO' 'BNPD' 'ARCCPD' 'CDPD' 'HDLSO' 'ALSO' 'JSO' 'WKNPD'
 'PLPD' 'SJSO' 'FWLRPD' 'CDPPAR' 'IGNCPD' 'CDW' 'OTRSO' 'LCNSO' 'BTPD'
 'TLLSO' 'DEBQPD' 'FLWSCPD' 'ADSDPS']
Old converted values
['CSP' 'EGLSO' 'ASO' 'DPD' 'THPD' 'PUSO' 'CSPD' 'BFPD' 'DLLPD' 'AURPD'
 'PUPD' 'ARVPD' 'WLDSO' 'LAJTPD' 'LDPS' 'GRYPD' 'CMCPD' 'FRSTPD' 'CGPD'
 'MNTUSPPD' 'JPD' 'GLWDSPGPD' 'EGLPD' 'GJPD' 'BLDPD' 'LNTRPD' 'BKPD'
 'LCBMO' 'FRSWNTPPD' 'SMVLGPD' 'AVPD' 'LTPD' 'SBTSGPD' 'MMTPD' 'LVPD'
 'SNFDPD' 'FTCPD' 'CNPD' 'SDPD' 'BRPD' 'NPD' 'SPRRPD' 'FTMGNPD' 'WRPD'
 'VPD' 'LPD' 'SVPD' 'WMPD' 'PSO' 'PPD' 'FHPD' 'WPPD' 'DSO' 'LRMSO' 'EVNPD'
 'DTPD' 'BHPD' 'GVPD' 'EGLWD PD' 'MTPD' 'ASPD' 'BNPD' 'DGOPD' 'ALPD'
 'EPPD' 'PGSSPPD' 'FNTN PD' 'LUPD' 'TPD' 'CRTPZ' 'CHVPD' 'ISPD' 'ESO'
 'WGGPD' 'STPD' 'CRPD' 'LDVLPD' 'GNPD' 'FDRKPD' 'HTKSSMO' 'GRNDSO'
 'GNDLPD' 'WDSPD' 'SUPD' 'LMRPD' 'SJSO' 'GDNPD' 'CUSO' 'CRCKPD' 'FLPD'
 'FRSPD' 'LRKSPPD' 'EDWPD' 'MPD' 'TNTHPD' 'NCPD' 'ERPD' 'BLDSO' 'LKSO'
 'MTNVWPD' 'MRRSNPD' 'MDPD' 'PVPD' nan 'LKSDPD' 'BPD' 'CDPPMTRS' 'HGMO'
 'MTVTAPD' 'KYPD' 'FTTAPD' 'ATPD' 'SNCEPD' 'BAMO' 'BTPD' 'WPKPD' 'RFLPD'
 'SPFLDPD' 'SLPD' 'JKSNSO' 'LSPD' 'RFPD' 'GRBYPD' 'CDPD' 'UCMCPD' 'PCPD'
 'BRSPD' 'MTZMASO' 'NDLDPD' 'CPD' 'EPD' 'PWRSO' 'RTTSO' 'MTCBMO' 'WTONSO'
 'LCBPD' 'CNTPD' 'MVPD' 'HYDPD' 'TLLSO' 'TRDMO' 'CBNVPD' 'ORYPD' 'EZTHPD'
 'RDWYPD' 'CSUPD' 'LFTTPD' 'GLPNSO' 'FTCSNPD' 'WPD' 'HTSPSPD' 'OKCRKPD'
 'GDLKEPD' 'MTCBPD' 'CDPPELT' 'FLWSCPD' 'YPD' 'PLSDPD' 'PGSALKPD' 'SWKSO'
 'CRWLSO' 'CALPD' 'SOMPD' 'HPD' 'HXTPD' 'CTRPD' 'HRFNSO' 'UCBPD' 'BDPD'
 'HDLSO' 'CBMO' 'BRLPD' 'PKSO' 'TRDPD' 'GRGTNPD' 'OTHPD' 'BVPD' 'NUNNPD'
 'CTLSO' 'CBPD' 'DACOPD' 'SALPD' 'DLTPD' 'GDNCTPD' 'WLLPD' 'FWLRPD'
 'FRMTSO' 'IGNCPD' 'LGLNPD' 'DNVSO' 'EMPREPD' 'MKRPD' 'PKNPD' 'LSANSO'
 'YSO' 'ALSO' 'UCPDHSC' 'FLRNCPD' 'KBPD' 'ARAPD' 'LYNPD' 'CBNPD' 'MFFTSO'
 'KMMPD' 'RPD' 'KWSO']
combined new and old converted values
['CSP' 'EGLSO' 'ASO' 'DPD' 'THPD' 'PUSO' 'CSPD' 'BFPD' 'DLLPD' 'AURPD'
 'PUPD' 'ARVPD' 'WLDSO' 'LAJTPD' 'LDPS' 'GRYPD' 'CMCPD' 'FRSTPD' 'CGPD'
 'MNTUSPPD' 'JPD' 'GLWDSPGPD' 'EGLPD' 'GJPD' 'BLDPD' 'LNTRPD' 'BKPD'
 'LCBMO' 'FRSWNTPPD' 'SMVLGPD' 'AVPD' 'LTPD' 'SBTSGPD' 'MMTPD' 'LVPD'
 'SNFDPD' 'FTCPD' 'CNPD' 'SDPD' 'BRPD' 'NPD' 'SPRRPD' 'FTMGNPD' 'WRPD'
 'VPD' 'LPD' 'SVPD' 'WMPD' 'PSO' 'PPD' 'FHPD' 'WPPD' 'DSO' 'LRMSO' 'EVNPD'
 'DTPD' 'BHPD' 'GVPD' 'EGLWD PD' 'MTPD' 'ASPD' 'BNPD' 'DGOPD' 'ALPD'
 'EPPD' 'PGSSPPD' 'FNTN PD' 'LUPD' 'TPD' 'CRTPZ' 'CHVPD' 'ISPD' 'ESO'
 'WGGPD' 'STPD' 'CRPD' 'LDVLPD' 'GNPD' 'FDRKPD' 'HTKSSMO' 'GRNDSO'
 'GNDLPD' 'WDSPD' 'SUPD' 'LMRPD' 'SJSO' 'GDNPD' 'CUSO' 'CRCKPD' 'FLPD'
 'FRSPD' 'LRKSPPD' 'EDWPD' 'MPD' 'TNTHPD' 'NCPD' 'ERPD' 'BLDSO' 'LKSO'
 'MTNVWPD' 'MRRSNPD' 'MDPD' 'PVPD' nan 'LKSDPD' 'BPD' 'CDPPMTRS' 'HGMO'
 'MTVTAPD' 'KYPD' 'FTTAPD' 'ATPD' 'SNCEPD' 'BAMO' 'BTPD' 'WPKPD' 'RFLPD'
 'SPFLDPD' 'SLPD' 'JKSNSO' 'LSPD' 'RFPD' 'GRBYPD' 'CDPD' 'UCMCPD' 'PCPD'
 'BRSPD' 'MTZMASO' 'NDLDPD' 'CPD' 'EPD' 'PWRSO' 'RTTSO' 'MTCBMO' 'WTONSO'
 'LCBPD' 'CNTPD' 'MVPD' 'HYDPD' 'TLLSO' 'TRDMO' 'CBNVPD' 'ORYPD' 'EZTHPD'
 'RDWYPD' 'CSUPD' 'LFTTPD' 'GLPNSO' 'FTCSNPD' 'WPD' 'HTSPSPD' 'OKCRKPD'
 'GDLKEPD' 'MTCBPD' 'CDPPELT' 'FLWSCPD' 'YPD' 'PLSDPD' 'PGSALKPD' 'SWKSO'
 'CRWLSO' 'CALPD' 'SOMPD' 'HPD' 'HXTPD' 'CTRPD' 'HRFNSO' 'UCBPD' 'BDPD'
 'HDLSO' 'CBMO' 'BRLPD' 'PKSO' 'TRDPD' 'GRGTNPD' 'OTHPD' 'BVPD' 'NUNNPD'
 'CTLSO' 'CBPD' 'DACOPD' 'SALPD' 'DLTPD' 'GDNCTPD' 'WLLPD' 'FWLRPD'
 'FRMTSO' 'IGNCPD' 'LGLNPD' 'DNVSO' 'EMPREPD' 'MKRPD' 'PKNPD' 'LSANSO'
 'YSO' 'ALSO' 'UCPDHSC' 'FLRNCPD' 'KBPD' 'ARAPD' 'LYNPD' 'CBNPD' 'MFFTSO'
 'KMMPD' 'RPD' 'KWSO' 'LIPD' 'ADSO' 'PAPD' 'HTKSSPD' 'BTSO' 'BLRPD'
 'PPCCPD' 'BAFPD' 'RBSO' 'SSO' 'HDSPD' 'FPYPD' 'GNMTNFLMO' 'ARCCPD' 'JSO'
 'WKNPD' 'PLPD' 'CDPPAR' 'CDW' 'OTRSO' 'LCNSO' 'DEBQPD' 'ADSDPS']


COLUMN City
New values
['DENVER' 'WHEAT RIDGE' 'BOULDER' 'THORNTON' nan 'AURORA'
 'COLORADO SPRINGS' 'FORT COLLINS' 'LONGMONT' 'BROOMFIELD' 'GREELEY'
 'LAKEWOOD' 'GRAND JUNCTION' 'BERTHOUD' 'VAIL' 'NORTHGLENN' 'ARVADA'
 'PUEBLO' 'KERSEY' 'BRECKENRIDGE' 'WESTMINSTER' 'EVANS' 'CRAIG'
 'ELIZABETH' 'COMMERCE CITY' 'PAGOSA SPRINGS' 'ENGLEWOOD' 'AULT' 'TIMNATH'
 'LOVELAND' 'LITTLETON' 'GOLDEN' 'LYONS' 'LA JUNTA' 'GREENWOOD VILLAGE'
 'CRESTED BUTTE' 'MONTROSE' 'DURANGO' 'FORT MORGAN' 'ASPEN' 'CENTENNIAL'
 'SHERIDAN' 'ELBERT' 'PARKER' 'WINDSOR' 'DEER TRAIL' 'RIFLE' 'JOHNSTOWN'
 'STEAMBOAT SPRINGS' 'ALAMOSA' 'FRISCO' 'FREDERICK' 'CANON CITY'
 'PUEBLO WEST' 'CASTLE ROCK' 'GUNNISON' 'BRIGHTON' 'AVON'
 'CHERRY HILLS VILLAGE' 'DILLON' 'MONUMENT' 'DELTA' 'FORT LUPTON' 'BASALT'
 'HOLYOKE' 'KREMMLING' 'LONE TREE' 'GLENWOOD SPRINGS' 'LOUISVILLE'
 'IDAHO SPRINGS' 'MILLIKEN' 'LAFAYETTE' 'FEDERAL HEIGHTS' 'FRASER'
 'BLACK HAWK' 'MONTE VISTA' 'LAKESIDE' 'FOUNTAIN' 'ESTES PARK' 'LAMAR'
 'OTIS' 'SILVER CLIFF' 'ERIE' 'FORT CARSON' 'SNOWMASS VILLAGE'
 'SPRINGFIELD' 'WOODLAND PARK' 'SEVERANCE' 'CRIPPLE CREEK' 'SUPERIOR'
 'WINTER PARK' 'PLATTEVILLE' 'PARACHUTE' 'EDGEWATER' 'SILVERTHORNE'
 'BURLINGTON' 'TWIN LAKES' 'IGNACIO' 'HERMOSA' 'GLENDALE' 'MEAD'
 'FIRESTONE' 'GRANBY' 'NEW CASTLE' 'CORTEZ' 'LEADVILLE' 'LA SALLE'
 'BLANCA' 'STERLING' 'TELLURIDE' 'PORTLAND' 'HUDSON' 'SALIDA' 'ARAPAHOE'
 'FRUITA' 'NEDERLAND' 'WALSENBURG' 'HAYDEN' 'RIDGWAY' 'MOUNTAIN VIEW'
 'WIDEFIELD' 'SILT' 'LOCHBUIE' 'BRUSH' 'MOUNTAIN VILLAGE' 'DACONO'
 'FLORENCE' 'VICTOR' 'LIMON' 'RAND' 'MEEKER' 'PIERCE' 'CENTRAL CITY'
 'BENNETT' 'EATON' 'GILCREST' 'YUMA' 'BUENA VISTA' 'AVONDALE' 'PAONIA'
 'PALISADE' 'MANITOU SPRINGS' 'CARBONDALE' 'GYPSUM' 'FAIRPLAY' 'HOTCHKISS'
 'EADS' 'HAXTUN' 'AKRON' 'OURAY' 'KEYSTONE' 'FOXFIELD' 'COALMONT'
 'LAS ANIMAS' 'WALDEN' 'BOONE' 'EVERGREEN' 'WRAY' 'MESA' 'BLUE RIVER'
 'ROCKY FORD' 'DIVIDE' 'HIGHLANDS RANCH' 'WELBY' 'BAILEY' 'BAYFIELD'
 'OAK CREEK' 'CASTLE PINES' 'JULESBURG' 'GREEN MOUNTAIN FALLS' 'EMPIRE'
 'ROGGEN' 'MORRISON' 'ORCHARD CITY' 'STRASBURG' 'HOT SULPHUR SPRINGS'
 'BLACK FOREST' 'OLATHE' 'RAMAH' 'SNOWMASS' 'CIMARRON' 'NUNN' 'KEENESBURG'
 'EDWARDS' 'COWDREY' 'LARKSPUR' 'PEYTON' 'HUGO' 'FRANKTOWN' 'LOUVIERS'
 'GOULD' 'COLUMBINE' 'TRINIDAD' 'MOFFAT' 'GRAND LAKE' 'LUCERNE' 'MINTURN'
 'WELLINGTON' 'COLORADO CITY' 'MANCOS' 'CALHAN' 'LA VETA' 'DOLORES'
 'ARBOLES' 'CEDAREDGE' 'HOLLY' 'MONTEZUMA' 'HESPERUS' 'LAKE CITY'
 'ALLISON' 'CONIFER' 'ROMEO' 'BATTLEMENT MESA' 'FOWLER' 'PALMER LAKE'
 'COAL CREEK' 'DOTSERO' 'HENDERSON' 'SILVER PLUME' 'ORCHARD' 'YAMPA'
 'PINE' 'ALLENSPARK' 'NEW RAYMER' 'GILL' 'DE BEQUE' 'BEULAH' 'SILVERTON'
 'PENROSE' 'DECKERS' 'INDIAN HILLS' 'KITTREDGE' 'OVID' 'FLORISSANT'
 'WATKINS' 'ASPEN PARK' 'DEL NORTE']
Old converted values
[nan 'GYPSUM' 'CENTENNIAL' 'DENVER' 'THORNTON' 'PUEBLO' 'COLORADO SPRINGS'
 'BROOMFIELD' 'DILLON' 'AURORA' 'ARVADA' 'LA JUNTA' 'LONGMONT' 'GREELEY'
 'COMMERCE CITY' 'FIRESTONE' 'CRAIG' 'MANITOU SPRINGS' 'JOHNSTOWN' 'RIFLE'
 'GLENWOOD SPRINGS' 'EAGLE' 'GRAND JUNCTION' 'BOULDER' 'LONE TREE'
 'BRECKENRIDGE' 'LOCHBUIE' 'WINTER PARK' 'SNOWMASS VILLAGE' 'AVON'
 'LITTLETON' 'CLIFTON' 'STEAMBOAT SPRINGS' 'MONUMENT' 'LOVELAND' 'SANFORD'
 'FORT COLLINS' 'CANON CITY' 'SHERIDAN' 'BRIGHTON' 'NORTHGLENN' 'SUPERIOR'
 'FORT MORGAN' 'VAIL' 'LAKEWOOD' 'SILVERTHORNE' 'WESTMINSTER' 'PARKER'
 'FEDERAL HEIGHTS' 'WHEAT RIDGE' 'WOODLAND PARK' 'BERTHOUD' 'EVANS'
 'DELTA' 'BLACK HAWK' 'GREENWOOD VILLAGE' 'ENGLEWOOD' 'ASPEN' 'MONTROSE'
 'BLANCA' 'DURANGO' 'ALAMOSA' 'ESTES PARK' 'PAGOSA SPRINGS' 'FOUNTAIN'
 'LOUISVILLE' 'TRINIDAD' 'CORTEZ' 'CHERRY HILLS VILLAGE' 'PUEBLO WEST'
 'IDAHO SPRINGS' 'ELBERT' 'WIGGINS' 'STERLING' 'CASTLE ROCK' 'LEADVILLE'
 'GUNNISON' 'FREDERICK' 'FRISCO' 'HOTCHKISS' 'GRAND LAKE' 'GLENDALE'
 'WINDSOR' 'IGNACIO' 'KIOWA' 'PALISADE' 'LAMAR' 'ERIE' 'LOMA' 'SILVERTON'
 'GOLDEN' 'FRUITVALE' 'WESTCLIFFE' 'KREMMLING' 'CRIPPLE CREEK'
 'FORT LUPTON' 'GEORGETOWN' 'MEAD' 'CONIFER' 'GRANBY' 'EDGEWATER'
 'MILLIKEN' 'TIMNATH' 'NEW CASTLE' 'ELIZABETH' 'LA SALLE' 'MEEKER'
 'TWIN LAKES' 'MOUNTAIN VIEW' 'MORRISON' 'PLATTEVILLE' 'WELLINGTON'
 'BLUE RIVER' 'LAKESIDE' 'BASALT' 'HUGO' 'MONTE VISTA' 'KERSEY' 'DACONO'
 'BRIGGSDALE' 'ADAMS CITY' 'BAYFIELD' 'SEVERANCE' 'FRUITA' 'PIERCE'
 'HUDSON' 'RIDGWAY' 'SPRINGFIELD' 'EVERGREEN' 'ORCHARD CITY' 'SILT'
 'COWDREY' 'SNOWMASS' 'ROCKY FORD' 'WALDEN' 'NUNN' 'DINOSAUR' 'CEDAREDGE'
 'MILNER' 'PARACHUTE' 'BRUSH' 'DOLORES' 'NEDERLAND' 'CAMPO' 'MINTURN'
 'CARBONDALE' 'EATON' 'GILCREST' 'ARAPAHOE' 'CRESTED BUTTE' 'AGATE'
 'PALMER LAKE' 'AKRON' 'MOUNTAIN VILLAGE' 'OURAY' 'DOTSERO' 'HAYDEN'
 'VICTOR' 'TELLURIDE' 'AULT' 'COLUMBINE VALLEY' 'CALHAN' 'LIMON'
 'COLUMBINE' 'SIMLA' 'SWINK' 'BUENA VISTA' 'NIWOT' 'BEULAH' 'LAFAYETTE'
 'CENTRAL CITY' 'WRAY' 'HOT SULPHUR SPRINGS' 'EDWARDS' 'RAND' 'LAPORTE'
 'YAMPA' 'KEENESBURG' 'HIGHLANDS RANCH' 'OAK CREEK' 'FRASER' 'FAIRPLAY'
 'RYE' 'PEYTON' 'FOXFIELD' 'DEER TRAIL' 'YUMA' 'YODER' 'JULESBURG'
 'KIT CARSON' 'FLORISSANT' 'ORDWAY' 'BOONE' 'STRASBURG' 'RED CLIFF'
 'WILEY' 'PENROSE' 'JEFFERSON' 'HOLYOKE' 'WALSENBURG' 'AGUILAR' 'LUCERNE'
 'HAXTUN' 'CENTER' 'LAKE CITY' 'BYERS' 'MATHESON' 'PONCHA SPRINGS'
 'BURLINGTON' 'CLARK' 'NUCLA' 'WALSH' 'HARTSEL' 'OLATHE' 'MANCOS'
 'WETMORE' 'LIVERMORE' 'SAN LUIS' 'COLORADO CITY' 'LYONS' 'SEDALIA'
 'FLORENCE' 'FORT GARLAND' 'SILVER PLUME' 'SALIDA' 'CRAWFORD' 'SEDGWICK'
 'GARDEN CITY' 'CRESTONE' 'CIMARRON' 'RAMAH' 'FOWLER' 'GLADE PARK'
 'CROWLEY' 'BAILEY' 'SOUTH FORK' 'LOG LANE VILLAGE' 'COPPER MOUNTAIN'
 'DRAKE' 'PITKIN' 'HENDERSON' 'GOULD' 'UNKNOWN CITY NAME' 'BENNETT'
 'MOFFAT' 'ECKLEY' 'EMPIRE' 'SILVER CLIFF' 'JAMESTOWN' 'PHIPPSBURG'
 'AUSTIN' 'DIVIDE' 'BOW MAR' 'LARKSPUR' 'BETHUNE' 'OLNEY SPRINGS'
 'SUGAR CITY' 'GALETON' 'ALMA' 'VERNON' 'TABERNASH' 'ARBOLES' 'EL JEBEL'
 'AVONDALE' 'ALLISON' 'HESPERUS' 'ROCKVALE' 'ECKERT' 'KITTREDGE' 'RANGELY'
 'HASWELL' 'LA VETA' 'FRANKTOWN' 'FLEMING' 'PINE']
combined new and old converted values
[nan 'GYPSUM' 'CENTENNIAL' 'DENVER' 'THORNTON' 'PUEBLO' 'COLORADO SPRINGS'
 'BROOMFIELD' 'DILLON' 'AURORA' 'ARVADA' 'LA JUNTA' 'LONGMONT' 'GREELEY'
 'COMMERCE CITY' 'FIRESTONE' 'CRAIG' 'MANITOU SPRINGS' 'JOHNSTOWN' 'RIFLE'
 'GLENWOOD SPRINGS' 'EAGLE' 'GRAND JUNCTION' 'BOULDER' 'LONE TREE'
 'BRECKENRIDGE' 'LOCHBUIE' 'WINTER PARK' 'SNOWMASS VILLAGE' 'AVON'
 'LITTLETON' 'CLIFTON' 'STEAMBOAT SPRINGS' 'MONUMENT' 'LOVELAND' 'SANFORD'
 'FORT COLLINS' 'CANON CITY' 'SHERIDAN' 'BRIGHTON' 'NORTHGLENN' 'SUPERIOR'
 'FORT MORGAN' 'VAIL' 'LAKEWOOD' 'SILVERTHORNE' 'WESTMINSTER' 'PARKER'
 'FEDERAL HEIGHTS' 'WHEAT RIDGE' 'WOODLAND PARK' 'BERTHOUD' 'EVANS'
 'DELTA' 'BLACK HAWK' 'GREENWOOD VILLAGE' 'ENGLEWOOD' 'ASPEN' 'MONTROSE'
 'BLANCA' 'DURANGO' 'ALAMOSA' 'ESTES PARK' 'PAGOSA SPRINGS' 'FOUNTAIN'
 'LOUISVILLE' 'TRINIDAD' 'CORTEZ' 'CHERRY HILLS VILLAGE' 'PUEBLO WEST'
 'IDAHO SPRINGS' 'ELBERT' 'WIGGINS' 'STERLING' 'CASTLE ROCK' 'LEADVILLE'
 'GUNNISON' 'FREDERICK' 'FRISCO' 'HOTCHKISS' 'GRAND LAKE' 'GLENDALE'
 'WINDSOR' 'IGNACIO' 'KIOWA' 'PALISADE' 'LAMAR' 'ERIE' 'LOMA' 'SILVERTON'
 'GOLDEN' 'FRUITVALE' 'WESTCLIFFE' 'KREMMLING' 'CRIPPLE CREEK'
 'FORT LUPTON' 'GEORGETOWN' 'MEAD' 'CONIFER' 'GRANBY' 'EDGEWATER'
 'MILLIKEN' 'TIMNATH' 'NEW CASTLE' 'ELIZABETH' 'LA SALLE' 'MEEKER'
 'TWIN LAKES' 'MOUNTAIN VIEW' 'MORRISON' 'PLATTEVILLE' 'WELLINGTON'
 'BLUE RIVER' 'LAKESIDE' 'BASALT' 'HUGO' 'MONTE VISTA' 'KERSEY' 'DACONO'
 'BRIGGSDALE' 'ADAMS CITY' 'BAYFIELD' 'SEVERANCE' 'FRUITA' 'PIERCE'
 'HUDSON' 'RIDGWAY' 'SPRINGFIELD' 'EVERGREEN' 'ORCHARD CITY' 'SILT'
 'COWDREY' 'SNOWMASS' 'ROCKY FORD' 'WALDEN' 'NUNN' 'DINOSAUR' 'CEDAREDGE'
 'MILNER' 'PARACHUTE' 'BRUSH' 'DOLORES' 'NEDERLAND' 'CAMPO' 'MINTURN'
 'CARBONDALE' 'EATON' 'GILCREST' 'ARAPAHOE' 'CRESTED BUTTE' 'AGATE'
 'PALMER LAKE' 'AKRON' 'MOUNTAIN VILLAGE' 'OURAY' 'DOTSERO' 'HAYDEN'
 'VICTOR' 'TELLURIDE' 'AULT' 'COLUMBINE VALLEY' 'CALHAN' 'LIMON'
 'COLUMBINE' 'SIMLA' 'SWINK' 'BUENA VISTA' 'NIWOT' 'BEULAH' 'LAFAYETTE'
 'CENTRAL CITY' 'WRAY' 'HOT SULPHUR SPRINGS' 'EDWARDS' 'RAND' 'LAPORTE'
 'YAMPA' 'KEENESBURG' 'HIGHLANDS RANCH' 'OAK CREEK' 'FRASER' 'FAIRPLAY'
 'RYE' 'PEYTON' 'FOXFIELD' 'DEER TRAIL' 'YUMA' 'YODER' 'JULESBURG'
 'KIT CARSON' 'FLORISSANT' 'ORDWAY' 'BOONE' 'STRASBURG' 'RED CLIFF'
 'WILEY' 'PENROSE' 'JEFFERSON' 'HOLYOKE' 'WALSENBURG' 'AGUILAR' 'LUCERNE'
 'HAXTUN' 'CENTER' 'LAKE CITY' 'BYERS' 'MATHESON' 'PONCHA SPRINGS'
 'BURLINGTON' 'CLARK' 'NUCLA' 'WALSH' 'HARTSEL' 'OLATHE' 'MANCOS'
 'WETMORE' 'LIVERMORE' 'SAN LUIS' 'COLORADO CITY' 'LYONS' 'SEDALIA'
 'FLORENCE' 'FORT GARLAND' 'SILVER PLUME' 'SALIDA' 'CRAWFORD' 'SEDGWICK'
 'GARDEN CITY' 'CRESTONE' 'CIMARRON' 'RAMAH' 'FOWLER' 'GLADE PARK'
 'CROWLEY' 'BAILEY' 'SOUTH FORK' 'LOG LANE VILLAGE' 'COPPER MOUNTAIN'
 'DRAKE' 'PITKIN' 'HENDERSON' 'GOULD' 'UNKNOWN CITY NAME' 'BENNETT'
 'MOFFAT' 'ECKLEY' 'EMPIRE' 'SILVER CLIFF' 'JAMESTOWN' 'PHIPPSBURG'
 'AUSTIN' 'DIVIDE' 'BOW MAR' 'LARKSPUR' 'BETHUNE' 'OLNEY SPRINGS'
 'SUGAR CITY' 'GALETON' 'ALMA' 'VERNON' 'TABERNASH' 'ARBOLES' 'EL JEBEL'
 'AVONDALE' 'ALLISON' 'HESPERUS' 'ROCKVALE' 'ECKERT' 'KITTREDGE' 'RANGELY'
 'HASWELL' 'LA VETA' 'FRANKTOWN' 'FLEMING' 'PINE' 'OTIS' 'FORT CARSON'
 'HERMOSA' 'PORTLAND' 'WIDEFIELD' 'PAONIA' 'EADS' 'KEYSTONE' 'COALMONT'
 'LAS ANIMAS' 'MESA' 'WELBY' 'CASTLE PINES' 'GREEN MOUNTAIN FALLS'
 'ROGGEN' 'BLACK FOREST' 'LOUVIERS' 'HOLLY' 'MONTEZUMA' 'ROMEO'
 'BATTLEMENT MESA' 'COAL CREEK' 'ORCHARD' 'ALLENSPARK' 'NEW RAYMER' 'GILL'
 'DE BEQUE' 'DECKERS' 'INDIAN HILLS' 'OVID' 'WATKINS' 'ASPEN PARK'
 'DEL NORTE']


COLUMN County
New values
['DENVER' 'JEFFERSON' 'BOULDER' 'ADAMS' 'PITKIN' 'WELD' 'ARAPAHOE'
 'EL PASO' 'LARIMER' 'BROOMFIELD' 'PUEBLO' 'MESA' 'EAGLE' 'SUMMIT'
 'DOUGLAS' 'MOFFAT' 'COSTILLA' 'TELLER' 'ELBERT' 'KIT CARSON' 'ARCHULETA'
 'HUERFANO' 'CLEAR CREEK' 'GRAND' 'OTERO' 'PARK' 'GUNNISON' 'MONTROSE'
 'LA PLATA' 'MORGAN' 'LOGAN' 'GARFIELD' 'ROUTT' 'ALAMOSA' 'FREMONT'
 'MONTEZUMA' 'LAS ANIMAS' 'LINCOLN' 'BENT' 'DELTA' 'WASHINGTON' 'PHILLIPS'
 'RIO GRANDE' 'GILPIN' 'SAGUACHE' 'SAN MIGUEL' 'PROWERS' 'YUMA' 'OURAY'
 'BACA' 'CHEYENNE' 'CUSTER' 'LAKE' 'KIOWA' 'CHAFFEE' 'RIO BLANCO'
 'CONEJOS' 'JACKSON' 'DOLORES' 'MINERAL' 'SAN JUAN' 'SEDGWICK' 'CROWLEY'
 'HINSDALE' nan]
Old converted values
['MESA' 'EAGLE' 'ARCHULETA' 'ARAPAHOE' 'DENVER' 'ADAMS' 'WELD' 'PUEBLO'
 'EL PASO' 'BROOMFIELD' 'SUMMIT' 'JEFFERSON' 'OTERO' 'MONTEZUMA' 'BOULDER'
 'LARIMER' 'ALAMOSA' 'WASHINGTON' 'KIT CARSON' 'OURAY' 'RIO BLANCO'
 'MOFFAT' 'CLEAR CREEK' 'GRAND' 'GARFIELD' 'ROUTT' 'MONTROSE' 'DOUGLAS'
 'GUNNISON' 'DELTA' 'PITKIN' 'YUMA' 'CHAFFEE' 'SAN MIGUEL' 'CONEJOS'
 'PARK' 'FREMONT' 'JACKSON' 'MORGAN' 'HUERFANO' 'LA PLATA' 'LAS ANIMAS'
 'TELLER' 'BACA' 'PHILLIPS' 'CHEYENNE' 'GILPIN' 'COSTILLA' 'LOGAN' 'BENT'
 'ELBERT' 'RIO GRANDE' 'PROWERS' 'SAN JUAN' 'SAGUACHE' 'CUSTER' 'LINCOLN'
 'SEDGWICK' 'LAKE' 'KIOWA' 'DOLORES' 'CROWLEY' nan 'MINERAL' 'HINSDALE']
combined new and old converted values
['MESA' 'EAGLE' 'ARCHULETA' 'ARAPAHOE' 'DENVER' 'ADAMS' 'WELD' 'PUEBLO'
 'EL PASO' 'BROOMFIELD' 'SUMMIT' 'JEFFERSON' 'OTERO' 'MONTEZUMA' 'BOULDER'
 'LARIMER' 'ALAMOSA' 'WASHINGTON' 'KIT CARSON' 'OURAY' 'RIO BLANCO'
 'MOFFAT' 'CLEAR CREEK' 'GRAND' 'GARFIELD' 'ROUTT' 'MONTROSE' 'DOUGLAS'
 'GUNNISON' 'DELTA' 'PITKIN' 'YUMA' 'CHAFFEE' 'SAN MIGUEL' 'CONEJOS'
 'PARK' 'FREMONT' 'JACKSON' 'MORGAN' 'HUERFANO' 'LA PLATA' 'LAS ANIMAS'
 'TELLER' 'BACA' 'PHILLIPS' 'CHEYENNE' 'GILPIN' 'COSTILLA' 'LOGAN' 'BENT'
 'ELBERT' 'RIO GRANDE' 'PROWERS' 'SAN JUAN' 'SAGUACHE' 'CUSTER' 'LINCOLN'
 'SEDGWICK' 'LAKE' 'KIOWA' 'DOLORES' 'CROWLEY' nan 'MINERAL' 'HINSDALE']


COLUMN Latitude
New values
[39.73687 39.76933 39.98818 ... 39.87912 40.0449  40.0927 ]
Old converted values
[ 0.       37.204663 39.57856  ... 39.6959   39.7221   38.74007 ]
combined new and old converted values
[ 0.       37.204663 39.57856  ... 39.87912  40.0449   40.0927  ]


COLUMN Longitude
New values
[-104.99869 -105.10966 -105.25394 ... -104.97152 -104.4344  -104.361  ]
Old converted values
[   0.       -107.329465 -104.8071   ... -105.474113 -104.847189
 -104.62466 ]
combined new and old converted values
[   0.       -107.329465 -104.8071   ... -104.97152  -104.4344
 -104.361   ]


COLUMN Location 1
New values
['N SANTA FE DR' 'W 38TH AVE' 'BROADWAY' ... '4000 BLK W COLFAX AVE'
 '2200 BLOCK N FEDERAL BLVD' 'E 100TH LN']
Old converted values
['SYCAMORE CT' 'NIGHTHAWK CIR' 'HWY 160' ... 'PEORIA ST (3800 BLK N)'
 'CHERRY CREEK N DR' 'GRAND CR 8']
combined new and old converted values
['SYCAMORE CT' 'NIGHTHAWK CIR' 'HWY 160' ... '4000 BLK W COLFAX AVE'
 '2200 BLOCK N FEDERAL BLVD' 'E 100TH LN']


COLUMN Link
New values
['AT' '00201FS' '00200FS' ... '0.39MW' '01092FW' '00926FN']
Old converted values
['00650FN' 'AT' '00528FE' ... '00921FN' '00483FN' '00570FE']
combined new and old converted values
['00650FN' 'AT' '00528FE' ... '0.39MW' '01092FW' '00926FN']


COLUMN Location 2
New values
['W 13TH AVE' 'KIPLING ST' 'EASTMAN AVE' ... 'DURASNO DR' 'S MORRISON RD'
 'WELD COUNTY ROAD 22']
Old converted values
['WELLINGTON AVE' '41 NIGHTHAWK CIR' 'MM 123' ... '48TH AVE (OVERPASS)'
 'WAPITI DR' 'E LAMPREY DR']
combined new and old converted values
['WELLINGTON AVE' '41 NIGHTHAWK CIR' 'MM 123' ... 'DURASNO DR'
 'S MORRISON RD' 'WELD COUNTY ROAD 22']


COLUMN Wild Animal
New values

In [38]:
# Renamed Columns and mapped - Traffic Units
renamed_mapped_columns_part2=[
    'TU-1 Type', 
    'TU-2 Type', 
    'TU-3 Type', 
    'TU-1 Direction', 
    'TU-2 Direction', 
    'TU-3 Direction', 
    'TU-1 Movement', 
    'TU-2 Movement', 
    'TU-3 Movement', 
    'TU-1 Hit And Run', 
    'TU-2 Hit And Run', 
    'TU-3 Hit And Run', 
    'TU-1 Speed Limit', 
    'TU-2 Speed Limit', 
    'TU-3 Speed Limit', 
    'TU-1 Estimated Speed', 
    'TU-2 Estimated Speed', 
    'TU-3 Estimated Speed', 
    'TU-1 Human Contributing Factor', 
    'TU-2 Human Contributing Factor', 
    'TU-3 Human Contributing Factor', 
    'TU-1 Age', 
    'TU-2 Age', 
    'TU-3 Age', 
    'TU-1 Sex ', 
    'TU-2 Sex', 
    'TU-3 Sex', 
    'TU-1 Safety restraint Use', 
    'TU-2 Safety restraint Use', 
    'TU-3 Safety restraint Use', 
    'TU-1 Safety Helmet', 
    'TU-2  Safety Helmet', 
    'TU-3 Safety Helmet', 
    'TU-1 Alcohol Suspected', 
    'TU-2 Alcohol Suspected', 
    'TU-3 Alcohol Suspected', 
    'TU-1  Marijuana Suspected', 
    'TU-2 Marijuana Suspected', 
    'TU-3 Marijuana Suspected', 
    'TU-1 Other Drugs Suspected ', 
    'TU-2 Other Drugs Suspected ', 
    'TU-3 Other Drugs Suspected ', 
    'TU-1 NM Direction', 
    'TU-2 NM Direction', 
    'TU-3 NM Direction', 
    'TU-1 NM Movement', 
    'TU-2 NM Movement', 
    'TU-3 NM Movement', 
    'TU-1 NM Type', 
    'TU-2 NM Type', 
    'TU-3 NM Type', 
    'TU-1 NM Age ', 
    'TU-2 NM Age ', 
    'TU-3 NM Age ', 
    'TU-1 NM Sex ', 
    'TU-2 NM Sex ', 
    'TU-3 NM Sex ', 
    'TU-1 NM Human Contributing Factor ', 
    'TU-2 NM Human Contributing Factor ', 
    'TU-3 NM Human Contributing Factor ', 
    'TU-1 NM Safety Helmet ', 
    'TU-2 NM Safety Helmet ', 
    'TU-3 NM Safety Helmet ', 
    'TU-1 NM Alcohol Suspected ', 
    'TU-2 NM Alcohol Suspected ', 
    'TU-3 NM Alcohol Suspected ', 
    'TU-1 NM Marijuana Suspected ', 
    'TU-2 NM Marijuana Suspected ', 
    'TU-3 NM Marijuana Suspected ', 
    'TU-1 NM Other Drugs Suspected ', 
    'TU-2 NM Other Drugs Suspected ', 
    'TU-3 NM Other Drugs Suspected ', 
]

#'TU-1 Sex ', 'TU-1 NM Sex ', 'TU-2 Sex', 'TU-2 NM Sex '
#'TU-1 Safety Helmet', 'TU-1 NM Safety Helmet ', 'TU-2  Safety Helmet', 'TU-2 NM Safety Helmet '
# 'TU-1  Marijuana Suspected', 'TU-1 NM Marijuana Suspected ', 'TU-2 Marijuana Suspected', 'TU-2 NM Marijuana Suspected '

for column_name in renamed_mapped_columns_part2:
    print('COLUMN', column_name)
    print('New values')
    if column_name in list(cdot_new_pdf.columns):
        print(cdot_new_pdf[column_name].unique())
    print('Old converted values')
    print(converted_cdot_old_pdf[column_name].unique())
    print('combined new and old converted values')
    print(combined_cdot_pdf[column_name].unique())
    print()
    print()

COLUMN TU-1 Type
New values
['Unknown ' 'SUV' 'Passenger Car/Passenger Van' nan
 'Pickup Truck/Utility Van' 'Low Speed Vehicle'
 'Medium/Heavy Trucks, GVWR/GCWR 10,001 or Over' 'Motorcycle'
 'Medium/Heavy Trucks, GVWR/GCWR 16,001 or over'
 'Other Vehicle Type (Describe in Narrative)' 'Transit Bus'
 'Working Vehicle/Equipment' 'Motor Home' 'School Bus (all school buses)'
 'Autocycle'
 'Non-School Bus (nine occupants or more including driver) in commerce'
 'Off Highway Vehicle/ATV' 'Farm Equipment'
 'Pickup Truck/Utility Van with Trailer - RET' 'Snowmobile'
 'Passenger Car/Passenger Van with Trailer - RET']
Old converted values
['Unknown' 'Pickup Truck/Utility Van' 'Passenger Car/Passenger Van' 'SUV'
 'Other Vehicle Type (Describe in Narrative)' 'Motorcycle' ''
 'old__pickup_truck_utility_van_w_trailer'
 'old__truck_gvw_gr_10k_busses_gr_15_people'
 'Passenger Car/Passenger Van with Trailer - RET' 'old__SUV_w_trailer'
 'School Bus (all school buses)' 'Farm Equipment' 'Motor Home' nan]
combined new and old converted values
['Unknown' 'Pickup Truck/Utility Van' 'Passenger Car/Passenger Van' 'SUV'
 'Other Vehicle Type (Describe in Narrative)' 'Motorcycle' ''
 'old__pickup_truck_utility_van_w_trailer'
 'old__truck_gvw_gr_10k_busses_gr_15_people'
 'Passenger Car/Passenger Van with Trailer - RET' 'old__SUV_w_trailer'
 'School Bus (all school buses)' 'Farm Equipment' 'Motor Home' nan
 'Unknown ' 'Low Speed Vehicle'
 'Medium/Heavy Trucks, GVWR/GCWR 10,001 or Over'
 'Medium/Heavy Trucks, GVWR/GCWR 16,001 or over' 'Transit Bus'
 'Working Vehicle/Equipment' 'Autocycle'
 'Non-School Bus (nine occupants or more including driver) in commerce'
 'Off Highway Vehicle/ATV' 'Pickup Truck/Utility Van with Trailer - RET'
 'Snowmobile']


COLUMN TU-2 Type
New values
['Passenger Car/Passenger Van' 'Pickup Truck/Utility Van' nan 'SUV'
 'Other Vehicle Type (Describe in Narrative)' 'Working Vehicle/Equipment'
 'Motor Home'
 'Non-School Bus (nine occupants or more including driver) in commerce'
 'Unknown ' 'Medium/Heavy Trucks, GVWR/GCWR 10,001 or Over'
 'Medium/Heavy Trucks, GVWR/GCWR 16,001 or over' 'Motorcycle'
 'Off Highway Vehicle/ATV' 'Transit Bus' 'Heavy Train'
 'School Bus (all school buses)'
 'Pickup Truck/Utility Van with Trailer - RET' 'Low Speed Vehicle'
 'Farm Equipment' 'Autocycle' 'Light Rail']
Old converted values
['SUV' 'Passenger Car/Passenger Van' nan 'Unknown'
 'Pickup Truck/Utility Van' 'old__truck_gvw_gr_10k_busses_gr_15_people'
 'old__pickup_truck_utility_van_w_trailer' 'Motorcycle' ''
 'Other Vehicle Type (Describe in Narrative)'
 'Passenger Car/Passenger Van with Trailer - RET' 'old__SUV_w_trailer'
 'Motor Home' 'School Bus (all school buses)' 'Farm Equipment']
combined new and old converted values
['SUV' 'Passenger Car/Passenger Van' nan 'Unknown'
 'Pickup Truck/Utility Van' 'old__truck_gvw_gr_10k_busses_gr_15_people'
 'old__pickup_truck_utility_van_w_trailer' 'Motorcycle' ''
 'Other Vehicle Type (Describe in Narrative)'
 'Passenger Car/Passenger Van with Trailer - RET' 'old__SUV_w_trailer'
 'Motor Home' 'School Bus (all school buses)' 'Farm Equipment'
 'Working Vehicle/Equipment'
 'Non-School Bus (nine occupants or more including driver) in commerce'
 'Unknown ' 'Medium/Heavy Trucks, GVWR/GCWR 10,001 or Over'
 'Medium/Heavy Trucks, GVWR/GCWR 16,001 or over' 'Off Highway Vehicle/ATV'
 'Transit Bus' 'Heavy Train' 'Pickup Truck/Utility Van with Trailer - RET'
 'Low Speed Vehicle' 'Autocycle' 'Light Rail']


COLUMN TU-3 Type
New values
Old converted values
[nan 'Passenger Car/Passenger Van' 'Pickup Truck/Utility Van' 'Unknown'
 'SUV' 'old__truck_gvw_gr_10k_busses_gr_15_people'
 'Passenger Car/Passenger Van with Trailer - RET' ''
 'old__pickup_truck_utility_van_w_trailer'
 'Other Vehicle Type (Describe in Narrative)' 'Motor Home' 'Motorcycle'
 'old__SUV_w_trailer' 'School Bus (all school buses)']
combined new and old converted values
[nan 'Passenger Car/Passenger Van' 'Pickup Truck/Utility Van' 'Unknown'
 'SUV' 'old__truck_gvw_gr_10k_busses_gr_15_people'
 'Passenger Car/Passenger Van with Trailer - RET' ''
 'old__pickup_truck_utility_van_w_trailer'
 'Other Vehicle Type (Describe in Narrative)' 'Motor Home' 'Motorcycle'
 'old__SUV_w_trailer' 'School Bus (all school buses)']


COLUMN TU-1 Direction
New values
['East' 'North' 'South' 'West' nan 'Southeast' 'Northwest' 'Unknown'
 'Southwest' 'Northeast']
Old converted values
['South' 'North' 'West' 'Unknown' 'East' 'Southeast' 'Northwest'
 'Northeast' '' 'Southwest' nan]
combined new and old converted values
['South' 'North' 'West' 'Unknown' 'East' 'Southeast' 'Northwest'
 'Northeast' '' 'Southwest' nan]


COLUMN TU-2 Direction
New values
['North' 'East' 'South' nan 'West' 'Northwest' 'Northeast' 'Southeast'
 'Unknown' 'Southwest']
Old converted values
['South' 'North' nan 'Unknown' 'East' 'West' 'Northwest' '' 'Southeast'
 'Southwest' 'Northeast']
combined new and old converted values
['South' 'North' nan 'Unknown' 'East' 'West' 'Northwest' '' 'Southeast'
 'Southwest' 'Northeast']


COLUMN TU-3 Direction
New values
Old converted values
[nan 'North' 'South' 'Unknown' 'West' 'East' 'Southeast' 'Southwest' ''
 'Northwest' 'Northeast']
combined new and old converted values
[nan 'North' 'South' 'Unknown' 'West' 'East' 'Southeast' 'Southwest' ''
 'Northwest' 'Northeast']


COLUMN TU-1 Movement
New values
['Traveled Wrong Way' 'Going Straight' 'Making Left Turn' 'Out of Control'
 'Swerve/Avoidance' nan 'Changing Lanes' 'Entering Traffic Way/Merge'
 'Passing' 'Weaving' 'Making Right Turn' 'Other (Describe in Narrative)'
 'Negotiating a Curve' 'Stopped in Traffic'
 'Entering/Leaving Parked Position' 'Slowing' 'Backing' 'Making U-Turn'
 'Parked']
Old converted values
['Backing' 'Other (Describe in Narrative)' 'Swerve/Avoidance' nan
 'Changing Lanes' 'Going Straight' 'Entering/Leaving Parked Position'
 'Passing' 'Making Left Turn' 'Slowing' 'Weaving' 'Making U-Turn'
 'Making Right Turn' '' 'Parked' 'Stopped in Traffic' 'Traveled Wrong Way']
combined new and old converted values
['Backing' 'Other (Describe in Narrative)' 'Swerve/Avoidance' nan
 'Changing Lanes' 'Going Straight' 'Entering/Leaving Parked Position'
 'Passing' 'Making Left Turn' 'Slowing' 'Weaving' 'Making U-Turn'
 'Making Right Turn' '' 'Parked' 'Stopped in Traffic' 'Traveled Wrong Way'
 'Out of Control' 'Entering Traffic Way/Merge' 'Negotiating a Curve']


COLUMN TU-2 Movement
New values
['Going Straight' nan 'Parked' 'Negotiating a Curve' 'Slowing'
 'Stopped in Traffic' 'Making Left Turn' 'Making Right Turn'
 'Other (Describe in Narrative)' 'Changing Lanes' 'Passing' 'Backing'
 'Swerve/Avoidance' 'Entering Traffic Way/Merge' 'Out of Control'
 'Entering/Leaving Parked Position' 'Making U-Turn' 'Weaving'
 'Traveled Wrong Way']
Old converted values
['Parked' nan 'Going Straight' 'Other (Describe in Narrative)'
 'Making Left Turn' 'Stopped in Traffic' 'Slowing' 'Making Right Turn'
 'Swerve/Avoidance' 'Changing Lanes' '' 'Passing' 'Backing'
 'Entering/Leaving Parked Position' 'Making U-Turn' 'Weaving'
 'Traveled Wrong Way']
combined new and old converted values
['Parked' nan 'Going Straight' 'Other (Describe in Narrative)'
 'Making Left Turn' 'Stopped in Traffic' 'Slowing' 'Making Right Turn'
 'Swerve/Avoidance' 'Changing Lanes' '' 'Passing' 'Backing'
 'Entering/Leaving Parked Position' 'Making U-Turn' 'Weaving'
 'Traveled Wrong Way' 'Negotiating a Curve' 'Entering Traffic Way/Merge'
 'Out of Control']


COLUMN TU-3 Movement
New values
Old converted values
[nan 'Going Straight' 'Parked' 'Stopped in Traffic'
 'Other (Describe in Narrative)' 'Slowing' 'Changing Lanes'
 'Making Left Turn' '' 'Making U-Turn' 'Making Right Turn'
 'Swerve/Avoidance' 'Entering/Leaving Parked Position' 'Backing' 'Passing'
 'Weaving']
combined new and old converted values
[nan 'Going Straight' 'Parked' 'Stopped in Traffic'
 'Other (Describe in Narrative)' 'Slowing' 'Changing Lanes'
 'Making Left Turn' '' 'Making U-Turn' 'Making Right Turn'
 'Swerve/Avoidance' 'Entering/Leaving Parked Position' 'Backing' 'Passing'
 'Weaving']


COLUMN TU-1 Hit And Run
New values
[ True False]
Old converted values
[True False nan]
combined new and old converted values
[True False nan]


COLUMN TU-2 Hit And Run
New values
[False  True]
Old converted values
[False True nan]
combined new and old converted values
[False True nan]


COLUMN TU-3 Hit And Run
New values
Old converted values
[False True nan]
combined new and old converted values
[False True nan]


COLUMN TU-1 Speed Limit
New values
[ 25  40  45  50  65   0  30  35  75  20  55  60  15 400  10  70   5  24
 255  17  36   3   1 401 404   2 301  13  53  34  44  67  12   4  23 330
  26   6 553  14  32  64  42 658 652 105]
Old converted values
[nan 60.0 65.0 55.0 35.0 25.0 30.0 20.0 75.0 40.0 45.0 50.0 '' 15.0 10.0
 5.0 70.0 34.0 19.0 36.0 1.0 2.0 26.0 14.0 4.0 9.0 3.0 54.0 13.0 24.0 12.0
 80.0 31.0 56.0 8.0 6.0 33.0 49.0 16.0 90.0 39.0 53.0 44.0 46.0 22.0]
combined new and old converted values
[nan 60.0 65.0 55.0 35.0 25.0 30.0 20.0 75.0 40.0 45.0 50.0 '' 15.0 10.0
 5.0 70.0 34.0 19.0 36.0 1.0 2.0 26.0 14.0 4.0 9.0 3.0 54.0 13.0 24.0 12.0
 80.0 31.0 56.0 8.0 6.0 33.0 49.0 16.0 90.0 39.0 53.0 44.0 46.0 22.0 0 400
 255 17 401 404 301 67 23 330 553 32 64 42 658 652 105]


COLUMN TU-2 Speed Limit
New values
[ 25  35  40  45   0  30  20  55  15  65  75  50  60  10  70   5  24 425
   3   2 558   4  34   1  32 501 455   6  78  13 165 350  36  64  39 825
 254 600 355 301 100  44]
Old converted values
[nan 55.0 25.0 65.0 30.0 35.0 45.0 40.0 50.0 75.0 60.0 15.0 '' 20.0 10.0
 24.0 56.0 70.0 47.0 5.0 52.0 49.0 1.0 3.0 4.0 6.0 62.0 63.0 36.0 44.0
 23.0 26.0 27.0 64.0 22.0 2.0 34.0 28.0 46.0]
combined new and old converted values
[nan 55.0 25.0 65.0 30.0 35.0 45.0 40.0 50.0 75.0 60.0 15.0 '' 20.0 10.0
 24.0 56.0 70.0 47.0 5.0 52.0 49.0 1.0 3.0 4.0 6.0 62.0 63.0 36.0 44.0
 23.0 26.0 27.0 64.0 22.0 2.0 34.0 28.0 46.0 0 425 558 32 501 455 78 13
 165 350 39 825 254 600 355 301 100]


COLUMN TU-3 Speed Limit
New values
Old converted values
[nan 65.0 40.0 30.0 50.0 35.0 55.0 15.0 45.0 60.0 20.0 25.0 5.0 75.0 ''
 10.0 6.0 49.0]
combined new and old converted values
[nan 65.0 40.0 30.0 50.0 35.0 55.0 15.0 45.0 60.0 20.0 25.0 5.0 75.0 ''
 10.0 6.0 49.0]


COLUMN TU-1 Estimated Speed
New values
[ 40  10  43  45  50  65   0  20  15  75  35  30   5  25  70  60  80  90
  55   3 120 100   2  74  68   8 145  61 151  85  28  58  62   9  72  14
  24  77   4   7   1  12 125 102   6  37  11  47  66  21  57  19  63  69
  33  48 130  78  79  41  13  32  87  95  34  42  56  46  38  44  27  64
  67  52  53  51  18  81  99  49 105  76  29  23  96  73  88  22  17 755
  36  94  84  59  39  86  83  26 117  16 115  31  71  54  92 110  97 230
  82 154 101 200 109 150  91 353 510 111 104 129 455 656]
Old converted values
[nan 55.0 60.0 45.0 35.0 5.0 100.0 30.0 10.0 20.0 75.0 50.0 40.0 15.0 25.0
 65.0 70.0 13.0 2.0 3.0 12.0 '' 22.0 8.0 18.0 58.0 42.0 1.0 0.0 54.0 7.0
 80.0 67.0 27.0 95.0 48.0 93.0 105.0 53.0 32.0 82.0 63.0 90.0 68.0 14.0
 6.0 4.0 46.0 43.0 79.0 37.0 17.0 78.0 36.0 19.0 52.0 59.0 85.0 34.0 47.0
 87.0 83.0 62.0 21.0 56.0 28.0 24.0 9.0 66.0 33.0 61.0 38.0 64.0 107.0
 120.0 73.0 72.0 69.0 23.0 77.0 110.0 103.0 51.0 16.0 26.0 76.0 41.0 57.0
 99.0 455.0 145.0 88.0 510.0 44.0 94.0 29.0 91.0 435.0 11.0 39.0 98.0 71.0
 49.0 81.0 115.0 125.0 97.0 106.0 74.0 135.0 92.0 31.0 560.0 140.0 121.0
 96.0 117.0 101.0 108.0 89.0 126.0 84.0 134.0]
combined new and old converted values
[nan 55.0 60.0 45.0 35.0 5.0 100.0 30.0 10.0 20.0 75.0 50.0 40.0 15.0 25.0
 65.0 70.0 13.0 2.0 3.0 12.0 '' 22.0 8.0 18.0 58.0 42.0 1.0 0.0 54.0 7.0
 80.0 67.0 27.0 95.0 48.0 93.0 105.0 53.0 32.0 82.0 63.0 90.0 68.0 14.0
 6.0 4.0 46.0 43.0 79.0 37.0 17.0 78.0 36.0 19.0 52.0 59.0 85.0 34.0 47.0
 87.0 83.0 62.0 21.0 56.0 28.0 24.0 9.0 66.0 33.0 61.0 38.0 64.0 107.0
 120.0 73.0 72.0 69.0 23.0 77.0 110.0 103.0 51.0 16.0 26.0 76.0 41.0 57.0
 99.0 455.0 145.0 88.0 510.0 44.0 94.0 29.0 91.0 435.0 11.0 39.0 98.0 71.0
 49.0 81.0 115.0 125.0 97.0 106.0 74.0 135.0 92.0 31.0 560.0 140.0 121.0
 96.0 117.0 101.0 108.0 89.0 126.0 84.0 134.0 151 102 130 755 86 230 154
 200 109 150 353 111 104 129 656]


COLUMN TU-2 Estimated Speed
New values
[ 30  35   5  45   0  40  20  15  25  10  65  50  75  58   2  60   8  52
  55  72  70   1  38   3  28  26  80  93  42  12  53  36  63  48  47  32
  37  27  69  22   7  67  41  79  68   4  43  85  39  49  11  78  90  31
  23   6  29 356  18  99  33  24  71  19  76  64  17  84  13  34  77  61
  73  54  44  74  16  62  56  51  14  57 350  46 100   9  59 555 300  83
  88 320 215]
Old converted values
[0.0 nan 55.0 65.0 5.0 10.0 60.0 45.0 40.0 35.0 20.0 15.0 30.0 7.0 25.0
 9.0 36.0 50.0 '' 49.0 3.0 4.0 70.0 28.0 18.0 1.0 31.0 2.0 6.0 56.0 75.0
 47.0 67.0 58.0 38.0 77.0 54.0 16.0 8.0 80.0 32.0 24.0 12.0 72.0 63.0 22.0
 17.0 34.0 33.0 37.0 48.0 13.0 39.0 52.0 73.0 85.0 95.0 29.0 42.0 43.0
 27.0 69.0 19.0 23.0 62.0 53.0 57.0 74.0 68.0 26.0 46.0 79.0 76.0 59.0
 90.0 78.0 66.0 110.0 71.0 64.0 61.0 82.0 41.0 14.0 51.0 44.0 101.0 100.0
 11.0]
combined new and old converted values
[0.0 nan 55.0 65.0 5.0 10.0 60.0 45.0 40.0 35.0 20.0 15.0 30.0 7.0 25.0
 9.0 36.0 50.0 '' 49.0 3.0 4.0 70.0 28.0 18.0 1.0 31.0 2.0 6.0 56.0 75.0
 47.0 67.0 58.0 38.0 77.0 54.0 16.0 8.0 80.0 32.0 24.0 12.0 72.0 63.0 22.0
 17.0 34.0 33.0 37.0 48.0 13.0 39.0 52.0 73.0 85.0 95.0 29.0 42.0 43.0
 27.0 69.0 19.0 23.0 62.0 53.0 57.0 74.0 68.0 26.0 46.0 79.0 76.0 59.0
 90.0 78.0 66.0 110.0 71.0 64.0 61.0 82.0 41.0 14.0 51.0 44.0 101.0 100.0
 11.0 93 356 99 84 350 555 300 83 88 320 215]


COLUMN TU-3 Estimated Speed
New values
Old converted values
[nan 65.0 0.0 5.0 45.0 35.0 60.0 55.0 2.0 1.0 20.0 3.0 25.0 15.0 50.0 30.0
 10.0 40.0 '' 75.0 70.0 12.0 27.0 9.0 23.0 6.0 69.0 48.0 49.0 36.0 53.0
 7.0 8.0 38.0 71.0 68.0 57.0 26.0 78.0 47.0 62.0 42.0 24.0 63.0]
combined new and old converted values
[nan 65.0 0.0 5.0 45.0 35.0 60.0 55.0 2.0 1.0 20.0 3.0 25.0 15.0 50.0 30.0
 10.0 40.0 '' 75.0 70.0 12.0 27.0 9.0 23.0 6.0 69.0 48.0 49.0 36.0 53.0
 7.0 8.0 38.0 71.0 68.0 57.0 26.0 78.0 47.0 62.0 42.0 24.0 63.0]


COLUMN TU-1 Human Contributing Factor
New values
['Not Observed' 'No Apparent Contributing Factor' nan 'Looked/Did Not See'
 'Medical' 'Aggressive Driving' 'Other Factor (Describe in Narrative)'
 'Driver Inexperience' 'Age/Driver Ability' 'Distracted - Smoking'
 'Asleep or Fatigued' 'Distracted - Eating/Drinking'
 'Distracted - Other Exterior' 'Distracted/Other Occupant'
 'Distracted - Other Interior' 'Driver Unfamiliar With Area'
 'Driver Emotionally Upset' 'Evading Law Enforcement Officer'
 'Distracted - Talking on Phone/Holding'
 'Distracted - Manipulating Electronic Device' 'Physical Disability'
 'Sun Glare' 'Distracted - Manipulating Vehicle Control' 'Illness'
 'Distracted - Talking on Phone/ Hands Free']
Old converted values
['No Apparent Contributing Factor' nan 'Driver Unfamiliar With Area'
 'Distracted' 'Driver Inexperience' 'Asleep or Fatigued'
 'Asleep at the wheel' 'Illness' 'Driver Emotionally Upset' ''
 'Distracted/Other Occupant' 'Evading Law Enforcement Officer'
 'Physical Disability']
combined new and old converted values
['No Apparent Contributing Factor' nan 'Driver Unfamiliar With Area'
 'Distracted' 'Driver Inexperience' 'Asleep or Fatigued'
 'Asleep at the wheel' 'Illness' 'Driver Emotionally Upset' ''
 'Distracted/Other Occupant' 'Evading Law Enforcement Officer'
 'Physical Disability' 'Not Observed' 'Looked/Did Not See' 'Medical'
 'Aggressive Driving' 'Other Factor (Describe in Narrative)'
 'Age/Driver Ability' 'Distracted - Smoking'
 'Distracted - Eating/Drinking' 'Distracted - Other Exterior'
 'Distracted - Other Interior' 'Distracted - Talking on Phone/Holding'
 'Distracted - Manipulating Electronic Device' 'Sun Glare'
 'Distracted - Manipulating Vehicle Control'
 'Distracted - Talking on Phone/ Hands Free']


COLUMN TU-2 Human Contributing Factor
New values
['No Apparent Contributing Factor' nan 'Not Observed' 'Aggressive Driving'
 'Other Factor (Describe in Narrative)' 'Driver Emotionally Upset'
 'Looked/Did Not See' 'Distracted - Other Interior'
 'Distracted - Other Exterior' 'Age/Driver Ability'
 'Distracted - Manipulating Electronic Device'
 'Distracted - Eating/Drinking' 'Driver Unfamiliar With Area'
 'Driver Inexperience' 'Sun Glare' 'Asleep or Fatigued'
 'Distracted/Other Occupant' 'Distracted - Manipulating Vehicle Control'
 'Illness' 'Distracted - Talking on Phone/ Hands Free'
 'Distracted - Talking on Phone/Holding' 'Medical'
 'Evading Law Enforcement Officer' 'Physical Disability']
Old converted values
['No Apparent Contributing Factor' nan 'Driver Unfamiliar With Area'
 'Driver Inexperience' '' 'Asleep at the wheel' 'Distracted'
 'Driver Emotionally Upset' 'Illness' 'Distracted/Other Occupant'
 'Asleep or Fatigued' 'Evading Law Enforcement Officer']
combined new and old converted values
['No Apparent Contributing Factor' nan 'Driver Unfamiliar With Area'
 'Driver Inexperience' '' 'Asleep at the wheel' 'Distracted'
 'Driver Emotionally Upset' 'Illness' 'Distracted/Other Occupant'
 'Asleep or Fatigued' 'Evading Law Enforcement Officer' 'Not Observed'
 'Aggressive Driving' 'Other Factor (Describe in Narrative)'
 'Looked/Did Not See' 'Distracted - Other Interior'
 'Distracted - Other Exterior' 'Age/Driver Ability'
 'Distracted - Manipulating Electronic Device'
 'Distracted - Eating/Drinking' 'Sun Glare'
 'Distracted - Manipulating Vehicle Control'
 'Distracted - Talking on Phone/ Hands Free'
 'Distracted - Talking on Phone/Holding' 'Medical' 'Physical Disability']


COLUMN TU-3 Human Contributing Factor
New values
Old converted values
['No Apparent Contributing Factor' nan 'Distracted' 'Driver Inexperience'
 '' 'Distracted/Other Occupant' 'Asleep or Fatigued' 'Physical Disability'
 'Illness' 'Driver Unfamiliar With Area' 'Driver Emotionally Upset'
 'Asleep at the wheel' 'Evading Law Enforcement Officer']
combined new and old converted values
['No Apparent Contributing Factor' nan 'Distracted' 'Driver Inexperience'
 '' 'Distracted/Other Occupant' 'Asleep or Fatigued' 'Physical Disability'
 'Illness' 'Driver Unfamiliar With Area' 'Driver Emotionally Upset'
 'Asleep at the wheel' 'Evading Law Enforcement Officer']


COLUMN TU-1 Age
New values
[ nan  68.  50.  38.  62.  33.  16.   0.  25.  27.  28.  29.  17.  22.
  61.  24.  35.  67.  21.  23.  39.  37.  32.  43.  26.  18.  20.  31.
  47.  53.  36.  30.  44.  41.  82.  45.  49.  69.  42.  54.  64.  40.
  57.  65.  56.  34.  85.  52.  90.  58.  71.  19.  66.  60.  83.  63.
  59.  46.  70.  80.  55.  78.  72.  51.  75.  14.  48.  87.  89.  81.
  86.  73.  79.  88.  76.  15.  74.  77.  12.  84.   3.  10.  13.  96.
  91.   4.  92.   9.   5.  93.   7.  94.   2. 271.  11.   6.  98.   1.
  95.   8. 100. 124.  97. 104. 123.]
Old converted values
[0 27 30 17 28 20 18 29 24 74 16 51 26 25 19 37 21 46 22 58 65 44 36 33 63
 41 38 47 57 50 23 43 56 72 34 66 77 64 52 39 75 49 60 62 71 35 40 53 54
 45 '' 94 31 87 32 59 42 69 48 55 79 82 70 81 68 61 67 86 76 73 88 78 84
 80 83 14 91 15 90 89 85 92 95 nan 93 97 13 9 7 12 98 96 10 11 99]
combined new and old converted values
[0 27 30 17 28 20 18 29 24 74 16 51 26 25 19 37 21 46 22 58 65 44 36 33 63
 41 38 47 57 50 23 43 56 72 34 66 77 64 52 39 75 49 60 62 71 35 40 53 54
 45 '' 94 31 87 32 59 42 69 48 55 79 82 70 81 68 61 67 86 76 73 88 78 84
 80 83 14 91 15 90 89 85 92 95 nan 93 97 13 9 7 12 98 96 10 11 99 3.0 4.0
 5.0 2.0 271.0 6.0 1.0 8.0 100.0 124.0 104.0 123.0]


COLUMN TU-2 Age
New values
[ 36.  31.  50.  17.  nan  30.  25.  52.  71.  24.  38.  37.  40.  35.
  21.   0.  41.  56.  39.  54.  69.  33.  49.  18.  28.  16.  19.  51.
  58.  70.  68.  73.  43.  59.  29.  67.  53.  46.  23.  45.  42.  64.
  55.  72.  26.  75.  22.  63.  27.  47.  34.  32.  44.  76.  66.  60.
  61.  77.  57.  15.  20.  48.  79.  74.  65.  62.  89.  88.  78.  80.
   1.  95.  82.  81.  13.   6.  85.  84.  92.   8.  91.  10.   7.  83.
   5.  12.   4.  93.  14.   9.   2.  87.  86.  90.   3.  11.  94. 123.

In [42]:
# Other transformations 
columns=[
    'Number Killed', 
    'Number Injured',
    'Crash Time', 
    'Rd_Number', 
    'Rd_Section', 
    'City_Street',
    'Approach Overtaking Turn'
]

for column_name in columns:
    print('COLUMN', column_name)
    print('New values')
    print(cdot_new_pdf[column_name].unique())
    print('Old converted values')
    print(converted_cdot_old_pdf[column_name].unique())
    print('combined new and old converted values')
    print(combined_cdot_pdf[column_name].unique())
    print()
    print()

COLUMN Number Killed
New values
[0 1 2 3 4 5]
Old converted values
[ 0.  1. nan  2.  8.  3.]
combined new and old converted values
[ 0.  1. nan  2.  8.  3.  4.  5.]


COLUMN Number Injured
New values
[ 0  3  2  5  1  7  4  8  6  9 12 11 10]
Old converted values
[ 0.  1.  2.  3.  4.  5.  8.  6. nan 11.  9.  7. 10. 13.]
combined new and old converted values
[ 0.  1.  2.  3.  4.  5.  8.  6. nan 11.  9.  7. 10. 13. 12.]


COLUMN Crash Time
New values
['00:16:00' '00:34:00' '00:37:00' ... '04:56:00' '00:14:00' '04:37:00']
Old converted values
['00:00:00' '10:00:00' '60:00:00' ... '32:20:00' '14:60:00' '34:60:00']
combined new and old converted values
['00:00:00' '10:00:00' '60:00:00' ... '04:56:00' '00:14:00' '04:37:00']


COLUMN Rd_Number
New values
['0320' '391A' '093A' '1285' '082A' '085L' '0055' '0240' '0455' '030A'
 '0820' '287C' '025A' '0570' '0760' '0555' '070A' '0945' '121A' '044A'
 '225A' '034A' '0700' '0125' '036B' '1085' '0415' '4700' '0255' '040C'
 '160A' '0800' '3800' '024A' '086A' '088A' '1200' '070B' '095A' '006H'
 '1015' '076A' '0395' '083A' '085C' '067C' '1290' '0830' '285D' '128B'
 '040A' '0040' '007D' '0810' '050A' '045A' '0835' '0745' '5400' '085B'
 '177A' '0270' '0910' '0110' '1100' '550B' '0470' '0300' '138A' '392B'
 '119B' '0245' '1360' '119A' '0388' '270A' '034D' '0600' '1038' '1375'
 '1355' '0305' '013A' '014C' '470N' '0145' '006B' '009C' '0400' '392A'
 '0690' '1250' '0015' '034Z' '050C' '021B' '0490' '2400' '0175' '006G'
 '1086' '1500' '050B' '006E' '0590' '135A' '0130' '0185' '0580' '470B'
 '160C' '0330' '071D' '1125' '052A' '115A' '091A' '0045' '0915' '026B'
 '128A' '491B' '021A' '088B' '092A' '036?' '2700' '470A' '0059' '0193'
 '131B' '007A' '002A' '0630' '0730' '034B' '040B' '0315' '340A' '0817'
 '0465' '0825' '4400' '024G' '053A' '0660' '072A' '112A' '060B' '042A'
 '1800' '3400' '0430' '1400' '074A' '0900' '1000' '172A' '085A' '2300'
 '550A' '145A' '085H' '0765' '006J' '0350' '4200' '096A' '0540' '1900'
 '257A' '006F' '224A' '062A' '061A' '071C' '069A' '6100' '149A' '194A'
 '047A' '0735' '287A' '040H' '066B' '017B' '094A' '4800' '0454' '1235'
 '5600' '010A' '1240' '036E' '1380' '5300' '086B' '287B' '1195' '035A'
 '0200' '0280' '141A' '067A' '2000' '056B' '394A' '3300' '1378' '016A'
 '119C' '1055' '009D' '184A' '4100' '2900' '003A' '1223' '3500' '0160'
 '2200' '1299' '4000' '133A' '067F' '139A' '0665' '1600' '285B' '015B'
 '2800' '040Z' '079B' '3200' '4900' '0485' '2100' '065A' '285C' '385D'
 '036D' '0500' '024H' '144A' '491A' '090B' '285A' '5800' '007C' '5100'
 '006D' '002D' '159A' '0865' '0885' '0000' '014B' '350A' '5200' '0475'
 '0755' '157A' '0210' '0095' '006A' '0535' '4300' '1255' '1280' '0250'
 '022A' '1066' '007B' '1160' '1306' '0026' '1270' '058A' '0505' '5700'
 '1120' '0925' '3100' '1362' '1210' '0150' '0927' '0450' '084A' '1310'
 '0100' '270B' '0550' '0813' '0935' '0295' '125A' '013C' '067B' '085F'
 '001A' '0875' '2500' '006K' '1045' '114A' '0710' '0075' '015A' '105B'
 '0370' '0435' '1395' '0530' '085G' '141?' '5500' '0405' '1300' '385C'
 '136A' '0061' '1035' '1020' '6000' '181?' '078A' '1037' '024' '071F'
 '80002?' '370A' '0940' '0595' '0425' '006M' '3900' '140A' '0180' '2600'
 '0610' '0010' '008A' '1005' '105A' '0477' '071E' '009B' '014A' '0780'
 '064A' '265A' '070G' '1700' '287Z' '160Z' '0790' '0105' '167A' '096D'
 '0640' '325A' '0417' '012A' '070R' '0060' '063A' '?' '0850' '013B' '141B'
 '3600' '0615' '348A' '1135' '121?' '0333' '034C' '1344' '165A' '127A'
 '36?' '0063' '0380' '402A' '3000' '072' '036' '0775' '078?' '184B' '096B'
 '142A' '0065' '030?' '067D' '0965' '0090' '0184' '0695' nan '067E' '070'
 '0624' '006N' '0050' '0390' '024B' '052B' '017A' '050Z' '3700' '109A'
 '170A' '006C' '0985' '1262' '266A' '009A' '039A' '095C' '103A' '0645'
 '060A' '025C' '0087' '059A' '036C' '0360' '1233' '0220' '0920' '330A'
 '070Z' '0381' '88?' '125?' '470?' '287?' '075B' '040?' '0080' '046A'
 '1049' '113A' '059B' '291A' '196A' '0655' '95A?' '121B' '072B' '0826'
 '300' '0241' '1330' '85?' '096C' '265B' '134A' '318A' '5000' '1640172?'
 '1295' '470W' '0895' '0560' '0575' '024A?' '0385' '056A' '239A' '75?'
 '74?' '151A' '207A' '71?' '225?' '30A?' '83?' '050' '1345' '50?' '0155'
 '024F' '085E' '40?' '0845' '34?' '350?' '0525' '024E' '101A' '079A'
 '101?' '285?' '120A' '329B' '040E' '089A' '72?' '256A' '006L' '65?'
 '006?' '0027' '160?' '0625' '78?' '0901' '119?' '0287?' '60?' '085?'
 '145?' '76?' '6?' '030A?' '0017' '0237' '0960' '088A?' '0248' '1140'
 '0770' '6400' '0190' '368A' '82?' 'HWY3?' '385?' '116A' '579287?' '025?'
 '550B?' '003A?' '160150?' '024I' '0480' '257?' '1025' '491?' '93?' '050D'
 '91?' '036Z' '95?' '550?' '066A' '6300' '25?' '036A' '070Q' '82550?'
 '076?' '070L' '070?' '227A' '14?' '391?' '083A?' '371A' '0617' '291?'
 '127?' '66?' '347A' '007D?' '085' '1220' '086?' '0981' '184?' '0066'
 '0970' '052A?' '67?' '181250?' '60150?' '105?' '1390' '071B' '100050?'
 '85G?' '231A' '024G?' '24?' '252550?' '71150?' 'I225?' '114?' 'I-25'
 '006G?' '392?' '8?' '402?' 'WELD?' 'MM?' '144?' '024D' '115?' '385A'
 '385B' '150A' '1060' '075?' '13?' '0016' '631085?' '56?' '152550?' '70?'
 '072A?' '0941' '348?' '1385' '040F' '050?' 'I25?' '53?' '138A?' '16?'
 '4500' '025A?' '095?' '45?' '9?' '177?' '083?' '0086' '085D' '142550?'
 '368585?' '1225' '034?' '034S' '024C' '0621' '0335' '52?' '70B?' '088?'
 '71950?' '006I' '1046' '103?' 'I 25?' '093?' '650?' '7?' '139?' '5900'
 '400?' '300A' '69?' '0301' '095S' 'CO S?' '340?' '056?' '270?' 'US 4?'
 '6TH ?' '0671' '2734?' '128?' '2?' 'I270?' '86?' 'I 76?' '4800270?'
 '34 ?' '0721' 'I76?' '58?' '44?' '224?' '96?' '47?' '1010' '87?' '491C'
 '231?' '50E?' '392A?' '330?' '0165' '10150?' '0451' 'I 70?' '79?' '34A?'
 '257A?' 'CO 8?' '0097' '0310' 'US85?' 'US 2?' '138?' '1325' '30?' '61?'
 '285D?' 'HWY ?' '096?' '10050?' 'I70?' '3400119?' '85H?' '060B?' '157?'
 '330085?' '047?' '086A?' '196?' '095A?' '1?' '135?' '034A?' '165?'
 'US 3?' '053?' '207?' '026B?' '650243?' '39?' '92?' '040C?' '17?' 'I70 ?'
 '085B?' '225A?' '62?' '002A?']
Old converted values
[nan '160.0A' '25.0A' '35.0A' '50.0C' '70.0A' '30.0A' '287.0C' '34.0D'
 '63.0A' '40.0C' '95.0A' '184.0B' '64.0A' '40.0A' '24.0A' '6.0D' '131.0B'
 '70.0F' '50.0A' '7.0C' '13.0B' '114.0A' '385.0C' '71.0F' '34.0A' '145.0A'
 '88.0A' '65.0A' '121.0A' '83.0A' '225.0A' '157.0A' '285.0D' '79.0B'
 '14.0C' '14.0B' '34.0B' '119.0A' '470.0B' '140.0A' '6.0F' '36.0B' '82.0A'
 '6.0C' '6.0G' '6.0H' '67.0F' '160.0C' '70.0B' '385.0D' '9.0C' '40.0H'
 '550.0B' '7.0D' '92.0A' '115.0A' '13.0A' '88.0B' '470.0A' '285.0B'
 '119.0C' '26.0B' '85.0B' '160.0Z' '24.0H' '391.0A' '21.0B' '16.0A'
 '52.0B' '6.0B' '47.0A' '72.0A' '34.0Z' '93.0A' '128.0B' '2.0A' '177.0A'
 '91.0A' '85.0C' '133.0A' '491.0B' '6.0E' '50.0B' '60.0B' '159.0A' '45.0A'
 '270.0A' '40.0B' '6.0Z' '135.0A' '70.0L' '138.0A' '85.0A' '58.0A' '40.0Z'
 '67.0C' '350.0A' '76.0A' '21.0A' '6.0A' '12.0A' '340.0A' '74.0A' '69.0A'
 '138.0Z' '105.0A' '119.0B' '90.0B' '9.0B' '24.0C' '60.0A' '134.0A'
 '96.0A' '24.0G' '224.0A' '270.0B' '392.0B' '86.0B' '149.0A' '112.0A'
 '85.0L' '90.0A' '71.0D' '318.0A' '52.0A' '9.0D' '15.0A' '109.0A' '6.0I'
 '285.0C' '86.0A' '287.0Z' '392.0A' '6.0J' '139.0A' '9.0A' '66.0B'
 '144.0A' '402.0A' '257.0A' '56.0B' '7.0A' '265.0A' '151.0A' '113.0A'
 '172.0A' '125.0A' '44.0A' '53.0A' '62.0A' '36.0C' '10.0A' '50.0Z'
 '348.0A' '287.0A' '36.0D' '550.0A' '128.0A' '70.0Z' '85.0F' '470.0N'
 '67.0D' '94.0A' '371.0A' '287.0B' '85.0G' '70.0G' '36.0Z' '1.0A' '34.0C'
 '71.0C' '13.0C' '285.0A' '96.0C' '42.0A' '8.0A' '17.0B' '6.0N' '36.0A'
 '141.0A' '141.0B' '75.0B' '165.0A' '14.0A' '36.0E' '46.0A' '385.0B'
 '470.0W' '78.0A' '127.0A' '3.0A' '7.0B' '103.0A' '265.0B' '24.0I' '24.0E'
 '96.0B' '330.0A' '71.0A' '61.0A' '59.0A' '291.0A' '71.0E' '170.0A'
 '85.0H' '84.0A' '24.0B' '6.0M' '370.0A' '194.0A' '39.0A' '59.0B' '71.0B'
 '72.0B' '89.0A' '207.0A' '491.0A' '142.0A' '67.0E' '15.0B' '70.0R'
 '325.0A' '266.0A' '394.0A' '6.0K' '67.0A' '25.0C' '2.0D' '85.0E' '96.0D'
 '184.0A' '97.0A' '385.0E' '17.0A' '24.0F' '105.0B' '167.0A' '6.0L'
 '196.0A' '70.0E' '22.0A' '368.0A' '40.0E' '150.0A' '300.0A' '120.0A'
 '121.0B' '239.0A' '385.0A' '209.0A' '160.0B' '70.0K' '67.0B' '11.0A'
 '131.0A' '136.0A' '231.0A' '25.0B' '257.0B' '278.0C']
combined new and old converted values
[nan '160.0A' '25.0A' '35.0A' '50.0C' '70.0A' '30.0A' '287.0C' '34.0D'
 '63.0A' '40.0C' '95.0A' '184.0B' '64.0A' '40.0A' '24.0A' '6.0D' '131.0B'
 '70.0F' '50.0A' '7.0C' '13.0B' '114.0A' '385.0C' '71.0F' '34.0A' '145.0A'
 '88.0A' '65.0A' '121.0A' '83.0A' '225.0A' '157.0A' '285.0D' '79.0B'
 '14.0C' '14.0B' '34.0B' '119.0A' '470.0B' '140.0A' '6.0F' '36.0B' '82.0A'
 '6.0C' '6.0G' '6.0H' '67.0F' '160.0C' '70.0B' '385.0D' '9.0C' '40.0H'
 '550.0B' '7.0D' '92.0A' '115.0A' '13.0A' '88.0B' '470.0A' '285.0B'
 '119.0C' '26.0B' '85.0B' '160.0Z' '24.0H' '391.0A' '21.0B' '16.0A'
 '52.0B' '6.0B' '47.0A' '72.0A' '34.0Z' '93.0A' '128.0B' '2.0A' '177.0A'
 '91.0A' '85.0C' '133.0A' '491.0B' '6.0E' '50.0B' '60.0B' '159.0A' '45.0A'
 '270.0A' '40.0B' '6.0Z' '135.0A' '70.0L' '138.0A' '85.0A' '58.0A' '40.0Z'
 '67.0C' '350.0A' '76.0A' '21.0A' '6.0A' '12.0A' '340.0A' '74.0A' '69.0A'
 '138.0Z' '105.0A' '119.0B' '90.0B' '9.0B' '24.0C' '60.0A' '134.0A'
 '96.0A' '24.0G' '224.0A' '270.0B' '392.0B' '86.0B' '149.0A' '112.0A'
 '85.0L' '90.0A' '71.0D' '318.0A' '52.0A' '9.0D' '15.0A' '109.0A' '6.0I'
 '285.0C' '86.0A' '287.0Z' '392.0A' '6.0J' '139.0A' '9.0A' '66.0B'
 '144.0A' '402.0A' '257.0A' '56.0B' '7.0A' '265.0A' '151.0A' '113.0A'
 '172.0A' '125.0A' '44.0A' '53.0A' '62.0A' '36.0C' '10.0A' '50.0Z'
 '348.0A' '287.0A' '36.0D' '550.0A' '128.0A' '70.0Z' '85.0F' '470.0N'
 '67.0D' '94.0A' '371.0A' '287.0B' '85.0G' '70.0G' '36.0Z' '1.0A' '34.0C'
 '71.0C' '13.0C' '285.0A' '96.0C' '42.0A' '8.0A' '17.0B' '6.0N' '36.0A'
 '141.0A' '141.0B' '75.0B' '165.0A' '14.0A' '36.0E' '46.0A' '385.0B'
 '470.0W' '78.0A' '127.0A' '3.0A' '7.0B' '103.0A' '265.0B' '24.0I' '24.0E'
 '96.0B' '330.0A' '71.0A' '61.0A' '59.0A' '291.0A' '71.0E' '170.0A'
 '85.0H' '84.0A' '24.0B' '6.0M' '370.0A' '194.0A' '39.0A' '59.0B' '71.0B'
 '72.0B' '89.0A' '207.0A' '491.0A' '142.0A' '67.0E' '15.0B' '70.0R'
 '325.0A' '266.0A' '394.0A' '6.0K' '67.0A' '25.0C' '2.0D' '85.0E' '96.0D'
 '184.0A' '97.0A' '385.0E' '17.0A' '24.0F' '105.0B' '167.0A' '6.0L'
 '196.0A' '70.0E' '22.0A' '368.0A' '40.0E' '150.0A' '300.0A' '120.0A'
 '121.0B' '239.0A' '385.0A' '209.0A' '160.0B' '70.0K' '67.0B' '11.0A'
 '131.0A' '136.0A' '231.0A' '25.0B' '257.0B' '278.0C' '0320' '391A' '093A'
 '1285' '082A' '085L' '0055' '0240' '0455' '030A' '0820' '287C' '025A'
 '0570' '0760' '0555' '070A' '0945' '121A' '044A' '225A' '034A' '0700'
 '0125' '036B' '1085' '0415' '4700' '0255' '040C' '160A' '0800' '3800'
 '024A' '086A' '088A' '1200' '070B' '095A' '006H' '1015' '076A' '0395'
 '083A' '085C' '067C' '1290' '0830' '285D' '128B' '040A' '0040' '007D'
 '0810' '050A' '045A' '0835' '0745' '5400' '085B' '177A' '0270' '0910'
 '0110' '1100' '550B' '0470' '0300' '138A' '392B' '119B' '0245' '1360'
 '119A' '0388' '270A' '034D' '0600' '1038' '1375' '1355' '0305' '013A'
 '014C' '470N' '0145' '006B' '009C' '0400' '392A' '0690' '1250' '0015'
 '034Z' '050C' '021B' '0490' '2400' '0175' '006G' '1086' '1500' '050B'
 '006E' '0590' '135A' '0130' '0185' '0580' '470B' '160C' '0330' '071D'
 '1125' '052A' '115A' '091A' '0045' '0915' '026B' '128A' '491B' '021A'
 '088B' '092A' '036?' '2700' '470A' '0059' '0193' '131B' '007A' '002A'
 '0630' '0730' '034B' '040B' '0315' '340A' '0817' '0465' '0825' '4400'
 '024G' '053A' '0660' '072A' '112A' '060B' '042A' '1800' '3400' '0430'
 '1400' '074A' '0900' '1000' '172A' '085A' '2300' '550A' '145A' '085H'
 '0765' '006J' '0350' '4200' '096A' '0540' '1900' '257A' '006F' '224A'
 '062A' '061A' '071C' '069A' '6100' '149A' '194A' '047A' '0735' '287A'
 '040H' '066B' '017B' '094A' '4800' '0454' '1235' '5600' '010A' '1240'
 '036E' '1380' '5300' '086B' '287B' '1195' '035A' '0200' '0280' '141A'
 '067A' '2000' '056B' '394A' '3300' '1378' '016A' '119C' '1055' '009D'
 '184A' '4100' '2900' '003A' '1223' '3500' '0160' '2200' '1299' '4000'
 '133A' '067F' '139A' '0665' '1600' '285B' '015B' '2800' '040Z' '079B'
 '3200' '4900' '0485' '2100' '065A' '285C' '385D' '036D' '0500' '024H'
 '144A' '491A' '090B' '285A' '5800' '007C' '5100' '006D' '002D' '159A'
 '0865' '0885' '0000' '014B' '350A' '5200' '0475' '0755' '157A' '0210'
 '0095' '006A' '0535' '4300' '1255' '1280' '0250' '022A' '1066' '007B'
 '1160' '1306' '0026' '1270' '058A' '0505' '5700' '1120' '0925' '3100'
 '1362' '1210' '0150' '0927' '0450' '084A' '1310' '0100' '270B' '0550'
 '0813' '0935' '0295' '125A' '013C' '067B' '085F' '001A' '0875' '2500'
 '006K' '1045' '114A' '0710' '0075' '015A' '105B' '0370' '0435' '1395'
 '0530' '085G' '141?' '5500' '0405' '1300' '385C' '136A' '0061' '1035'
 '1020' '6000' '181?' '078A' '1037' '024' '071F' '80002?' '370A' '0940'
 '0595' '0425' '006M' '3900' '140A' '0180' '2600' '0610' '0010' '008A'
 '1005' '105A' '0477' '071E' '009B' '014A' '0780' '064A' '265A' '070G'
 '1700' '287Z' '160Z' '0790' '0105' '167A' '096D' '0640' '325A' '0417'
 '012A' '070R' '0060' '063A' '?' '0850' '013B' '141B' '3600' '0615' '348A'
 '1135' '121?' '0333' '034C' '1344' '165A' '127A' '36?' '0063' '0380'
 '402A' '3000' '072' '036' '0775' '078?' '184B' '096B' '142A' '0065'
 '030?' '067D' '0965' '0090' '0184' '0695' '067E' '070' '0624' '006N'
 '0050' '0390' '024B' '052B' '017A' '050Z' '3700' '109A' '170A' '006C'
 '0985' '1262' '266A' '009A' '039A' '095C' '103A' '0645' '060A' '025C'
 '0087' '059A' '036C' '0360' '1233' '0220' '0920' '330A' '070Z' '0381'
 '88?' '125?' '470?' '287?' '075B' '040?' '0080' '046A' '1049' '113A'
 '059B' '291A' '196A' '0655' '95A?' '121B' '072B' '0826' '300' '0241'
 '1330' '85?' '096C' '265B' '134A' '318A' '5000' '1640172?' '1295' '470W'
 '0895' '0560' '0575' '024A?' '0385' '056A' '239A' '75?' '74?' '151A'
 '207A' '71?' '225?' '30A?' '83?' '050' '1345' '50?' '0155' '024F' '085E'
 '40?' '0845' '34?' '350?' '0525' '024E' '101A' '079A' '101?' '285?'
 '120A' '329B' '040E' '089A' '72?' '256A' '006L' '65?' '006?' '0027'
 '160?' '0625' '78?' '0901' '119?' '0287?' '60?' '085?' '145?' '76?' '6?'
 '030A?' '0017' '0237' '0960' '088A?' '0248' '1140' '0770' '6400' '0190'
 '368A' '82?' 'HWY3?' '385?' '116A' '579287?' '025?' '550B?' '003A?'
 '160150?' '024I' '0480' '257?' '1025' '491?' '93?' '050D' '91?' '036Z'
 '95?' '550?' '066A' '6300' '25?' '036A' '070Q' '82550?' '076?' '070L'
 '070?' '227A' '14?' '391?' '083A?' '371A' '0617' '291?' '127?' '66?'
 '347A' '007D?' '085' '1220' '086?' '0981' '184?' '0066' '0970' '052A?'
 '67?' '181250?' '60150?' '105?' '1390' '071B' '100050?' '85G?' '231A'
 '024G?' '24?' '252550?' '71150?' 'I225?' '114?' 'I-25' '006G?' '392?'
 '8?' '402?' 'WELD?' 'MM?' '144?' '024D' '115?' '385A' '385B' '150A'
 '1060' '075?' '13?' '0016' '631085?' '56?' '152550?' '70?' '072A?' '0941'
 '348?' '1385' '040F' '050?' 'I25?' '53?' '138A?' '16?' '4500' '025A?'
 '095?' '45?' '9?' '177?' '083?' '0086' '085D' '142550?' '368585?' '1225'
 '034?' '034S' '024C' '0621' '0335' '52?' '70B?' '088?' '71950?' '006I'
 '1046' '103?' 'I 25?' '093?' '650?' '7?' '139?' '5900' '400?' '300A'
 '69?' '0301' '095S' 'CO S?' '340?' '056?' '270?' 'US 4?' '6TH ?' '0671'
 '2734?' '128?' '2?' 'I270?' '86?' 'I 76?' '4800270?' '34 ?' '0721' 'I76?'
 '58?' '44?' '224?' '96?' '47?' '1010' '87?' '491C' '231?' '50E?' '392A?'
 '330?' '0165' '10150?' '0451' 'I 70?' '79?' '34A?' '257A?' 'CO 8?' '0097'
 '0310' 'US85?' 'US 2?' '138?' '1325' '30?' '61?' '285D?' 'HWY ?' '096?'
 '10050?' 'I70?' '3400119?' '85H?' '060B?' '157?' '330085?' '047?' '086A?'
 '196?' '095A?' '1?' '135?' '034A?' '165?' 'US 3?' '053?' '207?' '026B?'
 '650243?' '39?' '92?' '040C?' '17?' 'I70 ?' '085B?' '225A?' '62?' '002A?']


COLUMN Rd_Section
New values
['SANTA' '8.482' '16.461' ... 'DURAS' '348?' '295.29?']
Old converted values
['SYCAM' 'NIGHT' '123.1' ... '321.33' '186.85' 'EVESH']
combined new and old converted values
['SYCAM' 'NIGHT' '123.1' ... 'DURAS' '348?' '295.29?']


COLUMN City_Street
New values
['THAVE' nan 'COLOR' ... 'GULFS' 'IDYLW' 'DURAS']
Old converted values
[nan]
combined new and old converted values
[nan 'THAVE' 'COLOR' ... 'GULFS' 'IDYLW' 'DURAS']


COLUMN Approach Overtaking Turn
New values
['Not Applicable' 'Approach Turn' 'Overtaking Turn' nan]
Old converted values
['Not Applicable' 'Approach Turn' 'Overtaking Turn' nan]
combined new and old converted values
['Not Applicable' 'Approach Turn' 'Overtaking Turn' nan]

### Check Motorist vs. Non-Motorist Columns

In [95]:
combined_cdot_pdf['TU-1 Type'].unique()

combined_cdot_pdf.loc[combined_cdot_pdf['TU-1 Type'].isna(), 'TU-1 Type'] = ''
combined_cdot_pdf.loc[combined_cdot_pdf['TU-1 NM Type'].isna(), 'TU-1 NM Type'] = ''
combined_cdot_pdf.loc[combined_cdot_pdf['TU-2 Type'].isna(), 'TU-2 Type'] = ''
combined_cdot_pdf.loc[combined_cdot_pdf['TU-2 NM Type'].isna(), 'TU-2 NM Type'] = ''
combined_cdot_pdf.loc[combined_cdot_pdf['TU-3 Type'].isna(), 'TU-3 Type'] = ''
combined_cdot_pdf.loc[combined_cdot_pdf['TU-3 NM Type'].isna(), 'TU-3 NM Type'] = ''

In [98]:
pop_tu1_type = combined_cdot_pdf.loc[combined_cdot_pdf['TU-1 Type'] != '', ['TU-1 Type', 'TU-1 NM Type']]

display(pop_tu1_type)
print(pop_tu1_type['TU-1 NM Type'].unique())

                         TU-1 Type TU-1 NM Type
0                          Unknown
1                          Unknown
2         Pickup Truck/Utility Van
3                          Unknown
4                          Unknown
...                            ...          ...
92805  Passenger Car/Passenger Van
92806                     Unknown
92807                          SUV
92808  Passenger Car/Passenger Van
92809  Passenger Car/Passenger Van

[176572 rows x 2 columns]

['' 'Bicyclist' 'Pedestrian' 'Scooter']

In [97]:
display(combined_cdot_pdf.loc[(combined_cdot_pdf['TU-1 Type'] != '') & (combined_cdot_pdf['TU-1 NM Type'] != ''), ['TU-1 Type', 'TU-1 NM Type']])
display(combined_cdot_pdf.loc[(combined_cdot_pdf['TU-2 Type'] != '') & (combined_cdot_pdf['TU-2 NM Type'] != ''), ['TU-2 Type', 'TU-2 NM Type']])
display(combined_cdot_pdf.loc[(combined_cdot_pdf['TU-3 Type'] != '') & (combined_cdot_pdf['TU-3 NM Type'] != ''), ['TU-3 Type', 'TU-3 NM Type']])

                                        TU-1 Type TU-1 NM Type
51971                 Passenger Car/Passenger Van    Bicyclist
56178                 Passenger Car/Passenger Van    Bicyclist
63484                 Passenger Car/Passenger Van   Pedestrian
67540  Other Vehicle Type (Describe in Narrative)      Scooter
69996                                    Unknown     Bicyclist

Empty DataFrame
Columns: [TU-2 Type, TU-2 NM Type]
Index: []

Empty DataFrame
Columns: [TU-3 Type, TU-3 NM Type]
Index: []

In [99]:
# CHECK THAT ALL COLUMNS WITH MOTORISTS AND NON-MOTORISTS ARE AS EXPECTED 
# When it is a motorist - all NM columns should be empty 
# and vice versa 

# check if there are any rows where TU-1 Type is populated but TU-1 Age is not 
print(combined_cdot_pdf.loc[(combined_cdot_pdf['TU-1 Type'] != '') & (combined_cdot_pdf['TU-1 Age'] == ''), ['TU-1 Type', 'TU-1 Age']].shape)

# check if there are any rows where TU-1 NM Type is populated but TU-1 NM Age is Not
print(combined_cdot_pdf.loc[(combined_cdot_pdf['TU-1 NM Type'] != '') & (combined_cdot_pdf['TU-1 NM Age '] == ''), ['TU-1 NM Type', 'TU-1 NM Age ']].shape)

(0, 2)
(0, 2)

In [100]:
combined_cdot_pdf.shape

(179114, 148)